<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-27">

<title>Race the Reaper – MTG Decks — Daily Standard Guides</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a8dd2cfac03084eab458e3b1c626e1f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MTG Decks — Daily Standard Guides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a>
  <ul class="collapse">
  <li><a href="#game-plan-phases" id="toc-game-plan-phases" class="nav-link" data-scroll-target="#game-plan-phases">Game plan phases</a></li>
  <li><a href="#card-roles" id="toc-card-roles" class="nav-link" data-scroll-target="#card-roles">Card roles</a></li>
  <li><a href="#lands-as-engines" id="toc-lands-as-engines" class="nav-link" data-scroll-target="#lands-as-engines">Lands as engines</a></li>
  <li><a href="#curve-and-mana" id="toc-curve-and-mana" class="nav-link" data-scroll-target="#curve-and-mana">Curve and mana</a></li>
  </ul></li>
  <li><a href="#gameplay-strategy" id="toc-gameplay-strategy" class="nav-link" data-scroll-target="#gameplay-strategy">Gameplay strategy</a>
  <ul class="collapse">
  <li><a href="#early-game" id="toc-early-game" class="nav-link" data-scroll-target="#early-game">Early game</a></li>
  <li><a href="#mid-game" id="toc-mid-game" class="nav-link" data-scroll-target="#mid-game">Mid game</a></li>
  <li><a href="#the-combo-turn" id="toc-the-combo-turn" class="nav-link" data-scroll-target="#the-combo-turn">The combo turn</a></li>
  <li><a href="#the-second-win-condition" id="toc-the-second-win-condition" class="nav-link" data-scroll-target="#the-second-win-condition">The second win condition</a></li>
  <li><a href="#mulligan-guide" id="toc-mulligan-guide" class="nav-link" data-scroll-target="#mulligan-guide">Mulligan guide</a></li>
  <li><a href="#key-interactions-and-edge-cases" id="toc-key-interactions-and-edge-cases" class="nav-link" data-scroll-target="#key-interactions-and-edge-cases">Key interactions and edge cases</a></li>
  <li><a href="#matchups" id="toc-matchups" class="nav-link" data-scroll-target="#matchups">Matchups</a></li>
  </ul></li>
  <li><a href="#iterations" id="toc-iterations" class="nav-link" data-scroll-target="#iterations">Iterations</a></li>
  <li><a href="#deck-list-arena-import" id="toc-deck-list-arena-import" class="nav-link" data-scroll-target="#deck-list-arena-import">Deck list (Arena import)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Race the Reaper</h1>
<p class="subtitle lead">Blue, black, red and green — Fathomless descent x Manifest dread x Max speed: mill your own permanents to grow the graveyard, then race the clock to kill</p>
  <div class="quarto-categories">
    <div class="quarto-category">combo</div>
    <div class="quarto-category">Fathomless descent</div>
    <div class="quarto-category">Manifest dread</div>
    <div class="quarto-category">Max speed</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 27, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="at-a-glance" class="level1">
<h1>At a glance</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 61%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Format</td>
<td>Standard (MTGA)</td>
</tr>
<tr class="even">
<td>Colors</td>
<td>Blue, black, red and green (four colors, no white)</td>
</tr>
<tr class="odd">
<td>Archetype</td>
<td>Combo-midrange: a graveyard engine that turns manifest dread into fathomless descent, and an attacking clock that turns combat damage into max speed</td>
</tr>
<tr class="even">
<td>Size</td>
<td>60 cards (36 nonlands, 24 lands)</td>
</tr>
<tr class="odd">
<td>Primary win</td>
<td>The max speed mill engine: Aether Syphon plus Vnwxt, Verbose Host and The Speed Demon. At max speed every card you draw mills each opponent two cards, and the deck draws four extra cards a turn, so the opponent’s library is a clock</td>
</tr>
<tr class="even">
<td>Secondary win</td>
<td>Fathomless descent beatdown: Souls of the Lost is a two mana creature whose power equals the number of permanent cards in your graveyard, Squirming Emergence returns a big permanent from the graveyard for free, and The Speed Demon closes with flying trample</td>
</tr>
<tr class="odd">
<td>Land win cons</td>
<td>Avishkar Raceway is a land that starts your engines and, at max speed, loots for three mana (discard a card, draw a card) — every one of those draws is two more cards milled off each opponent with Aether Syphon on board. Amonkhet Raceway grants haste at max speed, which turns a freshly cast Souls of the Lost or Speed Demon into unexpected lethal</td>
</tr>
</tbody>
</table>
</section>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>Race the Reaper is built on three rolled mechanics: Fathomless descent, Manifest dread and Max speed, in four colors. They fit together better than they look, because all three want the same thing: a body on the board every turn and a life total that keeps moving down.</p>
<p>Manifest dread is the fuel line. Every manifest dread looks at the top two cards of the library, puts one onto the battlefield face down as a 2/2 and the other into the graveyard. That is two resources from one spell: a creature that can attack, and a permanent card in the graveyard. Fathomless descent counts exactly those permanent cards, so each manifest dread also grows the descent payoffs. There are thirteen cards that manifest dread: four Manifest Dread at two mana, three Hauntwoods Shrieker that trigger on every attack, two Growing Dread at instant speed, two Threats Around Every Corner that also ramp a basic land every time a face down permanent enters, and two Abhorrent Oculus that trigger on each opponent’s upkeep.</p>
<p>Fathomless descent is the payoff. Souls of the Lost costs two mana and its power is the number of permanent cards in your graveyard, with toughness one higher, so after three or four manifest dreads it is a four or five power creature for two. Squirming Emergence is the free reanimation spell: return any nonland permanent card from the graveyard with mana value at most that same count, which comfortably reaches Hauntwoods Shrieker, Abhorrent Oculus, Racers’ Scoreboard and The Speed Demon.</p>
<p>Max speed is the finish line. Every card that starts your engines gives you speed 1, and speed increases once each of your turns when an opponent loses life, up to 4. Attacking is how this deck pays for that: three Deep-Cavern Bat with flying and lifelink, three Sinkhole Surveyor that grow every attack, face down 2/2s, and eventually a 5/5 flying trample Speed Demon. Once speed reaches 4 the max speed clauses switch on: Aether Syphon mills each opponent two cards on every draw, Vnwxt doubles every draw, The Speed Demon draws four cards at end of turn, Racers’ Scoreboard makes every spell cost one less, Endrider Catalyzer taps for two red mana and Avishkar Raceway loots. Mill two per draw, draw four a turn, and the opponent’s deck is the win condition.</p>
<p>The deck is genuinely a combo, but a resilient one. It has 23 creatures, so it attacks from turn two while the engine assembles, and it never needs both halves at once: manifest dread into descent beats wins games on its own, and so does an aggressive start that reaches max speed with two mana open.</p>
</section>
<section id="approach" class="level1">
<h1>Approach</h1>
<section id="game-plan-phases" class="level2">
<h2 class="anchored" data-anchor-id="game-plan-phases">Game plan phases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>What happens</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Turn 1</td>
<td>A land. The three Raceways and every dual land come in untapped, and each Raceway starts your engines on turn one, so the speed clock is running before the deck casts anything</td>
</tr>
<tr class="even">
<td>Turns 2-3</td>
<td>The engine starts: Manifest Dread, Souls of the Lost fed by a discarded card or a spare body, Deep-Cavern Bat for flying lifelink and a look at the opponent’s hand, Sinkhole Surveyor to grow every attack, Vnwxt to start drawing a turn early</td>
</tr>
<tr class="odd">
<td>Turns 4-5</td>
<td>Depth and a clock: Hauntwoods Shrieker attacks and manifests every combat, Aether Syphon starts milling, Threats Around Every Corner ramps a land per face down permanent, Racers’ Scoreboard refuels and starts the discount, The Speed Demon arrives as a 5/5 flying trampler</td>
</tr>
<tr class="even">
<td>Turns 6+</td>
<td>Max speed. Every draw mills the opponent, Vnwxt doubles the draws, Avishkar Raceway and Racers’ Scoreboard keep the hand full while the graveyard feeds Souls of the Lost and Squirming Emergence for a second wave</td>
</tr>
</tbody>
</table>
</section>
<section id="card-roles" class="level2">
<h2 class="anchored" data-anchor-id="card-roles">Card roles</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Card</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Manifest Dread</td>
<td>The enabler: two mana, one face down 2/2, one permanent card into the graveyard. Every copy is one step of fathomless descent plus a body that attacks for speed</td>
</tr>
<tr class="even">
<td>Hauntwoods Shrieker</td>
<td>Repeatable manifest dread on every attack, on a 3/3 for three. Its one green and a green also reveals and flips a face down creature for free, which is how the deck cheats expensive creatures onto the board without paying their cost</td>
</tr>
<tr class="odd">
<td>Paranormal Analyst</td>
<td>The value engine: whenever you manifest dread, the card that would have gone to the graveyard goes to your hand instead. She turns manifest dread into a two for one, at the price of a shallower graveyard</td>
</tr>
<tr class="even">
<td>Growing Dread</td>
<td>Instant speed manifest dread for two, plus a plus one counter on any permanent you turn face up. Flash means it is also a surprise blocker that leaves a permanent in the graveyard</td>
</tr>
<tr class="odd">
<td>Threats Around Every Corner</td>
<td>Four mana, manifest dread on entry, then a free basic land every time a face down permanent enters. With Hauntwoods Shrieker and Abhorrent Oculus online this is a one-sided ramp engine</td>
</tr>
<tr class="even">
<td>Abhorrent Oculus</td>
<td>The best creature in the deck and the most expensive question: a 5/5 flying for three that manifests dread on every opponent’s upkeep. The cost is exiling six cards from your graveyard, so cast it before the descent count matters or after Squirming Emergence has done its work</td>
</tr>
<tr class="odd">
<td>Souls of the Lost</td>
<td>The descent payoff that costs two: power equals the permanent cards in your graveyard, toughness one higher, and the additional cost of discarding a card or sacrificing a permanent is itself fuel for the next one</td>
</tr>
<tr class="even">
<td>Squirming Emergence</td>
<td>Free reanimation scaled to the graveyard: three mana returns any nonland permanent with mana value at most the permanent count, which in this deck means Hauntwoods Shrieker, Abhorrent Oculus, Racers’ Scoreboard or The Speed Demon</td>
</tr>
<tr class="odd">
<td>Sinkhole Surveyor</td>
<td>The speed clock: a 1/3 flier for two that loses you one life and endures one on every attack, meaning it becomes a plus one counter or a 1/1 Spirit token each combat</td>
</tr>
<tr class="even">
<td>Deep-Cavern Bat</td>
<td>Flying lifelink, plus it exiles a nonland card from the opponent’s hand while it lives. The lifelink pays for the Speed Demon’s end step and for the Surveyor’s attacks</td>
</tr>
<tr class="odd">
<td>Vnwxt, Verbose Host</td>
<td>Speed payoff and combo piece: no maximum hand size, and at max speed every card you draw becomes two cards</td>
</tr>
<tr class="even">
<td>Aether Syphon</td>
<td>The primary win condition: three mana artifact that taps for a card, and at max speed every draw mills each opponent two cards. With Vnwxt and The Speed Demon it is eight cards off the top of each opponent’s library per turn</td>
</tr>
<tr class="odd">
<td>The Speed Demon</td>
<td>Closer and engine: 5/5 flying trample for five, and at the end of each of your turns you draw X cards and lose X life, where X is your speed. At max speed that is four cards and four life a turn</td>
</tr>
<tr class="even">
<td>Endrider Catalyzer</td>
<td>Speed enabler and ramp: a 3/1 for two that taps for two red mana once you are at max speed, which pays for the second halves of the top end</td>
</tr>
<tr class="odd">
<td>Racers’ Scoreboard</td>
<td>Card flow and ramp: four mana, draw two then discard one on entry, and at max speed every spell costs one less. The discard is a graveyard permanent for fathomless descent</td>
</tr>
</tbody>
</table>
</section>
<section id="lands-as-engines" class="level2">
<h2 class="anchored" data-anchor-id="lands-as-engines">Lands as engines</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 70%">
</colgroup>
<thead>
<tr class="header">
<th>Land</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Avishkar Raceway (2)</td>
<td>The win condition land. It starts your engines, and at max speed three mana plus a tap and a discard draws a card. With Aether Syphon out each of those loots mills every opponent two cards, and the discarded card itself grows fathomless descent</td>
</tr>
<tr class="even">
<td>Amonkhet Raceway (1)</td>
<td>Starts engines, and at max speed it taps to give a creature haste. Casting Souls of the Lost as a six power creature and attacking with it the same turn is often the kill</td>
</tr>
<tr class="odd">
<td>Watery Grave, Breeding Pool, Overgrown Tomb, Blood Crypt, Steam Vents, Stomping Ground (9)</td>
<td>The four color fixing. All nine come in untapped if you pay two life, which the deck can afford because Deep-Cavern Bat gains it back</td>
</tr>
<tr class="even">
<td>Forest, Island, Swamp, Mountain (11)</td>
<td>Untapped basics, weighted to green and blue for the manifest dread half of the deck, with a single Mountain for Endrider Catalyzer</td>
</tr>
</tbody>
</table>
<p>Both Raceways produce only colorless mana, so they are the land slots that do not fix your colors: treat them as spells you can play for free, and lead on a dual or a basic instead.</p>
</section>
<section id="curve-and-mana" class="level2">
<h2 class="anchored" data-anchor-id="curve-and-mana">Curve and mana</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Mana value</th>
<th>Cards</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>22</td>
<td>Manifest Dread, Paranormal Analyst, Growing Dread, Souls of the Lost, Sinkhole Surveyor, Deep-Cavern Bat, Vnwxt, Endrider Catalyzer</td>
</tr>
<tr class="even">
<td>3</td>
<td>8</td>
<td>Hauntwoods Shrieker, Abhorrent Oculus, Aether Syphon, Squirming Emergence</td>
</tr>
<tr class="odd">
<td>4</td>
<td>4</td>
<td>Threats Around Every Corner, Racers’ Scoreboard</td>
</tr>
<tr class="even">
<td>5</td>
<td>2</td>
<td>The Speed Demon</td>
</tr>
</tbody>
</table>
<p>Average nonland mana value is 2.61 and there are no one mana spells at all: the deck wants its first two turns to be a land plus a creature or a Manifest Dread, and it never needs more than five mana to win. Twenty four lands plus Threats Around Every Corner’s land triggers make the fourth land drop very reliable, and everything above three mana is a card the deck is happy to draw late.</p>
</section>
</section>
<section id="gameplay-strategy" class="level1">
<h1>Gameplay strategy</h1>
<section id="early-game" class="level2">
<h2 class="anchored" data-anchor-id="early-game">Early game</h2>
<p>Lead with a dual land or a basic, not a Raceway, unless you have nothing else to do with the colorless mana. Turn two is Manifest Dread when you are setting up depth, Deep-Cavern Bat when you want the hand information and the lifelink, or Souls of the Lost once the graveyard already holds two or three permanents. Sinkhole Surveyor is the best turn two when you expect a race, because attacking with it every turn is how speed climbs to 4.</p>
<p>The first attack is what matters most: speed only rises on turns the opponent actually loses life. A 1/3 flier attacking into nothing is one point of damage and one point of speed. Do not hold back attacks to protect creatures you are willing to trade; the deck’s plan is to run the clock in both directions at once.</p>
</section>
<section id="mid-game" class="level2">
<h2 class="anchored" data-anchor-id="mid-game">Mid game</h2>
<p>Turns three to five are about stacking engines. Hauntwoods Shrieker turns every attack into another face down 2/2 and another permanent in the graveyard, which makes Threats Around Every Corner ramp a land on every combat and Aether Syphon’s milling start to matter. Growing Dread held up with flash is a blocker on demand that also deepens the graveyard, and Paranormal Analyst is the card that keeps the hand from running dry while the graveyard empties into the board.</p>
<p>The graveyard is a resource with two speeds: it grows with every manifest dread, and it shrinks with every Abhorrent Oculus and every Squirming Emergence. Spend it before you refill it. The usual sequence is manifest dread for several turns, cast Squirming Emergence to bring back the best permanent in the graveyard, then cast Abhorrent Oculus once the yard is deep enough to lose six cards and still keep three or four for the next Souls of the Lost.</p>
</section>
<section id="the-combo-turn" class="level2">
<h2 class="anchored" data-anchor-id="the-combo-turn">The combo turn</h2>
<p>Max speed arrives on the third turn that an opponent loses life, and the deck can usually turn that corner by turn four or five with one flier plus the Raceway lands’ start your engines. The turn itself is simple: attack with everything that can profitably attack, keep Aether Syphon and Vnwxt on the board, and let the draws do the work. At max speed the arithmetic is brutal: Vnwxt doubles each draw, Aether Syphon mills two per draw, and if The Speed Demon is out the end step draws four cards, which is eight cards milled off each opponent plus eight cards in your hand.</p>
<p>Racers’ Scoreboard’s max speed clause stacks with that turn: every spell you cast costs one less, so a hand of four cards often contains two spells and the mana to spare. Endrider Catalyzer’s max speed tap for two red mana is the other half, and it is the only red card in the deck that matters after turn two.</p>
</section>
<section id="the-second-win-condition" class="level2">
<h2 class="anchored" data-anchor-id="the-second-win-condition">The second win condition</h2>
<p>When the mill plan is interrupted or the opponent is gaining life, the deck still kills with its graveyard. Souls of the Lost is frequently a five or six power creature for two mana, and Hauntwoods Shrieker’s free flip ability plus Growing Dread’s plus one counter turns a nameless face down 2/2 into a real threat without paying for it. Squirming Emergence returning The Speed Demon for three mana ends games from an empty board, and Amonkhet Raceway’s max speed haste means the creature that comes back swings in the same turn it arrives.</p>
</section>
<section id="mulligan-guide" class="level2">
<h2 class="anchored" data-anchor-id="mulligan-guide">Mulligan guide</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Hand</th>
<th>Keep or mulligan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Two or three lands, a manifest dread card, one two mana creature</td>
<td>Keep. This is the whole deck in four cards</td>
</tr>
<tr class="even">
<td>Two lands, no green source, no manifest dread card</td>
<td>Mulligan. The engine needs green, and Paranormal Analyst and Vnwxt alone do not pressure anyone</td>
</tr>
<tr class="odd">
<td>Three Raceways or other colorless lands, one coloured source</td>
<td>Mulligan. Colorless lands cannot cast anything in the deck except the artifacts, and Racers’ Scoreboard is the only artifact worth four mana on turn four</td>
</tr>
<tr class="even">
<td>Five lands and two four drops</td>
<td>Mulligan against aggro, keep on the play against control. Twenty four lands means flood is real and the deck has no way to convert spare lands into cards except Squirming Emergence and Avishkar Raceway</td>
</tr>
</tbody>
</table>
</section>
<section id="key-interactions-and-edge-cases" class="level2">
<h2 class="anchored" data-anchor-id="key-interactions-and-edge-cases">Key interactions and edge cases</h2>
<p>Abhorrent Oculus exiles six cards from your graveyard as an additional cost. In a deck where Souls of the Lost and Squirming Emergence read that same graveyard, this is a real cost: cast it when the yard holds eight or more permanent cards, or after Squirming Emergence has already spent them for you.</p>
<p>Paranormal Analyst redirects the graveyard half of every manifest dread into your hand. That is a two for one every single time, and it is also the reason the descent count can stall: if you need a deep graveyard, do not lean on her, and if you need cards she is the best three drop in the deck.</p>
<p>Hauntwoods Shrieker’s one green and a green ability reveals a face down permanent and turns it face up for free if it is a creature card. That is the deck’s cost cheat: flip an expensive creature your manifest dread happened to hide, then put a plus one counter on it with Growing Dread.</p>
<p>Manifest dread is a choice, not a coin flip. You look at the top two cards: put the permanent you want as a 2/2 blocker (or the one you want to flip) onto the battlefield, and the other into the graveyard, where it counts for fathomless descent.</p>
<p>Souls of the Lost’s additional cost can be paid with a spare face down 2/2 rather than a card from hand, which is the cheapest way to make it a six power creature, and it also puts a creature card into the graveyard for the next copy.</p>
<p>Speed rises only once per turn, no matter how much life the opponent loses. One attacker is enough to keep the clock moving, but you must attack every turn or the deck loses a turn of max speed.</p>
<p>The Speed Demon’s end step costs you real life: at max speed it draws four and loses four. Deep-Cavern Bat’s lifelink and the opponent’s own damage output decide whether that is a clock or a suicide note, so hold the Demon until you are above ten life or the opponent is nearly dead.</p>
</section>
<section id="matchups" class="level2">
<h2 class="anchored" data-anchor-id="matchups">Matchups</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 62%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Opponent</th>
<th>Plan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aggro</td>
<td>Trade early with Sinkhole Surveyor and face down 2/2s, gain life with Deep-Cavern Bat, and win the race later with flying trample. Never tap out for Aether Syphon before turn five against a deck that can punish it</td>
</tr>
<tr class="even">
<td>Control</td>
<td>Paranormal Analyst and Vnwxt make every removal spell a bad trade, and Squirming Emergence rebuys whatever the opponent destroys. Bait the sweeper, then rebuild from the graveyard, which is exactly what the deck is good at</td>
</tr>
<tr class="odd">
<td>Midrange</td>
<td>Souls of the Lost outclasses anything fair on rate, and Hauntwoods Shrieker’s manifest engine goes wider than most midrange boards. Attack on the ground to grow speed, then mill out the top of their deck</td>
</tr>
<tr class="even">
<td>Ramp and combo</td>
<td>The mill plan does not need to race to a damage kill: Aether Syphon plus Vnwxt plus The Speed Demon takes sixteen cards off the top of the opponent’s library every turn, regardless of their life total</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="iterations" class="level1">
<h1>Iterations</h1>
<p>Three rounds of the viability battery, each fixing the weakest gate.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 33%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>Change</th>
<th>Metrics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v1</td>
<td>First pass: the full manifest dread suite, both descent payoffs, the speed package, 24 lands</td>
<td>sim 36.0, synergy 77.3, T4 0.621, lands 0.620</td>
</tr>
<tr class="even">
<td>v1 to v2</td>
<td>minus 2 Valgavoth’s Onslaught, minus 2 Twist Reality, minus 2 Under the Skin, minus 1 Unnerving Grasp, minus 1 Chupacabra Echo, plus 2 Abhorrent Oculus, plus 2 Sinkhole Surveyor, plus 2 Deep-Cavern Bat, plus 2 Racers’ Scoreboard (a seven mana X spell and three clunky sorceries became evasive attackers and card flow)</td>
<td>sim 36.0 to 45.7, synergy 77.3 to 77.0, T4 0.621 to 0.635, lands 0.620 to 0.625</td>
</tr>
<tr class="odd">
<td>v2 to v3</td>
<td>minus 1 Unnerving Grasp, minus 1 Squirming Emergence, plus 1 Sinkhole Surveyor, plus 1 Deep-Cavern Bat (trim the last do-nothing sorcery, add two more fliers that damage the opponent every turn)</td>
<td>sim 45.7 to 49.0, synergy 77.0 to 77.1, T4 0.635 to 0.651, lands 0.625 to 0.657</td>
</tr>
</tbody>
</table>
<p>The battery’s simulated win rate is the one gate the final list still misses (49.0 against a 52.0 threshold, with individual runs between 45 and 56), so the list is flagged on that metric. Every other gate passes with room: Standard legal, zero rotating cards, synergy 77.1 against 70, goldfish turn four consistency 0.651 against 0.55, and four lands by turn four 0.657 against 0.55.</p>
</section>
<section id="deck-list-arena-import" class="level1">
<h1>Deck list (Arena import)</h1>
<pre><code>Race the Reaper
Deck
4 Manifest Dread
3 Paranormal Analyst
2 Growing Dread
2 Threats Around Every Corner
1 Squirming Emergence
3 Souls of the Lost
3 Hauntwoods Shrieker
2 Abhorrent Oculus
3 Sinkhole Surveyor
3 Deep-Cavern Bat
2 Vnwxt, Verbose Host
2 Aether Syphon
2 The Speed Demon
2 Endrider Catalyzer
2 Racers' Scoreboard
2 Avishkar Raceway
1 Amonkhet Raceway
3 Watery Grave
2 Breeding Pool
2 Overgrown Tomb
1 Blood Crypt
1 Steam Vents
1 Stomping Ground
4 Forest
3 Island
3 Swamp
1 Mountain</code></pre>


</section>

</main> <!-- /main -->
<script data-goatcounter="https://th3pajay.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>From th3pajay — a new Standard deck guide every morning</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/th3pajay/mtga-decks">Source on GitHub</a></p>
</div>
  </div>
</footer>




</body></html>