<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-15">

<title>Eavesong – MTG Decks — Daily Standard Guides</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a8dd2cfac03084eab458e3b1c626e1f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MTG Decks — Daily Standard Guides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a>
  <ul class="collapse">
  <li><a href="#game-plan-phases" id="toc-game-plan-phases" class="nav-link" data-scroll-target="#game-plan-phases">Game plan phases</a></li>
  <li><a href="#card-roles" id="toc-card-roles" class="nav-link" data-scroll-target="#card-roles">Card roles</a></li>
  <li><a href="#lands-as-engines" id="toc-lands-as-engines" class="nav-link" data-scroll-target="#lands-as-engines">Lands as engines</a></li>
  <li><a href="#curve-and-mana" id="toc-curve-and-mana" class="nav-link" data-scroll-target="#curve-and-mana">Curve and mana</a></li>
  </ul></li>
  <li><a href="#gameplay-strategy" id="toc-gameplay-strategy" class="nav-link" data-scroll-target="#gameplay-strategy">Gameplay strategy</a>
  <ul class="collapse">
  <li><a href="#early-game" id="toc-early-game" class="nav-link" data-scroll-target="#early-game">Early game</a></li>
  <li><a href="#mid-game" id="toc-mid-game" class="nav-link" data-scroll-target="#mid-game">Mid game</a></li>
  <li><a href="#the-combo-turn" id="toc-the-combo-turn" class="nav-link" data-scroll-target="#the-combo-turn">The combo turn</a></li>
  <li><a href="#win-condition-2" id="toc-win-condition-2" class="nav-link" data-scroll-target="#win-condition-2">Win condition 2</a></li>
  <li><a href="#mulligan-guide" id="toc-mulligan-guide" class="nav-link" data-scroll-target="#mulligan-guide">Mulligan guide</a></li>
  <li><a href="#key-interactions-and-edge-cases" id="toc-key-interactions-and-edge-cases" class="nav-link" data-scroll-target="#key-interactions-and-edge-cases">Key interactions and edge cases</a></li>
  <li><a href="#matchups" id="toc-matchups" class="nav-link" data-scroll-target="#matchups">Matchups</a></li>
  </ul></li>
  <li><a href="#iterations" id="toc-iterations" class="nav-link" data-scroll-target="#iterations">Iterations</a></li>
  <li><a href="#deck-list-arena-import" id="toc-deck-list-arena-import" class="nav-link" data-scroll-target="#deck-list-arena-import">Deck list (Arena import)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Eavesong</h1>
<p class="subtitle lead">White / Blue / Black / Green (four colors) — legendary-Elf landfall engine with the Bard draw-and-token package, built on The Hobbit set</p>
  <div class="quarto-categories">
    <div class="quarto-category">hobbit</div>
    <div class="quarto-category">elves</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 15, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="at-a-glance" class="level1">
<h1>At a glance</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 61%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Format</td>
<td>Standard (MTGA)</td>
</tr>
<tr class="even">
<td>Colors</td>
<td>White / Blue / Black / Green (four colors)</td>
</tr>
<tr class="odd">
<td>Archetype</td>
<td>Synergy midrange-combo — Elf legends plus landfall, with a doubled-token finish</td>
</tr>
<tr class="even">
<td>Size</td>
<td>60 cards (36 spells and permanents, 24 lands, average mana value 3.36 across nonlands)</td>
</tr>
<tr class="odd">
<td>Signature mechanic</td>
<td>Landfall on legendary Elves, doubled by Bard, King of Dale</td>
</tr>
<tr class="even">
<td>Primary win</td>
<td>Mirkwood Pathmaker grows with every land, Thranduil’s Company and Elvenking’s Halls add counters, and Elvenking’s Harper makes the result unblockable</td>
</tr>
<tr class="odd">
<td>Secondary win</td>
<td>Thranduil, Sindarin Liege and Down in the Valley make 1/1 Elf tokens on landfall, Bard, King of Dale doubles every token made, and Bard’s Company turns the swarm into a real army</td>
</tr>
<tr class="even">
<td>Land win condition</td>
<td>Elvenking’s Halls, a green-blue land that sacrifices itself for two +1/+1 counters on an Elf</td>
</tr>
<tr class="odd">
<td>Measured performance</td>
<td>Sim 61.0 percent over three 500-game runs, turn-4 consistency 0.625, four-land probability by turn 4 of 0.632, synergy 70.6</td>
</tr>
</tbody>
</table>
</section>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>Eavesong is the Elf-legends build of The Hobbit set, and its engine is the one thing Elves and lands share in this set: landfall. Ten of the deck’s thirty-six nonland cards either trigger on a land entering or put extra lands onto the battlefield, and the two payoffs are both legendary Elves. Thranduil, Sindarin Liege gives the whole Elf team +1/+1 and makes a 1/1 green Elf token every time a land enters. Thranduil’s Company lets you play an extra land each turn and puts two +1/+1 counters on a creature on every landfall, with vigilance attached. Two creatures, one land per turn, and the board grows in three directions at once.</p>
<p>The second engine is mana. Wood Elves puts a Forest onto the battlefield, Woodland Weavemaster taps for one mana for each point of its power (and it grows whenever another Elf enters), and Thranduil’s Company adds a land drop. The deck reaches five and six mana early, which is where Thranduil, the Elvenking and Bard, King of Dale live.</p>
<p>Thranduil, the Elvenking is the top of the curve and the reason the deck is four colors. He draws two cards every time another legendary Elf enters — and there are six legendary Elves in the list. His first ability is the sharper one: he has all activated abilities of all Elf cards in your graveyard, so the unblockable activation from Elvenking’s Harper, the three counters from Guardian of the Halls and the mana ability from Woodland Weavemaster stay available to him after those creatures die. Elrond, Moon-Reader converts each of those activations into a card.</p>
<p>Bard, King of Dale closes the loop from the other side. Every draw after the first in a turn becomes two draws, and every token the deck creates is doubled. Down in the Valley chapter two turns every land into two 1/1 Elf tokens instead of one, Bard’s Company is a lord that recruits a Soldier on every attack, and Galion, Elvenking’s Butler turns whichever token you point it at into a 4/4.</p>
<p><strong>Note on the set:</strong> The Hobbit releases on Arena on 2026-08-14. Arena IDs are still empty for most of the set’s printings in the card database, so the import list below takes effect from that release date.</p>
</section>
<section id="approach" class="level1">
<h1>Approach</h1>
<section id="game-plan-phases" class="level2">
<h2 class="anchored" data-anchor-id="game-plan-phases">Game plan phases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>Turns</th>
<th>What the deck is doing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Open</td>
<td>1 to 2</td>
<td>Play a land every turn and land a two-drop. Woodland Weavemaster is the best turn two because it ramps from turn three onward; Guardian of the Halls and Elvenking’s Harper are the other two-drops and both later feed Thranduil, the Elvenking from the graveyard</td>
</tr>
<tr class="even">
<td>Build</td>
<td>3 to 4</td>
<td>Wood Elves accelerates, Thranduil, Sindarin Liege turns every land drop into a token, and Mirkwood Pathmaker arrives as a creature whose power equals the number of lands you control</td>
</tr>
<tr class="odd">
<td>Multiply</td>
<td>4 to 5</td>
<td>Thranduil’s Company doubles the land drops and puts +1/+1 counters on the team, Bard’s Company arrives as a lord, and Down in the Valley turns every land into a token</td>
</tr>
<tr class="even">
<td>Close</td>
<td>5 plus</td>
<td>Thranduil, the Elvenking refills the hand, Bard, King of Dale doubles draws and tokens, and the deck attacks wide with a doubled Elf army or tall with one unblockable land-sized Elf</td>
</tr>
</tbody>
</table>
</section>
<section id="card-roles" class="level2">
<h2 class="anchored" data-anchor-id="card-roles">Card roles</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 69%">
</colgroup>
<thead>
<tr class="header">
<th>Role</th>
<th>Cards</th>
<th>What the card actually does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Landfall payoffs</td>
<td>Thranduil, Sindarin Liege (3), Thranduil’s Company (2), Mirkwood Meditator (2)</td>
<td>Sindarin Liege gives other Elves +1/+1 and creates a 1/1 green Elf token on landfall. Thranduil’s Company lets you play an extra land while you control another Elf, and its landfall puts two +1/+1 counters on a creature and grants vigilance. Mirkwood Meditator becomes a 4/2 until end of turn on each landfall</td>
</tr>
<tr class="even">
<td>Mana engine</td>
<td>Wood Elves (3), Woodland Weavemaster (3), Down in the Valley (2)</td>
<td>Wood Elves searches a Forest onto the battlefield. Woodland Weavemaster taps for X mana of one color where X is its power. Down in the Valley chapter one searches a basic land to hand, and chapter two gives the Saga a landfall ability that makes a 1/1 green Elf token; chapters three and four give Elves +1/+0 and vigilance</td>
</tr>
<tr class="odd">
<td>Legendary-Elf engine</td>
<td>Thranduil, the Elvenking (2), Elrond, Moon-Reader (2)</td>
<td>Thranduil has every activated ability of every Elf card in your graveyard and draws two cards when another legendary Elf enters. Elrond draws a card whenever you activate an ability of a creature, once each turn</td>
</tr>
<tr class="even">
<td>Token doubling and draw</td>
<td>Bard, King of Dale (2), Bard the Bowman (2)</td>
<td>Bard, King of Dale doubles every draw after your first each turn and doubles every token you create. Bard the Bowman puts a +1/+1 counter on a creature and gives it lifelink whenever you draw your second card in a turn</td>
</tr>
<tr class="odd">
<td>Lord and recruit</td>
<td>Bard’s Company (2)</td>
<td>A 2/3 that can be cast as though it had flash while you control a Human, gives your other creatures +1/+1, and recruits on entry and on every attack — draw a card, discard a card, and if the discarded card is not a land, create a 1/1 white Human Soldier token</td>
</tr>
<tr class="even">
<td>Evasion and reach</td>
<td>Elvenking’s Harper (2), Key to the Side-Door (1), Guardian of the Halls (2), Galion, Elvenking’s Butler (2)</td>
<td>Harper’s {4}{U} activation makes a creature unblockable. Key to the Side-Door does the same for {2} and taps for it, and can discard a duplicate legendary to draw two. Guardian of the Halls is a 2/2 trampler that pays {5}{G}{G} for three counters. Galion sets another attacker’s base power and toughness to 4/4</td>
</tr>
<tr class="odd">
<td>Refuel and interaction</td>
<td>Cantankerous Keepers (1), Confusticate and Bebother (1)</td>
<td>Cantankerous Keepers has affinity for Elves, mills four cards and returns every Elf among them to hand. Confusticate and Bebother counters a spell unless they pay {4}, or draws two and discards one</td>
</tr>
</tbody>
</table>
</section>
<section id="lands-as-engines" class="level2">
<h2 class="anchored" data-anchor-id="lands-as-engines">Lands as engines</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Land</th>
<th>Count</th>
<th>Why it is in the deck</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Elvenking’s Halls</td>
<td>2</td>
<td>The win-condition land. It is a green-blue dual that enters tapped, and for {2}{G}{U} it sacrifices itself to put two +1/+1 counters on a target Elf — the cheapest permanent boost the deck has, and it lands on the same turn Mirkwood Pathmaker attacks</td>
</tr>
<tr class="even">
<td>Hedge Maze</td>
<td>3</td>
<td>Green-blue dual that enters tapped and surveils 1, which fills the graveyard for Thranduil, the Elvenking’s ability-stealing clause</td>
</tr>
<tr class="odd">
<td>Underground Mortuary</td>
<td>2</td>
<td>Black-green dual, tapped with surveil 1. One of only five black sources</td>
</tr>
<tr class="even">
<td>Opulent Palace</td>
<td>2</td>
<td>Three-color land that enters tapped and taps for black, green or blue — the reason a single land can cast Thranduil, the Elvenking</td>
</tr>
<tr class="odd">
<td>Temple Garden</td>
<td>2</td>
<td>Green-white shock land for the Bard package and Down in the Valley’s white-free base</td>
</tr>
<tr class="even">
<td>Hallowed Fountain</td>
<td>2</td>
<td>White-blue shock land. Bard’s Company, Bard the Bowman and Bard, King of Dale all want white and blue together</td>
</tr>
<tr class="odd">
<td>Lake-town</td>
<td>1</td>
<td>White-blue dual that can sacrifice itself for two +1/+1 counters on a Human, which is the same effect as Elvenking’s Halls aimed at the Bard creatures</td>
</tr>
<tr class="even">
<td>Forest, Island, Plains, Swamp</td>
<td>4 / 3 / 2 / 1</td>
<td>Basics. Black is a splash for exactly two cards, so a single Swamp plus the black-producing duals is enough</td>
</tr>
</tbody>
</table>
<p>Coloured sources: fifteen green, thirteen blue, seven white, five black, including the dual lands that produce two or three colours. Black exists only for Thranduil, the Elvenking, and white only for the three Bard cards plus the Lake-town activation, so the deck plays like a green-blue base with two splashes.</p>
</section>
<section id="curve-and-mana" class="level2">
<h2 class="anchored" data-anchor-id="curve-and-mana">Curve and mana</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Mana value</th>
<th>Count</th>
<th>Cards</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One</td>
<td>1</td>
<td>Key to the Side-Door</td>
</tr>
<tr class="even">
<td>Two</td>
<td>7</td>
<td>Woodland Weavemaster, Elvenking’s Harper, Guardian of the Halls</td>
</tr>
<tr class="odd">
<td>Three</td>
<td>14</td>
<td>Elrond, Moon-Reader, Wood Elves, Mirkwood Pathmaker, Mirkwood Meditator, Down in the Valley, Bard the Bowman, Confusticate and Bebother</td>
</tr>
<tr class="even">
<td>Four</td>
<td>9</td>
<td>Galion, Elvenking’s Butler, Thranduil’s Company, Bard’s Company, Thranduil, Sindarin Liege</td>
</tr>
<tr class="odd">
<td>Five</td>
<td>2</td>
<td>Thranduil, the Elvenking</td>
</tr>
<tr class="even">
<td>Six</td>
<td>3</td>
<td>Bard, King of Dale, Cantankerous Keepers</td>
</tr>
</tbody>
</table>
<p>Six of the fourteen three-cost cards and both five-drops are castable earlier than the table suggests: Cantankerous Keepers has affinity for Elves and routinely costs four or five, Woodland Weavemaster taps for two or three mana in the mid game, and Wood Elves plus Thranduil’s Company mean the deck often has six or seven lands by turn five. Four-land probability by turn four is 0.632 and turn-four consistency is 0.625, both above the 0.55 threshold the build is held to.</p>
</section>
</section>
<section id="gameplay-strategy" class="level1">
<h1>Gameplay strategy</h1>
<section id="early-game" class="level2">
<h2 class="anchored" data-anchor-id="early-game">Early game</h2>
<p>Turns one and two are about lands and one cheap body. Woodland Weavemaster is the priority two-drop: it blocks, it grows whenever another Elf enters, and once its power is two or three it taps for that much mana, which is what pays for the four-drop half of the deck without slowing the land count. Guardian of the Halls is the aggressive option at the same cost, and Elvenking’s Harper is the one that matters later, because its unblockable activation is an ability Thranduil, the Elvenking inherits from the graveyard.</p>
<p>Never trade a land drop for a spell in the first three turns. Every land is a Thranduil, Sindarin Liege token, a Thranduil’s Company counter, a Mirkwood Pathmaker point of power, and a Mirkwood Meditator trigger, so the deck’s mana base is also its threat base.</p>
</section>
<section id="mid-game" class="level2">
<h2 class="anchored" data-anchor-id="mid-game">Mid game</h2>
<p>Thranduil, Sindarin Liege on turn four is the pivot. From that point you land tokens on every land, and the whole Elf team is one point bigger, which changes every combat. Thranduil’s Company on top of it means two lands per turn: one land makes a token, and the Company’s landfall trigger adds two +1/+1 counters with vigilance.</p>
<p>Mirkwood Pathmaker is the card opponents consistently misjudge. It is a three-drop whose power is your land count — usually 5/5 or 6/6 by turn five in this deck — and Galion, Elvenking’s Butler can point at any other attacker and set its base power and toughness to 4/4, which turns a 1/1 Elf token into a real threat. Down in the Valley should be played before the big attack turn: chapter two turns each land into a token, and chapters three and four add +1/+0 and vigilance across the team.</p>
</section>
<section id="the-combo-turn" class="level2">
<h2 class="anchored" data-anchor-id="the-combo-turn">The combo turn</h2>
<p>The deck’s engine turn needs Thranduil’s Company or Thranduil, Sindarin Liege, a handful of lands, and one evasion source.</p>
<ol type="1">
<li>Land for the turn. Thranduil, Sindarin Liege makes a 1/1 Elf token, and Thranduil’s Company’s landfall puts two +1/+1 counters on Mirkwood Pathmaker and grants it vigilance.</li>
<li>Play a second land if Thranduil’s Company or another Elf is out. Same two triggers again: another token, another two counters.</li>
<li>Cast Down in the Valley if it is not already on the board. Chapter two turns your next land into two Elf tokens, and with Bard, King of Dale those tokens are doubled again.</li>
<li>Activate Elvenking’s Halls for {2}{G}{U}, sacrificing it, to put two more +1/+1 counters on the attacking Elf.</li>
<li>Activate Elvenking’s Harper for {4}{U} to make that creature unblockable. Elrond, Moon-Reader draws you a card for the activation, and Bard the Bowman puts a counter and lifelink on a creature for that second draw.</li>
<li>Attack with everything. Galion, Elvenking’s Butler can upgrade whichever token is smallest, and Bard’s Company gives the team +1/+1 before damage.</li>
</ol>
<p>Two lands and one evasion activation is typically eight or more points of unblockable damage on a board that was two creatures wide one turn earlier. Order matters: make the land drops and the Halls activation before the unblockable activation, because both can change which creature should carry the attack.</p>
</section>
<section id="win-condition-2" class="level2">
<h2 class="anchored" data-anchor-id="win-condition-2">Win condition 2</h2>
<p>The second win does not need Mirkwood Pathmaker at all. Thranduil, Sindarin Liege and Down in the Valley create Elf tokens on landfall, Bard, King of Dale doubles each creation, Bard’s Company recruits a Human Soldier on every attack and attack trigger, and Galion, Elvenking’s Butler turns the largest token into a 4/4 attacker each combat. Against a deck that answers one big creature, the wide plan is the better one; against a deck with many small blockers, the tall Pathmaker plan is.</p>
<p>Bard, King of Dale is worth protecting with Confusticate and Bebother: while it is on the board every draw spell in the deck is worth double and every token the deck makes arrives twice. Down in the Valley’s chapters three and four giving the team vigilance is what makes the alpha strike safe, since the Elf tokens can stay back to block on the following turn.</p>
</section>
<section id="mulligan-guide" class="level2">
<h2 class="anchored" data-anchor-id="mulligan-guide">Mulligan guide</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 57%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Hand shape</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Three lands, Woodland Weavemaster and any three-drop</td>
<td>Keep. This is the deck’s ideal opening</td>
</tr>
<tr class="even">
<td>Two lands, Wood Elves and Thranduil, Sindarin Liege</td>
<td>Keep. Wood Elves finds the third land and the Liege converts every later land into a token</td>
</tr>
<tr class="odd">
<td>One land with a four-drop and no two-drop</td>
<td>Mulligan. The deck needs three lands before its payoffs function</td>
</tr>
<tr class="even">
<td>Four lands, Thranduil’s Company and a landfall three-drop</td>
<td>Keep. Thranduil’s Company is the best card in the deck with four lands in hand</td>
</tr>
<tr class="odd">
<td>Five lands and both Bards but no Elf</td>
<td>Mulligan. The Bard package doubles the Elf engine; it does not replace it</td>
</tr>
<tr class="even">
<td>Two lands with a green source and one Swamp plus Thranduil, the Elvenking</td>
<td>Keep. Black is a one-card splash, and a single Swamp plus Opulent Palace or Underground Mortuary is enough</td>
</tr>
</tbody>
</table>
</section>
<section id="key-interactions-and-edge-cases" class="level2">
<h2 class="anchored" data-anchor-id="key-interactions-and-edge-cases">Key interactions and edge cases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 53%">
</colgroup>
<thead>
<tr class="header">
<th>Interaction</th>
<th>Ruling detail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Thranduil, the Elvenking and the graveyard</td>
<td>His ability grants him all activated abilities of all Elf cards in your graveyard, so an Elvenking’s Harper that died still makes his unblockable activation available, and a Woodland Weavemaster in the graveyard gives him its mana ability</td>
</tr>
<tr class="even">
<td>Elrond, Moon-Reader triggers once per turn</td>
<td>Any activation of an ability of a creature draws a card, but only the first activation each turn. Pair it with the unblockable activation, not with mana abilities you would rather activate twice</td>
</tr>
<tr class="odd">
<td>Landfall needs a land, not a token</td>
<td>Only a land entering triggers landfall. Ramp that puts a land onto the battlefield (Wood Elves, Down in the Valley chapter one) does trigger it, and Thranduil’s Company’s extra land drop is a second trigger on the same turn</td>
</tr>
<tr class="even">
<td>Bard, King of Dale doubles draws</td>
<td>Every draw after the first in each of your draw steps becomes two draws, so a single recruited card from Bard’s Company becomes two cards and immediately triggers Bard the Bowman’s second-draw ability</td>
</tr>
<tr class="odd">
<td>Bard, King of Dale doubles tokens</td>
<td>Thranduil, Sindarin Liege’s 1/1 Elf token becomes two, Down in the Valley’s tokens become two each, and Bard’s Company’s Human Soldier becomes two. This is the entire wide plan, so the Bard is a removal magnet</td>
</tr>
<tr class="even">
<td>Recruit and the discard</td>
<td>Recruit draws a card and then discards one; if the discarded card is a nonland, you create a 1/1 white Human Soldier token. Discarding a spare land is often correct, and it feeds Thranduil, the Elvenking’s graveyard clause</td>
</tr>
<tr class="odd">
<td>Galion sets base power and toughness</td>
<td>The change is to base values until end of turn, so it overwrites Mirkwood Pathmaker’s land-based strength if you point Galion at the Pathmaker. Point it at a token instead</td>
</tr>
<tr class="even">
<td>Elvenking’s Halls and Lake-town are one-shot</td>
<td>Both lands sacrifice themselves for two +1/+1 counters, and only as a sorcery. Tap them for mana first, then sacrifice in the second main phase</td>
</tr>
<tr class="odd">
<td>Key to the Side-Door</td>
<td>The unblockable activation costs {2} and taps the artifact, so it is the cheap evasion for the turn you need it; the second ability needs a legendary card in hand with the same name as a legendary permanent you control, which happens after a second Thranduil, the Elvenking or Bard, King of Dale is drawn</td>
</tr>
</tbody>
</table>
</section>
<section id="matchups" class="level2">
<h2 class="anchored" data-anchor-id="matchups">Matchups</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 62%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Opponent</th>
<th>Plan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aggro, including fliers and lifegain counters</td>
<td>Guardian of the Halls blocks and grows, Mirkwood Meditator switches to a 4/2 on every landfall, and Bard the Bowman’s lifelink counter offsets their clock. Race with the wide token plan and keep Confusticate and Bebother for their pump spell</td>
</tr>
<tr class="even">
<td>Midrange</td>
<td>The strong matchup. Thranduil, the Elvenking outdraws them, Thranduil’s Company’s landfall counters outgrow their blockers, and Galion, Elvenking’s Butler makes any token a 4/4 that trades up</td>
</tr>
<tr class="odd">
<td>Control</td>
<td>The weak matchup. Board wipes take the tokens with them, so commit Thranduil’s Company plus one token-maker and hold the second. Cantankerous Keepers returns the Elf cards that a wipe puts into the graveyard, and Thranduil, the Elvenking’s ability-stealing clause means the Elves that died still contribute</td>
</tr>
<tr class="even">
<td>Combo</td>
<td>The deck’s clock is turn five or six, so interaction is minimal: Confusticate and Bebother is the only counter and Key to the Side-Door’s unblockable is the only way to push damage through a stalled board. Land Thranduil, Sindarin Liege early and attack every turn to force them to block instead of assembling</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="iterations" class="level1">
<h1>Iterations</h1>
<p>The list was run through the viability battery twice before publishing. Round one missed the cohesion gate by half a point, so round two replaced the cards that were not feeding the engine with the highest-affinity Elf and Bard slots.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 40%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>What changed</th>
<th>Gate results</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v1</td>
<td>Baseline list: Elf legends core plus landfall creatures (Elven Raft-Steerer, Silvan Reveler, Boughside Wanderers), with Attercop and Gigantic Big Bear as curve fillers</td>
<td>synergy 69.49 (FAIL vs 70), sim 58.3 percent, turn-4 0.595, four lands 0.584</td>
</tr>
<tr class="even">
<td>v2</td>
<td>-2 Attercop, -2 Boughside Wanderers, -2 Gigantic Big Bear, -2 Silvan Reveler, -2 Elven Raft-Steerer, -1 Mirkwood Pathmaker, -1 Thranduil’s Company, -1 Cantankerous Keepers; +3 Thranduil, Sindarin Liege, +2 Bard’s Company, +2 Bard, King of Dale, +2 Bard the Bowman, +1 Guardian of the Halls, +1 Key to the Side-Door, +1 Confusticate and Bebother; manabase -3 Forest, -2 Swamp, -1 Opulent Palace, +2 Temple Garden, +2 Hallowed Fountain, +1 Lake-town, +2 Plains (why: Thranduil, Sindarin Liege is the highest-affinity partner for Thranduil, the Elvenking, and the Bard package is the highest-affinity unlocked cluster in the set, while the Spider, Bear and off-theme Elf slots were not feeding the landfall engine)</td>
<td>synergy 69.49 to 70.57, sim 58.3 to 61.0 percent, turn-4 0.595 to 0.625, four lands 0.584 to 0.632</td>
</tr>
</tbody>
</table>
<p>All gates pass on the final list: size 60 with no missing cards, Standard legal, zero rotating cards, sim 61.0 percent, synergy 70.6, turn-4 consistency 0.625, four-land probability 0.632.</p>
</section>
<section id="deck-list-arena-import" class="level1">
<h1>Deck list (Arena import)</h1>
<pre class="text"><code>Eavesong
Deck
2 Thranduil, the Elvenking
2 Elrond, Moon-Reader
3 Thranduil, Sindarin Liege
3 Wood Elves
3 Woodland Weavemaster
2 Mirkwood Pathmaker
2 Galion, Elvenking's Butler
2 Thranduil's Company
2 Down in the Valley
1 Cantankerous Keepers
2 Bard's Company
2 Bard, King of Dale
2 Bard the Bowman
2 Elvenking's Harper
2 Guardian of the Halls
2 Mirkwood Meditator
1 Confusticate and Bebother
1 Key to the Side-Door
2 Elvenking's Halls
3 Hedge Maze
2 Underground Mortuary
2 Opulent Palace
2 Temple Garden
2 Hallowed Fountain
1 Lake-town
4 Forest
3 Island
2 Plains
1 Swamp</code></pre>


</section>

</main> <!-- /main -->
<script data-goatcounter="https://th3pajay.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>From th3pajay — a new Standard deck guide every morning</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/th3pajay/mtga-decks">Source on GitHub</a></p>
</div>
  </div>
</footer>




</body></html>