<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-13">

<title>Wilderland Howl – MTG Decks — Daily Standard Guides</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a8dd2cfac03084eab458e3b1c626e1f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MTG Decks — Daily Standard Guides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a>
  <ul class="collapse">
  <li><a href="#game-plan-phases" id="toc-game-plan-phases" class="nav-link" data-scroll-target="#game-plan-phases">Game plan phases</a></li>
  <li><a href="#card-roles" id="toc-card-roles" class="nav-link" data-scroll-target="#card-roles">Card roles</a></li>
  <li><a href="#lands-as-engines" id="toc-lands-as-engines" class="nav-link" data-scroll-target="#lands-as-engines">Lands as engines</a></li>
  <li><a href="#curve-and-mana" id="toc-curve-and-mana" class="nav-link" data-scroll-target="#curve-and-mana">Curve and mana</a></li>
  </ul></li>
  <li><a href="#gameplay-strategy" id="toc-gameplay-strategy" class="nav-link" data-scroll-target="#gameplay-strategy">Gameplay strategy</a>
  <ul class="collapse">
  <li><a href="#early-game" id="toc-early-game" class="nav-link" data-scroll-target="#early-game">Early game</a></li>
  <li><a href="#mid-game" id="toc-mid-game" class="nav-link" data-scroll-target="#mid-game">Mid game</a></li>
  <li><a href="#the-combo-turn" id="toc-the-combo-turn" class="nav-link" data-scroll-target="#the-combo-turn">The combo turn</a></li>
  <li><a href="#win-condition-2" id="toc-win-condition-2" class="nav-link" data-scroll-target="#win-condition-2">Win condition 2</a></li>
  <li><a href="#mulligan-guide" id="toc-mulligan-guide" class="nav-link" data-scroll-target="#mulligan-guide">Mulligan guide</a></li>
  <li><a href="#key-interactions-and-edge-cases" id="toc-key-interactions-and-edge-cases" class="nav-link" data-scroll-target="#key-interactions-and-edge-cases">Key interactions and edge cases</a></li>
  <li><a href="#matchups" id="toc-matchups" class="nav-link" data-scroll-target="#matchups">Matchups</a></li>
  </ul></li>
  <li><a href="#iterations" id="toc-iterations" class="nav-link" data-scroll-target="#iterations">Iterations</a></li>
  <li><a href="#deck-list-arena-import" id="toc-deck-list-arena-import" class="nav-link" data-scroll-target="#deck-list-arena-import">Deck list (Arena import)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Wilderland Howl</h1>
<p class="subtitle lead">Golgari core with a red splash (Black / Green / Red) — Wilderlands Bears x the ferocious Warg pack, built on The Hobbit set</p>
  <div class="quarto-categories">
    <div class="quarto-category">hobbit</div>
    <div class="quarto-category">bears</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 13, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="at-a-glance" class="level1">
<h1>At a glance</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 61%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Format</td>
<td>Standard (MTGA)</td>
</tr>
<tr class="even">
<td>Colors</td>
<td>Black / Green with a red removal splash (three colors)</td>
</tr>
<tr class="odd">
<td>Archetype</td>
<td>Synergy midrange — Bear payoffs with a ferocious Wolf engine</td>
</tr>
<tr class="even">
<td>Size</td>
<td>60 cards (36 spells and permanents, 24 lands, average mana value 3.03)</td>
</tr>
<tr class="odd">
<td>Signature mechanic</td>
<td>Ferocious (power four or greater) plus Beorn the Fierce’s Bear anthem</td>
</tr>
<tr class="even">
<td>Primary win</td>
<td>Beorn the Fierce plus Bear tokens: every land drop makes a 2/2 Bear that Beorn turns into a 4/4 trampler</td>
</tr>
<tr class="odd">
<td>Secondary win</td>
<td>One counter-stacked Wolf or Bear pushed through an unstoppable Rogue’s Passage</td>
</tr>
<tr class="even">
<td>Land win condition</td>
<td>Mirkwood, repeated two-counter activations on a Bear, Spider or Wolf</td>
</tr>
<tr class="odd">
<td>Measured performance</td>
<td>Sim 62.3 percent over three 500-game runs, turn-4 consistency 0.634, four-land probability by turn 4 of 0.624, cohesion 72.5</td>
</tr>
</tbody>
</table>
</section>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>Wilderland Howl is a black-green creature deck with a red removal splash, and it is built on two interlocking Wilderlands mechanics. The first is ferocious. Wargling, Ravening Warg, Nighthowl Pursuer, Wilderland Scrounger and The Chief Warg all switch on the moment you control a creature with power four or greater, and this deck has an unusually easy time meeting that condition: Ordinary Bear is a four-power four-drop, Large Bear is a 5/5 with haste, and Beorn the Fierce is a 6/6 that also hands out a trample counter. A Wargling attack then gives the whole team trample, a Scrounger attack puts a +1/+1 counter on every creature, and The Chief Warg draws a card.</p>
<p>The second is the Bear payoff. Dancing from Dark to Dawn makes a 2/2 green Bear token on every land that enters, and Beorn the Fierce gives other Bears +2/+2, so the same token is a 4/4 trampler. Beorn’s combat trigger turns any creature you control into a Bear in addition to its other types, which means the Warg pack itself starts collecting the anthem. With three or more Bears, Beorn draws two cards at the start of combat, and the deck stops running out of gas.</p>
<p>The deck attacks from two directions and neither line depends on the other. The wide line is Dancing from Dark to Dawn plus Beorn the Fierce: play lands, make Bears, make them bigger, attack with trample. The tall line is counters. Dancing from Dark to Dawn puts counters equal to the mana value of every creature spell you cast, Mirkwood sacrifices itself for two more counters on a Bear or Wolf, and Quarrel and Pinecone Strike clear the blockers. Once one creature is large enough, Rogue’s Passage makes it unblockable and the game ends in one or two attacks.</p>
<p><strong>Note on the set:</strong> The Hobbit set lands on Arena 2026-08-14; Arena IDs are still empty for many of these printings in the card database, so the list below imports by card name from that date.</p>
</section>
<section id="approach" class="level1">
<h1>Approach</h1>
<section id="game-plan-phases" class="level2">
<h2 class="anchored" data-anchor-id="game-plan-phases">Game plan phases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>Turns</th>
<th>What the deck is doing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Open</td>
<td>1 to 2</td>
<td>Land a two-drop that attacks or trades: Wargling and Ravening Warg are both 2/2s, Ravening Warg has deathtouch. Thrór’s Map or Troop of Ponies fixes a colour and finds the fourth land</td>
</tr>
<tr class="even">
<td>Turn on ferocious</td>
<td>3 to 4</td>
<td>Ordinary Bear is the switch: four power for four mana, and from that point every ferocious trigger on the board is live. Chief Warg’s Company starts making a 2/2 Wolf every upkeep</td>
</tr>
<tr class="odd">
<td>Pivot</td>
<td>5</td>
<td>Beorn the Fierce or Dancing from Dark to Dawn. Beorn makes the Wolves into Bears and the Bears into 4/4s; Dancing turns every later land into a Bear token</td>
</tr>
<tr class="even">
<td>Close</td>
<td>6 plus</td>
<td>Attack with trample behind Wargling or Wilderland Scrounger, sacrifice Mirkwood for counters, and finish with Rogue’s Passage on the largest body</td>
</tr>
</tbody>
</table>
</section>
<section id="card-roles" class="level2">
<h2 class="anchored" data-anchor-id="card-roles">Card roles</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 69%">
</colgroup>
<thead>
<tr class="header">
<th>Role</th>
<th>Cards</th>
<th>What the card actually does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ferocious engine</td>
<td>Wargling (4), Ravening Warg (4), Nighthowl Pursuer (2), Wilderland Scrounger (2), The Chief Warg (1)</td>
<td>Wargling gives the team trample when it attacks with power four or greater on the board. Scrounger puts a +1/+1 counter on each creature you control on the same condition. Ravening Warg gains you 2 life, Nighthowl Pursuer grows to 3/3, and The Chief Warg draws a card</td>
</tr>
<tr class="even">
<td>Bear payoffs</td>
<td>Beorn the Fierce (2), Ordinary Bear (3), Little Bear (3), Large Bear (2)</td>
<td>Beorn is a 6/6 trampler that gives other Bears +2/+2, hands out a trample counter, and draws two cards with three or more Bears. Ordinary Bear is the four-power switch. Little Bear flashes in and untaps a Bear with a counter. Large Bear arrives as a hasty 5/5 with reach and trample</td>
</tr>
<tr class="odd">
<td>Token engines</td>
<td>Dancing from Dark to Dawn (2), Chief Warg’s Company (2), Head of the Hunt (1)</td>
<td>Dancing makes a 2/2 Bear on every landfall and puts counters equal to a creature spell’s mana value on a creature you control. Chief Warg’s Company makes a 2/2 Wolf every upkeep. Head of the Hunt flashes in and converts opposing creature deaths into 2/2 Wolf tokens</td>
</tr>
<tr class="even">
<td>Interaction</td>
<td>Quarrel (2), Pinecone Strike (2)</td>
<td>Quarrel makes your largest creature fight, which is usually a one-sided exchange once a Bear has counters. Pinecone Strike deals three damage to a creature and can also blow up artifact tokens</td>
</tr>
<tr class="odd">
<td>Mana and selection</td>
<td>Thrór’s Map (2), Troop of Ponies (2)</td>
<td>Map finds a basic land on entry and loots thereafter. Troop of Ponies blocks, then trades itself for two basic lands and a guaranteed fourth land drop</td>
</tr>
</tbody>
</table>
</section>
<section id="lands-as-engines" class="level2">
<h2 class="anchored" data-anchor-id="lands-as-engines">Lands as engines</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Land</th>
<th>Count</th>
<th>Why it is in the deck</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mirkwood</td>
<td>3</td>
<td>The win-condition land. It is a black and green dual that enters tapped, and for two mana of each colour it sacrifices itself to put two +1/+1 counters on target Bear, Spider or Wolf. Two counters turn a 2/2 Wolf token into a 4/4 threat, push ordinary bodies over the ferocious threshold, and make Beorn an 8/8 trampler</td>
</tr>
<tr class="even">
<td>Rogue’s Passage</td>
<td>1</td>
<td>The finisher land. Four mana makes any creature unblockable for the turn; combined with a counter-stacked Bear or a 6/6 trampling Beorn it is a two-turn clock through a stalled board</td>
</tr>
<tr class="odd">
<td>Forest</td>
<td>8</td>
<td>Primary green source, and the target for Troop of Ponies and Thrór’s Map</td>
</tr>
<tr class="even">
<td>Swamp</td>
<td>7</td>
<td>Primary black source. Black carries the deathtouch bodies, Head of the Hunt and the two Chief Warg cards</td>
</tr>
<tr class="odd">
<td>Mountain</td>
<td>5</td>
<td>Red for Pinecone Strike, and a fifth untapped land type so the deck does not stall on double-black or double-green</td>
</tr>
</tbody>
</table>
<p>Coloured sources: eleven green, ten black, five red. The red count is deliberately low because only Pinecone Strike needs it; the double-green cards (Beorn the Fierce, Dancing from Dark to Dawn) and the single double-black card (Head of the Hunt) both sit comfortably behind their colours.</p>
</section>
<section id="curve-and-mana" class="level2">
<h2 class="anchored" data-anchor-id="curve-and-mana">Curve and mana</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Mana value</th>
<th>Count</th>
<th>Cards</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One</td>
<td>2</td>
<td>Nighthowl Pursuer</td>
</tr>
<tr class="even">
<td>Two</td>
<td>16</td>
<td>Wargling, Ravening Warg, Thrór’s Map, Troop of Ponies, Quarrel, Pinecone Strike</td>
</tr>
<tr class="odd">
<td>Three</td>
<td>5</td>
<td>Little Bear, Chief Warg’s Company</td>
</tr>
<tr class="even">
<td>Four</td>
<td>5</td>
<td>Ordinary Bear, Head of the Hunt, The Chief Warg</td>
</tr>
<tr class="odd">
<td>Five</td>
<td>8</td>
<td>Large Bear, Beorn the Fierce, Wilderland Scrounger, Dancing from Dark to Dawn</td>
</tr>
</tbody>
</table>
<p>The deck wants four lands and is happy at five. Four-land probability by turn four is 0.624 and turn-four consistency is 0.634, both above the 0.55 threshold the build is held to. Twenty-four lands back a curve that peaks at five, and the two land-finding artifacts effectively add two more sources.</p>
</section>
</section>
<section id="gameplay-strategy" class="level1">
<h1>Gameplay strategy</h1>
<section id="early-game" class="level2">
<h2 class="anchored" data-anchor-id="early-game">Early game</h2>
<p>Turns one and two are about bodies that matter later. Wargling is the best turn-two play: it is a 2/2 that becomes a trample anthem the moment anything with four power is on the board. Ravening Warg trades with anything thanks to deathtouch and gains you 2 life on every attack once ferocious is live, which is the deck’s cheapest way to survive an aggressive start. Thrór’s Map on turn two is never wrong when the hand is short of lands, and Troop of Ponies should be held until it can be sacrificed in a turn where the land drop matters.</p>
<p>Do not panic about the tapped Mirkwood. Losing one turn of mana is worth a land that later adds two permanent counters to the creature of your choice.</p>
</section>
<section id="mid-game" class="level2">
<h2 class="anchored" data-anchor-id="mid-game">Mid game</h2>
<p>Turns three to five are where the deck takes over. Ordinary Bear is the pivot card at four mana because it turns on every ferocious trigger in the deck by itself. From that point Wargling attacks give the whole team trample, Wilderland Scrounger attacks put a +1/+1 counter on each creature you control, and The Chief Warg draws a card every attack.</p>
<p>Chief Warg’s Company needs two other Wolves to attack, which the deck has no trouble supplying: Wargling, Ravening Warg, Nighthowl Pursuer, Wilderland Scrounger and the Wolf tokens it makes itself all count. Once it can attack it is a 5/3 trampler that also leaves a 2/2 Wolf behind every upkeep, and those tokens are the raw material for Beorn’s anthem and Mirkwood’s counters.</p>
</section>
<section id="the-combo-turn" class="level2">
<h2 class="anchored" data-anchor-id="the-combo-turn">The combo turn</h2>
<p>The engine turn is Dancing from Dark to Dawn, then Beorn the Fierce, then a land drop:</p>
<ol type="1">
<li>Cast Dancing from Dark to Dawn. Every creature spell from now on puts counters equal to its mana value on a creature you control, and every land that enters makes a 2/2 green Bear token.</li>
<li>Cast Beorn the Fierce. His own trigger puts five counters on the best creature you have, and from now on all other Bears get +2/+2, so each Bear token is a 4/4.</li>
<li>Play a land. Landfall makes a Bear token, which Beorn immediately turns into a 4/4. If you have three or more Bears, Beorn’s combat trigger draws you two cards.</li>
<li>Attack. Wargling gives the team trample, Wilderland Scrounger adds a +1/+1 counter to everything, and Beorn’s trample counter on a Wolf converts that Wolf into a Bear for the anthem.</li>
</ol>
<p>Order matters: cast Beorn before the turn’s land drop if you can, so the Bear token arrives with the anthem already online.</p>
</section>
<section id="win-condition-2" class="level2">
<h2 class="anchored" data-anchor-id="win-condition-2">Win condition 2</h2>
<p>The second win is the counters line, and it is the plan when the ground is stalled. Every creature spell pumps a target for its mana value, Mirkwood sacrifices for two more counters, Little Bear untaps a Bear and adds a counter, and Quarrel trades the largest body for their best blocker. Once a single creature is at seven or more power, Rogue’s Passage makes it unblockable for four mana and it ends the game on its own — Beorn’s own trample usually makes the second Rogue’s Passage activation lethal.</p>
<p>Note the ordering detail on Mirkwood: it sacrifices itself as a sorcery, so activate it after the land has produced its mana for the turn.</p>
</section>
<section id="mulligan-guide" class="level2">
<h2 class="anchored" data-anchor-id="mulligan-guide">Mulligan guide</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 57%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Hand shape</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Two or three lands with Wargling and Ravening Warg</td>
<td>Keep. Two land types plus early pressure is exactly the shape the deck wants</td>
</tr>
<tr class="even">
<td>Land-light hand with Thrór’s Map and a two-drop</td>
<td>Keep. Map or Troop of Ponies finds the fourth land</td>
</tr>
<tr class="odd">
<td>Five lands and no creature</td>
<td>Mulligan. The deck needs a body on turn two</td>
</tr>
<tr class="even">
<td>One land, Beorn the Fierce and Dancing from Dark to Dawn</td>
<td>Mulligan. Both five-drops need four lands in play before they matter</td>
</tr>
<tr class="odd">
<td>Three lands with Ordinary Bear and Chief Warg’s Company</td>
<td>Keep. This is the ferocious switch plus a token engine</td>
</tr>
</tbody>
</table>
</section>
<section id="key-interactions-and-edge-cases" class="level2">
<h2 class="anchored" data-anchor-id="key-interactions-and-edge-cases">Key interactions and edge cases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 53%">
</colgroup>
<thead>
<tr class="header">
<th>Interaction</th>
<th>Ruling detail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ferocious checks power four or greater</td>
<td>All five ferocious cards check for any creature you control with power four or greater when the ability triggers. Ordinary Bear (4/5), Beorn the Fierce (6/6) and Large Bear (5/5) get there on their own; a Bear token with counters or a Wolf under Beorn does too</td>
</tr>
<tr class="even">
<td>Beorn’s combat trigger makes new Bears</td>
<td>The trample counter goes on up to one target creature you control and that creature becomes a Bear in addition to its other types. Point it at a Wargling or a Wolf token and the anthem begins applying to it, and it counts toward the three-Bear condition for the draw</td>
</tr>
<tr class="odd">
<td>Chief Warg’s Company needs two other Wolves</td>
<td>It is a Wolf itself, but the attack restriction counts only other Wolves. Two of Wargling, Ravening Warg, Nighthowl Pursuer, Wilderland Scrounger, The Chief Warg or a Wolf token satisfy it</td>
</tr>
<tr class="even">
<td>Dancing from Dark to Dawn counts creature spells only</td>
<td>The counter trigger fires on casting a creature spell, so the activation uses the mana value of what you cast. Landfall tokens do not trigger it, but they do trigger on the land itself</td>
</tr>
<tr class="odd">
<td>Mirkwood is a sorcery-speed sacrifice</td>
<td>The two counters must be used at sorcery speed, and the land is gone afterwards. Activate it after tapping it for mana in the same turn</td>
</tr>
<tr class="even">
<td>Little Bear’s untap</td>
<td>It untaps another target creature you control on entry; if that creature is a Bear it also gets a +1/+1 counter. Flashing it in during combat untaps an attacker you have already attacked with</td>
</tr>
<tr class="odd">
<td>Pinecone Strike is modal</td>
<td>Three damage to a creature, or destroying an artifact token, or both if you have two targets. It is the cleanest answer to Treasure and Map tokens</td>
</tr>
<tr class="even">
<td>No reach in the red splash</td>
<td>Beyond Large Bear’s reach and Wilderland Scrounger’s size, the deck is soft to fliers. Quarrel and Pinecone Strike are the answers, and racing with trample is often better than trading</td>
</tr>
</tbody>
</table>
</section>
<section id="matchups" class="level2">
<h2 class="anchored" data-anchor-id="matchups">Matchups</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 62%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Opponent</th>
<th>Plan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aggro, including fliers and lifegain counters</td>
<td>Ravening Warg’s deathtouch and lifegain is the stabiliser, and Pinecone Strike answers the first two-drop. Trade early, then take over with Ordinary Bear and Chief Warg’s Company</td>
</tr>
<tr class="even">
<td>Midrange</td>
<td>The strong matchup. Beorn plus repeated landfall Bear tokens outgrow one-for-one removal, and Mirkwood counters win the counter war against anything that does not fly</td>
</tr>
<tr class="odd">
<td>Control</td>
<td>The weak matchup. There is no card advantage beyond The Chief Warg and Beorn’s draw, so commit two threats at a time and rebuild with Dancing from Dark to Dawn’s landfall tokens</td>
</tr>
<tr class="even">
<td>Combo</td>
<td>Quarrel and Pinecone Strike are the only interaction, so the plan is speed: Wargling and Nighthowl Pursuer pressure, then Beorn plus Rogue’s Passage to close before they assemble</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="iterations" class="level1">
<h1>Iterations</h1>
<p>Two tuning rounds were run against the viability battery (three 500-game simulations per round). Both rounds were refinements after a passing list, not gate failures.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 34%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>Change</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v1 to v2</td>
<td>Removed Goblin-town (a tapped black and red dual whose activation only pumps Goblins and Orcs) and played the fifth Mountain instead, cutting the budget spend to two cards</td>
<td>Sim 60.7 to 62.7, turn-4 consistency 0.619 to 0.629, four-land probability 0.599 to 0.641, synergy 72.8 to 72.8</td>
</tr>
<tr class="even">
<td>v2 to v3</td>
<td>Removed 2 Nasty Little Rabbit (a 1/2 that only grows after ferocious is already online), added Head of the Hunt and The Chief Warg</td>
<td>Sim mean over three repeat runs 55.9 to 60.8, turn-4 consistency 0.643 to 0.634, four-land probability 0.645 to 0.624, synergy 72.8 to 72.5</td>
</tr>
</tbody>
</table>
<p>The final battery run on the v3 list returned sim 62.3 percent, turn-4 consistency 0.634, four-land probability 0.624 and synergy 72.5, with every gate passing.</p>
</section>
<section id="deck-list-arena-import" class="level1">
<h1>Deck list (Arena import)</h1>
<pre class="text"><code>Wilderland Howl
Deck
4 Wargling
4 Ravening Warg
2 Nighthowl Pursuer
1 Head of the Hunt
1 The Chief Warg
3 Little Bear
3 Ordinary Bear
2 Large Bear
2 Chief Warg's Company
2 Beorn the Fierce
2 Wilderland Scrounger
2 Dancing from Dark to Dawn
2 Thrór's Map
2 Troop of Ponies
2 Quarrel
2 Pinecone Strike
3 Mirkwood
1 Rogue's Passage
8 Forest
7 Swamp
5 Mountain</code></pre>


</section>

</main> <!-- /main -->
<script data-goatcounter="https://th3pajay.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>From th3pajay — a new Standard deck guide every morning</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/th3pajay/mtga-decks">Source on GitHub</a></p>
</div>
  </div>
</footer>




</body></html>