<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-03">

<title>Scale and Coin – MTG Decks — Daily Standard Guides</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a8dd2cfac03084eab458e3b1c626e1f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MTG Decks — Daily Standard Guides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a>
  <ul class="collapse">
  <li><a href="#game-plan-phases" id="toc-game-plan-phases" class="nav-link" data-scroll-target="#game-plan-phases">Game plan phases</a></li>
  <li><a href="#card-roles" id="toc-card-roles" class="nav-link" data-scroll-target="#card-roles">Card roles</a></li>
  <li><a href="#lands-as-engines" id="toc-lands-as-engines" class="nav-link" data-scroll-target="#lands-as-engines">Lands as engines</a></li>
  <li><a href="#curve-and-mana" id="toc-curve-and-mana" class="nav-link" data-scroll-target="#curve-and-mana">Curve and mana</a></li>
  </ul></li>
  <li><a href="#gameplay-strategy" id="toc-gameplay-strategy" class="nav-link" data-scroll-target="#gameplay-strategy">Gameplay strategy</a>
  <ul class="collapse">
  <li><a href="#early-game" id="toc-early-game" class="nav-link" data-scroll-target="#early-game">Early game</a></li>
  <li><a href="#mid-game" id="toc-mid-game" class="nav-link" data-scroll-target="#mid-game">Mid game</a></li>
  <li><a href="#the-combo-turn" id="toc-the-combo-turn" class="nav-link" data-scroll-target="#the-combo-turn">The combo turn</a></li>
  <li><a href="#win-condition-2" id="toc-win-condition-2" class="nav-link" data-scroll-target="#win-condition-2">Win condition 2</a></li>
  <li><a href="#mulligan-guide" id="toc-mulligan-guide" class="nav-link" data-scroll-target="#mulligan-guide">Mulligan guide</a></li>
  <li><a href="#key-interactions-and-edge-cases" id="toc-key-interactions-and-edge-cases" class="nav-link" data-scroll-target="#key-interactions-and-edge-cases">Key interactions and edge cases</a></li>
  <li><a href="#matchups" id="toc-matchups" class="nav-link" data-scroll-target="#matchups">Matchups</a></li>
  </ul></li>
  <li><a href="#iterations" id="toc-iterations" class="nav-link" data-scroll-target="#iterations">Iterations</a></li>
  <li><a href="#deck-list-arena-import" id="toc-deck-list-arena-import" class="nav-link" data-scroll-target="#deck-list-arena-import">Deck list (Arena import)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Scale and Coin</h1>
<p class="subtitle lead">Grixis (UBR) Smaug Dragon × Treasure — The Hobbit set identity deck</p>
  <div class="quarto-categories">
    <div class="quarto-category">hobbit</div>
    <div class="quarto-category">smaug</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 3, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="at-a-glance" class="level1">
<h1>At a glance</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 61%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Format</td>
<td>Standard (MTGA)</td>
</tr>
<tr class="even">
<td>Colors</td>
<td>Blue / Black / Red (UBR)</td>
</tr>
<tr class="odd">
<td>Archetype</td>
<td>Smaug treasure-dragon engine (avg nonland CMC ~2.9)</td>
</tr>
<tr class="even">
<td>Core mechanic</td>
<td>Treasure generation × artifact-ETB draw × dragon payoffs</td>
</tr>
<tr class="odd">
<td>Primary win</td>
<td>Smaug the Magnificent attacks with a hoard of Treasures and deals that much damage to any target; every Treasure that enters draws a card off Fateful Discovery</td>
</tr>
<tr class="even">
<td>Secondary win</td>
<td>Dragon swarm — The Misty Mountains Cold’s 6/6 Dragon, Magda’s 4/4 haste Dragon tokens, Smaug Wicked Worm and Rapacious Dragon beat down</td>
</tr>
<tr class="odd">
<td>Land win condition</td>
<td>The Lonely Mountain turns late-game treasure mana into 2/2 Dwarf tokens; Cavern of Souls (naming Dragon) makes every dragon cast uncounterable</td>
</tr>
</tbody>
</table>
</section>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>Scale and Coin is the Grixis Smaug deck. Every spell either makes a Treasure, draws off the Treasures being made, or is a Dragon that profits from them. The engine loops two abilities: <strong>Fateful Discovery</strong> — “whenever an artifact you control enters, draw a card” — turns every Treasure token into a cantrip, and <strong>Smaug the Magnificent</strong> — a 4/3 flying haste Dragon that creates a Treasure each upkeep and then deals damage equal to your Treasure count to any target whenever it attacks.</p>
<p>The red shell is the Smaug identity: The Misty Mountains Cold (a saga whose four chapters each make a Treasure and then become a 6/6 Dragon), Desolation of Smaug (a 3-damage sweep that also ramps four mana into a Dragon), Last Light of Durin’s Day (a Mountain-quest that tutors a Dragon into play), and Magda, the Hoardmaster (crimes make Treasures; three Treasures make a 4/4 haste Dragon). Blue is the draw engine — Fateful Discovery, Stock Up, Collector’s Vault — and black brings The Sackville-Bagginses, Nowhere to Run and Smaug, Wicked Worm, who converts your own Treasure casts into cards.</p>
<p>The deck wins by out-drawing the opponent while the Treasure count climbs, then pointing Smaug’s attack trigger — or a wave of Dragon tokens — at the opponent’s face. It is a value-tempo combo deck: it plays like a ramp-draw engine for the first turns and like a burn deck the moment Smaug or a 6/6 Dragon token lands.</p>
</section>
<section id="approach" class="level1">
<h1>Approach</h1>
<section id="game-plan-phases" class="level2">
<h2 class="anchored" data-anchor-id="game-plan-phases">Game plan phases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>What happens</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Turns 1-2</td>
<td>Develop: Magda, Sarkhan, Sackville-Bagginses or Collector’s Vault; start accruing Treasures</td>
</tr>
<tr class="even">
<td>Turns 3-4</td>
<td>Engine: Dori or The Misty Mountains Cold; Fateful Discovery turns every Treasure into a card; remove blockers with Nowhere to Run</td>
</tr>
<tr class="odd">
<td>Turns 5-6</td>
<td>Convert: Smaug the Magnificent attacks with 4-7 Treasures for 4-7 to any target; Desolation of Smaug clears boards then casts a Dragon</td>
</tr>
<tr class="even">
<td>Late game</td>
<td>Dragon swarm closes: Misty saga 6/6, Magda 4/4 haste tokens, Wicked Worm 5/5; The Lonely Mountain sinks spare Treasure mana into Dwarf tokens</td>
</tr>
</tbody>
</table>
</section>
<section id="card-roles" class="level2">
<h2 class="anchored" data-anchor-id="card-roles">Card roles</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Card</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Smaug the Magnificent</td>
<td>Primary payoff: upkeep Treasure, and attack damage equal to your Treasure count to any target (flying, haste)</td>
</tr>
<tr class="even">
<td>Smaug, Wicked Worm</td>
<td>5/5 flying Dragon that enters with a Treasure per opposing artifact and draws a card each time you cast with Treasure mana</td>
</tr>
<tr class="odd">
<td>The Misty Mountains Cold</td>
<td>Saga engine: four chapter triggers each make a Treasure, then sacrifices itself for a 6/6 flying Dragon</td>
</tr>
<tr class="even">
<td>Fateful Discovery</td>
<td>Engine: every artifact entering draws a card — every Treasure, Clue-less token, Vault and Barrier trigger it</td>
</tr>
<tr class="odd">
<td>Magda, the Hoardmaster</td>
<td>Treasure on each crime; three Treasures become a 4/4 red Dragon token with flying and haste</td>
</tr>
<tr class="even">
<td>Sarkhan, Dragon Ascendant</td>
<td>2-drop that beholds a Dragon into a Treasure and grows +1/+1 whenever a Dragon enters, becoming a Dragon itself</td>
</tr>
<tr class="odd">
<td>Dori, Bearer of Friends</td>
<td>3/2 trample that makes a Treasure on entry — the curve filler between Magda and Smaug</td>
</tr>
<tr class="even">
<td>Rapacious Dragon</td>
<td>3/3 flying that enters with two Treasures — ramp plus a body</td>
</tr>
<tr class="odd">
<td>The Sackville-Bagginses</td>
<td>Sacrifices a creature or artifact to draw and make a Treasure; token sacrifices ping the opponent</td>
</tr>
<tr class="even">
<td>Desolation of Smaug</td>
<td>Sweeps all non-Dragons for 3, then adds four mana usable only for Dragon spells</td>
</tr>
<tr class="odd">
<td>Last Light of Durin’s Day</td>
<td>Mountain quest that puts a Dragon onto the battlefield at six Mountains; mountaincycles to fix mana</td>
</tr>
<tr class="even">
<td>Collector’s Vault</td>
<td>Loot plus a Treasure every activation — an artifact that fuels Fateful Discovery</td>
</tr>
<tr class="odd">
<td>Gleaming Barrier</td>
<td>0/4 defender that chump-blocks early and makes a Treasure when it dies</td>
</tr>
<tr class="even">
<td>Stock Up</td>
<td>Digs five, keeps two — finds the engine pieces</td>
</tr>
<tr class="odd">
<td>Spell Pierce</td>
<td>Protects Smaug and the sagas from removal and board wipes</td>
</tr>
<tr class="even">
<td>Nowhere to Run</td>
<td>Flash -3/-3 that also turns off hexproof and ward for later removal</td>
</tr>
</tbody>
</table>
</section>
<section id="lands-as-engines" class="level2">
<h2 class="anchored" data-anchor-id="lands-as-engines">Lands as engines</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Land</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>The Lonely Mountain</td>
<td>Land win condition: a Mountain (feeds Last Light of Durin’s Day) that sinks spare Treasure mana into 2/2 Dwarf tokens; enters tapped unless you control an Equipment</td>
</tr>
<tr class="even">
<td>Cavern of Souls</td>
<td>Names Dragon: dragon spells can’t be countered and get any-color mana — protects the Smaug cast</td>
</tr>
<tr class="odd">
<td>Izzet Guildgate</td>
<td>Blue-red fixing for the draw engine</td>
</tr>
<tr class="even">
<td>Island / Swamp / Mountain</td>
<td>Blue-black core with a red base — the deck needs {R} early, {U}{U} for Fateful Discovery by turn five</td>
</tr>
</tbody>
</table>
</section>
<section id="curve-and-mana" class="level2">
<h2 class="anchored" data-anchor-id="curve-and-mana">Curve and mana</h2>
<p>Twenty-five lands: seventeen basics (7 Mountain, 6 Island, 6 Swamp) plus eight nonbasics (3 The Lonely Mountain, 1 Cavern of Souls, 2 Izzet Guildgate). The red base comes down early for Magda and Sarkhan; the two guildgates and Cavern cover the blue splash while Swamps support black. The curve is engine-shaped: six two-drop plays (Magda, Sarkhan, Sackville-Bagginses, Collector’s Vault, Gleaming Barrier, Last Light), four three-drops (Dori, Misty saga, Stock Up), and the four-to-five mana payoff cluster (Smaug the Magnificent, Desolation of Smaug, Wicked Worm, Rapacious Dragon, Fateful Discovery). Treasures effectively advance the curve by a full turn — a turn-three Dori or Misty saga makes turn-four Smaug routine.</p>
</section>
</section>
<section id="gameplay-strategy" class="level1">
<h1>Gameplay strategy</h1>
<section id="early-game" class="level2">
<h2 class="anchored" data-anchor-id="early-game">Early game</h2>
<p>Lead with Magda (crimes feed her Treasure), Sarkhan (behold a Dragon from hand for a Treasure), The Sackville-Bagginses, or Collector’s Vault. Gleaming Barrier stalls aggro while setting up a death-Treasure. Do not churn Treasures for mana unless the play matters — the Treasure count is both your mana and your damage. Play toward Fateful Discovery on four or five: from that point every Treasure ETB replaces itself.</p>
</section>
<section id="mid-game" class="level2">
<h2 class="anchored" data-anchor-id="mid-game">Mid game</h2>
<p>Resolve The Misty Mountains Cold or Dori to start the Treasure train, then Fateful Discovery. Each subsequent Treasure — Smaug’s upkeep trigger, Magda’s crime Treasure, Sackville’s draw-Treasure, a dying Gleaming Barrier, Collector’s Vault — draws a card. This is where the deck pulls ahead: Treasure count climbs and the hand refills every turn, so removal and counters stay stocked. Nowhere to Run clears hexproof/ward threats at flash speed.</p>
</section>
<section id="the-combo-turn" class="level2">
<h2 class="anchored" data-anchor-id="the-combo-turn">The combo turn</h2>
<p>With Fateful Discovery and Magda on board and a Treasure count of five or more: commit a crime (Nowhere to Run on their creature) for a tapped Treasure — that ETB draws a card. Sacrifice three Treasures to Magda for a 4/4 haste Dragon, whose entry grows Sarkhan and (if Sarkhan is out) makes him a flying Dragon too. Cast Smaug the Magnificent, then attack: he deals damage equal to the remaining Treasures to any target — removal or face. Desolation of Smaug is the reset button: it sweeps their non-Dragon board, then its four floating mana cast Wicked Worm or Rapacious Dragon the same turn.</p>
</section>
<section id="win-condition-2" class="level2">
<h2 class="anchored" data-anchor-id="win-condition-2">Win condition 2</h2>
<p>The Dragon swarm. The Misty Mountains Cold resolves fully into a 6/6 flying Dragon; Magda converts three Treasures into haste Dragons on demand; Smaug, Wicked Worm is a 5/5 flyer that can enter with a Treasure per opposing artifact; Rapacious Dragon brings two Treasures and a 3/3 flyer. Multiple evasive Dragons end games that Smaug’s ping can’t reach — especially against lifegain, where the attack-trigger damage plus flyer beats outlasts incidental life.</p>
</section>
<section id="mulligan-guide" class="level2">
<h2 class="anchored" data-anchor-id="mulligan-guide">Mulligan guide</h2>
<p>Keep any hand with two or three lands and a two-drop engine (Magda, Sarkhan, Sackville-Bagginses, Collector’s Vault). Hands with Smaug the Magnificent plus any Treasure source are strong. Ship one-landers, hands with three or more five-drops, and hands with no red source. Against aggressive decks, prioritize Gleaming Barrier and Nowhere to Run over the slow draw pieces; against control, keep Spell Pierce and lean on Cavern of Souls naming Dragon.</p>
</section>
<section id="key-interactions-and-edge-cases" class="level2">
<h2 class="anchored" data-anchor-id="key-interactions-and-edge-cases">Key interactions and edge cases</h2>
<ul>
<li>Smaug’s attack trigger deals damage equal to your Treasure count at the moment the trigger resolves — sacrifice Treasures for mana after declaring attackers, not before, if you want maximum damage.</li>
<li>Fateful Discovery triggers on artifacts entering, not tokens specifically: Treasure tokens, Gleaming Barrier, Collector’s Vault, and Cavern-free artifact creatures all draw. The Misty Mountains Cold’s four chapter triggers each draw a card with Fateful Discovery out.</li>
<li>The Misty Mountains Cold checks for four or more Treasures after each chapter trigger, then sacrifices itself for a 6/6 Dragon — it needs four Treasures, not four counters, so time your Treasure spends carefully if you want the Dragon rather than the mana.</li>
<li>Magda’s Treasure trigger fires once per turn regardless of how many crimes you commit — one crime per turn is enough.</li>
<li>“Commit a crime” means targeting the opponent, anything they control, or cards in their graveyard — Nowhere to Run, removal, and even a counterspell aimed at their spell are crimes.</li>
<li>Desolation of Smaug damages non-Dragon creatures — your Dragon tokens and Dragons survive while everything else on both sides takes 3. The four mana it adds can only cast Dragon spells.</li>
<li>The Sackville-Bagginses’ token-sacrifice ping includes Treasure tokens sacrificed for mana — cracking a Treasure at the right moment doubles as a Shock.</li>
<li>Cavern of Souls must name Dragon before it taps for the uncounterable any-color mana; it only protects Dragon creature spells.</li>
<li>Wicked Worm draws when you cast a spell <em>with mana from a Treasure</em> — mana from Cavern, basic lands or treasures all mix, so this triggers only if Treasure mana was actually spent on that spell.</li>
</ul>
</section>
<section id="matchups" class="level2">
<h2 class="anchored" data-anchor-id="matchups">Matchups</h2>
<ul>
<li><strong>Aggro (fliers, lifegain, cats)</strong>: Gleaming Barrier and Nowhere to Run hold the ground until Desolation of Smaug resets the board; the deck’s draw engine finds answers faster than aggro refills. Smaug’s ping doubles as removal for their biggest threat.</li>
<li><strong>Midrange (landfall, counters)</strong>: the Treasure-draw engine out-values them — every Treasure replaces itself and every Dragon is bigger than their curve; Desolation clears their developed board and ramps into a Dragon on the same turn.</li>
<li><strong>Control</strong>: Cavern of Souls (naming Dragon), Spell Pierce and Wicked Worm’s treasure-cast draw keep gas flowing; the saga and enchantment engines (Misty Mountains Cold, Fateful Discovery, Last Light of Durin’s Day) are hard for sweepers to answer permanently.</li>
<li><strong>Combo and big mana</strong>: the deck is the aggressor — haste Smaug and Magda Dragons pressure before their engine comes online, and Nowhere to Run plus Spell Pierce disrupt key pieces.</li>
</ul>
</section>
</section>
<section id="iterations" class="level1">
<h1>Iterations</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 20%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>Change</th>
<th>Sim avg</th>
<th>Synergy</th>
<th>Goldfish T4</th>
<th>P(≥4 lands T4)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v1 → v2</td>
<td>−1 Collector’s Vault, −1 Spell Pierce, +2 Gleaming Barrier (cheap artifact defender bodies chump early, trigger Fateful Discovery on entry, and replace themselves with a Treasure on death)</td>
<td>52.0 → 56.3</td>
<td>70.6 → 70.6</td>
<td>0.678 → 0.662</td>
<td>0.679 → 0.660</td>
</tr>
</tbody>
</table>
<p>All seven battery gates passed on the final list (v2): size 60 with no missing cards, Standard-legal, zero rotating cards, sim 3-run average 56.3, synergy 70.6, goldfish T4 consistency 0.662, P(≥4 lands by T4) 0.660.</p>
</section>
<section id="deck-list-arena-import" class="level1">
<h1>Deck list (Arena import)</h1>
<pre class="text"><code>Scale and Coin
Deck
4 Smaug the Magnificent
3 Smaug, Wicked Worm
2 Rapacious Dragon
3 Magda, the Hoardmaster
2 Sarkhan, Dragon Ascendant
3 Dori, Bearer of Friends
2 The Sackville-Bagginses
1 Collector's Vault
2 Gleaming Barrier
3 The Misty Mountains Cold
1 Last Light of Durin's Day
2 Desolation of Smaug
2 Fateful Discovery
2 Stock Up
1 Spell Pierce
2 Nowhere to Run
3 The Lonely Mountain
1 Cavern of Souls
2 Izzet Guildgate
6 Island
6 Swamp
7 Mountain</code></pre>


</section>

</main> <!-- /main -->
<script data-goatcounter="https://th3pajay.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>From th3pajay — a new Standard deck guide every morning</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/th3pajay/mtga-decks">Source on GitHub</a></p>
</div>
  </div>
</footer>




</body></html>