<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-12">

<title>Hammerhone Saga – MTG Decks — Daily Standard Guides</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a8dd2cfac03084eab458e3b1c626e1f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MTG Decks — Daily Standard Guides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a>
  <ul class="collapse">
  <li><a href="#game-plan-phases" id="toc-game-plan-phases" class="nav-link" data-scroll-target="#game-plan-phases">Game plan phases</a></li>
  <li><a href="#card-roles" id="toc-card-roles" class="nav-link" data-scroll-target="#card-roles">Card roles</a></li>
  <li><a href="#lands-as-engines" id="toc-lands-as-engines" class="nav-link" data-scroll-target="#lands-as-engines">Lands as engines</a></li>
  <li><a href="#curve-and-mana" id="toc-curve-and-mana" class="nav-link" data-scroll-target="#curve-and-mana">Curve and mana</a></li>
  </ul></li>
  <li><a href="#gameplay-strategy" id="toc-gameplay-strategy" class="nav-link" data-scroll-target="#gameplay-strategy">Gameplay strategy</a>
  <ul class="collapse">
  <li><a href="#early-game" id="toc-early-game" class="nav-link" data-scroll-target="#early-game">Early game</a></li>
  <li><a href="#mid-game" id="toc-mid-game" class="nav-link" data-scroll-target="#mid-game">Mid game</a></li>
  <li><a href="#the-combo-turn" id="toc-the-combo-turn" class="nav-link" data-scroll-target="#the-combo-turn">The combo turn</a></li>
  <li><a href="#win-condition-2" id="toc-win-condition-2" class="nav-link" data-scroll-target="#win-condition-2">Win condition 2</a></li>
  <li><a href="#mulligan-guide" id="toc-mulligan-guide" class="nav-link" data-scroll-target="#mulligan-guide">Mulligan guide</a></li>
  <li><a href="#key-interactions-and-edge-cases" id="toc-key-interactions-and-edge-cases" class="nav-link" data-scroll-target="#key-interactions-and-edge-cases">Key interactions and edge cases</a></li>
  <li><a href="#matchups" id="toc-matchups" class="nav-link" data-scroll-target="#matchups">Matchups</a></li>
  </ul></li>
  <li><a href="#iterations" id="toc-iterations" class="nav-link" data-scroll-target="#iterations">Iterations</a></li>
  <li><a href="#deck-list-arena-import" id="toc-deck-list-arena-import" class="nav-link" data-scroll-target="#deck-list-arena-import">Deck list (Arena import)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Hammerhone Saga</h1>
<p class="subtitle lead">Mardu (Red / White / Black) — Storied Dwarves x Equipment, built on The Hobbit set identity</p>
  <div class="quarto-categories">
    <div class="quarto-category">hobbit</div>
    <div class="quarto-category">dwarves</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 12, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="at-a-glance" class="level1">
<h1>At a glance</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 61%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Format</td>
<td>Standard (MTGA)</td>
</tr>
<tr class="even">
<td>Colors</td>
<td>Red / White with a black splash (three colors)</td>
</tr>
<tr class="odd">
<td>Archetype</td>
<td>Aggro-midrange — Storied Dwarves x Equipment</td>
</tr>
<tr class="even">
<td>Size</td>
<td>60 cards (37 spells and permanents, 23 lands, average mana value 2.51)</td>
</tr>
<tr class="odd">
<td>Signature mechanic</td>
<td>Storied (three or more artifacts, legendaries or Sagas) plus Equipment hone counters</td>
</tr>
<tr class="even">
<td>Primary win</td>
<td>Dwarf token swarm under An Unexpected Party and Thorin Oakenshield</td>
</tr>
<tr class="odd">
<td>Secondary win</td>
<td>Equipment rack on one Dwarf — Thorin, Mountain-king attaches the rack and bites a blocker</td>
</tr>
<tr class="even">
<td>Land win condition</td>
<td>The Lonely Mountain, repeatable 2/2 red Dwarf tokens</td>
</tr>
<tr class="odd">
<td>Measured performance</td>
<td>Sim 60.0 percent over three 500-game runs, turn-4 consistency 0.607, four-land probability by turn 4 of 0.614, cohesion 70.9</td>
</tr>
</tbody>
</table>
</section>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>Hammerhone Saga is a two-loop Dwarf deck. The first loop is Storied: the list is loaded with cheap artifacts, legendary Dwarves and Sagas so three or more are on the battlefield by turn three, which switches the whole Dwarf suite on for the rest of the game. The second loop is the hone counter: Dwalin, Weaponmaster puts a hone counter on every Equipment you control whenever it enters or attacks, and each counter is a permanent +1/+0 for whoever carries that Equipment. The rack gets better every turn instead of staying a fixed stat bonus.</p>
<p>The loops feed each other. Kíli the Resourceful and Óin the Brave only cash in once you have an enduring story, and they need artifacts on board to get there, while every Equipment you cast both pays toward Storied and carries a hone counter. Dáin Ironfoot and Iron Hills Blacksmith each mint an Equipment artifact token named Axe on entry, so one creature can push the artifact count over three by itself and simultaneously shave mana off the win-condition land. The black splash is a single card, Crude Bent Blade: an Equipment that makes an opponent sacrifice a creature, and at the same time a Storied artifact, a hone counter target and the removal spell the deck otherwise lacks.</p>
<p>The deck wins wide rather than tall. The Lonely Mountain turns surplus Equipment into 2/2 red Dwarf tokens at a discount, and An Unexpected Party turns those tokens into 4/4 attackers that also carry ward once Thorin Oakenshield is out. When the token plan is answered, Thorin, Mountain-king is the pivot: he hands the whole rack to one Dwarf and turns its power into a removal spell.</p>
</section>
<section id="approach" class="level1">
<h1>Approach</h1>
<section id="game-plan-phases" class="level2">
<h2 class="anchored" data-anchor-id="game-plan-phases">Game plan phases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>Turns</th>
<th>What the deck is doing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Set up</td>
<td>1 to 2</td>
<td>Land a two-drop that builds board: Dáin’s Company digs for the next Dwarf or Equipment, Kíli the Resourceful draws off Equipment entry, Iron Hills Blacksmith leaves an Axe token behind</td>
</tr>
<tr class="even">
<td>Establish Storied</td>
<td>3</td>
<td>The third artifact, legendary or Saga arrives. An Axe from Dáin Ironfoot or Iron Hills Blacksmith crosses the line alone, Crude Bent Blade supplies removal and an artifact at once</td>
</tr>
<tr class="odd">
<td>Turn the corner</td>
<td>4 to 5</td>
<td>Thorin Oakenshield grants ward to the team, Dáin Ironfoot attacks with double strike, The Lonely Mountain converts spare mana into 2/2 Dwarf tokens</td>
</tr>
<tr class="even">
<td>Close</td>
<td>6 plus</td>
<td>An Unexpected Party pumps every Dwarf by +2/+2 while the land keeps making tokens, or one Dwarf carries four or more Equipment and Thorin, Mountain-king converts that power into damage</td>
</tr>
</tbody>
</table>
</section>
<section id="card-roles" class="level2">
<h2 class="anchored" data-anchor-id="card-roles">Card roles</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 69%">
</colgroup>
<thead>
<tr class="header">
<th>Role</th>
<th>Cards</th>
<th>What the card actually does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hone engine</td>
<td>Dwalin, Weaponmaster (3), Sting, Bilbo’s Sword (2)</td>
<td>Dwalin adds a hone counter to each Equipment you control on entry and on every attack. Sting enters with one per opposing creature and attaches itself for free, so it scales against any board</td>
</tr>
<tr class="even">
<td>Storied enablers</td>
<td>Kíli the Resourceful (3), Óin the Brave (2), Thorin Oakenshield (2)</td>
<td>Kíli pays {0} for the first equip each turn and draws when another Dwarf or Equipment enters. Óin gains +1/+0 and haste. Thorin Oakenshield gives artifacts and creatures ward {1} and tramples</td>
</tr>
<tr class="odd">
<td>Body and artifact makers</td>
<td>Dáin Ironfoot (3), Iron Hills Blacksmith (3), Dwarven Shortsword (2)</td>
<td>The first two create a colorless Equipment artifact token named Axe on entry; Dwarven Shortsword creates a 2/2 red Dwarf token and attaches to it. All three are artifacts toward Storied and Equipment for the land discount, and they carry double strike or a free body</td>
</tr>
<tr class="even">
<td>Rack payoffs</td>
<td>Thorin, Mountain-king (2), Dwarven Mattock (2), Ragged Short Spear (2)</td>
<td>Mattock gives +2/+2 and ward {1} and attaches free to a Dwarf. Spear gives +2/+0 and loots two. Thorin, Mountain-king attaches any number of Equipment to one creature, which then deals damage equal to its power to a blocker</td>
</tr>
<tr class="odd">
<td>Flow and interaction</td>
<td>Dáin’s Company (3), Crude Bent Blade (2), Stone by Sunlight (1), Burn, Burn, Tree and Fern (1), Giant’s Boulder (1)</td>
<td>Company looks at the top four and takes a Dwarf or Equipment. Blade forces a sacrifice on entry and is the deck’s cheapest answer to a large blocker. Stone by Sunlight kills anything with power four or greater. The Burn saga deals six damage, then destroys an artifact. Boulder fixes a color and scries two</td>
</tr>
<tr class="even">
<td>Team pump</td>
<td>An Unexpected Party (2), The Mountain-king’s Return (1)</td>
<td>Unexpected Party gives every Dwarf +2/+2, and its Adventure makes X 2/2 red Dwarf tokens for {X}{2}{W}. The Return saga recruits a Soldier and returns a creature of mana value three or less</td>
</tr>
</tbody>
</table>
</section>
<section id="lands-as-engines" class="level2">
<h2 class="anchored" data-anchor-id="lands-as-engines">Lands as engines</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Land</th>
<th>Count</th>
<th>Why it is in the deck</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>The Lonely Mountain</td>
<td>3</td>
<td>The win-condition land. It enters untapped if you control an Equipment, taps for red as a Mountain, and for {4}{R} creates a 2/2 red Dwarf token, reduced by {1} for each Equipment you control. With three Equipment out the activation costs one mana</td>
</tr>
<tr class="even">
<td>Sundown Pass / Shattered Sanctum</td>
<td>3 / 3</td>
<td>Untapped once you control two other lands: red and white from the Pass, black and white from the Sanctum. The Sanctum is the main black source for Crude Bent Blade</td>
</tr>
<tr class="odd">
<td>Nomad Outpost</td>
<td>2</td>
<td>Enters tapped, but produces red, white or black, so it fixes the splash without spending a spell slot</td>
</tr>
<tr class="even">
<td>Temple of Triumph</td>
<td>2</td>
<td>Scry one, then red or white. Keeps two-drop-heavy draws from stalling</td>
</tr>
<tr class="odd">
<td>Mountain / Plains / Swamp</td>
<td>4 / 4 / 2</td>
<td>Basics to bring the check lands in untapped and to give land finds real targets</td>
</tr>
</tbody>
</table>
<p>Colored sources: fourteen red, fourteen white, seven black. The black count is deliberately low because only Crude Bent Blade needs it; this is a red-white deck that occasionally casts a three-mana black Equipment.</p>
</section>
<section id="curve-and-mana" class="level2">
<h2 class="anchored" data-anchor-id="curve-and-mana">Curve and mana</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Mana value</th>
<th>Count</th>
<th>Cards</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One and two</td>
<td>24</td>
<td>Giant’s Boulder, Dáin’s Company, Dwalin, Kíli, Iron Hills Blacksmith, Thorin Oakenshield, Óin, Ragged Short Spear, Stone by Sunlight</td>
</tr>
<tr class="even">
<td>Three</td>
<td>6</td>
<td>Dáin Ironfoot, Dwarven Mattock, Sting, Crude Bent Blade, The Mountain-king’s Return</td>
</tr>
<tr class="odd">
<td>Four</td>
<td>7</td>
<td>Thorin, Mountain-king, Dwarven Shortsword, An Unexpected Party, Burn, Burn, Tree and Fern</td>
</tr>
</tbody>
</table>
<p>The deck wants three lands and stops caring at four. Four-land probability by turn four is 0.614 and turn-four consistency is 0.607, both above the 0.55 threshold the build is held to.</p>
</section>
</section>
<section id="gameplay-strategy" class="level1">
<h1>Gameplay strategy</h1>
<section id="early-game" class="level2">
<h2 class="anchored" data-anchor-id="early-game">Early game</h2>
<p>Open on whichever two-drop builds the most board. Dáin’s Company is the best turn-two play because it looks at four cards and takes a Dwarf or an Equipment; Iron Hills Blacksmith is the fastest because it leaves an Axe token, which counts toward Storied immediately. Dwalin, Weaponmaster is the play when an Equipment is already down, since every later attack adds a hone counter to the whole rack. Never hold Equipment back to protect a creature that has not arrived: the rack is the engine, and empty Equipment still counts for Storied.</p>
</section>
<section id="mid-game" class="level2">
<h2 class="anchored" data-anchor-id="mid-game">Mid game</h2>
<p>Turns three to five are about crossing the Storied threshold and holding it. The magic number is three artifacts, legendaries or Sagas. Two Equipment plus one legendary Dwarf gets there, an Axe token counts, and the Sagas count on their own.</p>
<p>Once the story is enduring, Kíli equips for zero on the first activation each turn and draws off every other Dwarf or Equipment that enters, and Óin attacks with haste. The Lonely Mountain’s token activation drops by one mana per Equipment, so with four Equipment out it is effectively free each turn. Hold Crude Bent Blade for the biggest blocker the opponent has committed rather than firing it early; it is one of only two clean removal effects in the list.</p>
</section>
<section id="the-combo-turn" class="level2">
<h2 class="anchored" data-anchor-id="the-combo-turn">The combo turn</h2>
<p>The big swing is Thorin, Mountain-king in the four slot with four or more Equipment on the battlefield:</p>
<ol type="1">
<li>Cast Thorin, Mountain-king. His trigger attaches any number of Equipment you control to one target creature you control.</li>
<li>Stack the rack on the best carrier. Mattock, Spear, Sting’s hone counters and a couple of Axe tokens routinely make a 10 power Dwarf that also has ward and double strike from another body.</li>
<li>The same trigger makes the equipped creature deal damage equal to its power to up to one target creature, so the carrier doubles as a removal spell. Point it at the best blocker before attackers are declared.</li>
<li>Attack with the carrier, Dáin Ironfoot holding double strike and Thorin Oakenshield’s trample carrying the excess through.</li>
</ol>
<p>Sequence it after combat if the opponent has instant-speed removal, so the trigger cannot be answered before damage is assigned.</p>
</section>
<section id="win-condition-2" class="level2">
<h2 class="anchored" data-anchor-id="win-condition-2">Win condition 2</h2>
<p>The second win is attrition by tokens, and it is the plan when the rack is answered. Dáin Ironfoot and Iron Hills Blacksmith make Axe Equipment tokens, Dwarven Shortsword makes a real 2/2 Dwarf, and The Lonely Mountain makes a 2/2 red Dwarf every turn for one or two mana. An Unexpected Party then turns the board into 4/4s by naming Dwarf, and Thorin Oakenshield gives it ward {1}.</p>
<p>Order matters: cast the Adventure face of An Unexpected Party at sorcery speed to make tokens, then cast the enchantment face later from exile once the board is wide. The enchantment is the payoff and the Adventure is the setup, and six mana is not available on one turn, so plan a two-turn sequence.</p>
</section>
<section id="mulligan-guide" class="level2">
<h2 class="anchored" data-anchor-id="mulligan-guide">Mulligan guide</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 57%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Hand shape</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Two lands plus Dáin’s Company or Iron Hills Blacksmith</td>
<td>Keep. Two mana is where the deck lives</td>
</tr>
<tr class="even">
<td>One land with Dwalin and an Equipment</td>
<td>Mulligan. The deck needs three mana by turn three to keep the engine turning</td>
</tr>
<tr class="odd">
<td>Two lands with no Dwarf and no Equipment</td>
<td>Mulligan. Both loops need a body or a rack piece on turn two</td>
</tr>
<tr class="even">
<td>Three lands with Dwalin, Dáin Ironfoot and Crude Bent Blade</td>
<td>Keep. Hone engine, artifact count and removal in one hand</td>
</tr>
</tbody>
</table>
<p>Treat a Crude Bent Blade in the opener as a reason to keep rather than a bonus.</p>
</section>
<section id="key-interactions-and-edge-cases" class="level2">
<h2 class="anchored" data-anchor-id="key-interactions-and-edge-cases">Key interactions and edge cases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 53%">
</colgroup>
<thead>
<tr class="header">
<th>Interaction</th>
<th>Ruling detail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Axe tokens count for everything</td>
<td>The Axe from Dáin Ironfoot and Iron Hills Blacksmith is a colorless Equipment artifact token. It counts toward Storied, receives hone counters from Dwalin, reduces The Lonely Mountain’s activation and can be attached by Thorin, Mountain-king. It is not a creature, so it cannot attack or block</td>
</tr>
<tr class="even">
<td>Kíli’s free equip and draw</td>
<td>The discount applies to the first equip each turn and only while you have an enduring story. The draw fires once per turn, on the first other Dwarf or Equipment that enters, so an Axe made before Kíli lands does not draw</td>
</tr>
<tr class="odd">
<td>Thorin, Mountain-king needs a target</td>
<td>His trigger requires a target creature you control as well as the Equipment. Casting him into an empty board is a 3/4 trampler with no trigger</td>
</tr>
<tr class="even">
<td>Ward is not protection from sweepers</td>
<td>Thorin Oakenshield’s and Dwarven Mattock’s ward {1} taxes targeted removal only. Neither stops a sweeper, and Sting is at its worst against creature-light control</td>
</tr>
<tr class="odd">
<td>Stone by Sunlight is modal</td>
<td>Destroy a creature with power four or greater, or make one of your own creatures an indestructible artifact. The second mode blanks damage-based removal and adds an artifact toward Storied at instant speed</td>
</tr>
<tr class="even">
<td>No evasion in the list</td>
<td>The deck attacks on the ground. Trample, double strike and Crude Bent Blade’s sacrifice are the only ways through a stalled board</td>
</tr>
</tbody>
</table>
</section>
<section id="matchups" class="level2">
<h2 class="anchored" data-anchor-id="matchups">Matchups</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 62%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Opponent</th>
<th>Plan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aggro, including fliers and lifegain counters</td>
<td>Race with An Unexpected Party and the Axe tokens, but keep Stone by Sunlight and Crude Bent Blade for the biggest threat. Dáin’s Company’s lifegain and Mattock’s +2/+2 and ward {1} are the stabilizers</td>
</tr>
<tr class="even">
<td>Midrange</td>
<td>The strong matchup. The rack outgrows one-for-one removal, and Thorin, Mountain-king removes the best blocker while attacking</td>
</tr>
<tr class="odd">
<td>Control</td>
<td>The weak matchup. Ward {1} does not stop sweepers and the deck has no card advantage engine beyond Kíli. Commit two bodies at a time and rebuild with land tokens</td>
</tr>
<tr class="even">
<td>Combo</td>
<td>Crude Bent Blade and Stone by Sunlight are the only interaction. Point the damage trigger at their key creature and race with double strike</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="iterations" class="level1">
<h1>Iterations</h1>
<p>One tuning round was run against the viability battery (three 500-game simulations per round). No gate failed in either round; round two was taken because the first list passed inside the noise band.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 34%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>Change</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v1 to v2</td>
<td>Removed 2 Bofur, Reliable Guardian (a 1/2 lifelink body with no artifact or token payoff), added 2 Dwarven Shortsword (a 2/2 red Dwarf token plus an Equipment on one card)</td>
<td>Sim 53.3 to 60.0 percent, turn-4 consistency 0.582 to 0.607, four-land probability 0.568 to 0.614, cohesion 70.6 to 70.9</td>
</tr>
</tbody>
</table>
<p>The final list below is the v2 list.</p>
</section>
<section id="deck-list-arena-import" class="level1">
<h1>Deck list (Arena import)</h1>
<pre class="text"><code>Hammerhone Saga
Deck
3 Dáin's Company
3 Dwalin, Weaponmaster
3 Kíli the Resourceful
3 Iron Hills Blacksmith
3 Dáin Ironfoot
2 Thorin Oakenshield
2 Óin the Brave
2 Thorin, Mountain-king
2 Dwarven Mattock
2 Ragged Short Spear
2 Sting, Bilbo's Sword
2 Crude Bent Blade
1 Giant's Boulder
2 An Unexpected Party
1 Burn, Burn, Tree and Fern
1 Stone by Sunlight
1 The Mountain-king's Return
3 The Lonely Mountain
3 Sundown Pass
3 Shattered Sanctum
2 Nomad Outpost
2 Temple of Triumph
4 Mountain
4 Plains
2 Swamp
2 Dwarven Shortsword</code></pre>


</section>

</main> <!-- /main -->
<script data-goatcounter="https://th3pajay.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>From th3pajay — a new Standard deck guide every morning</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/th3pajay/mtga-decks">Source on GitHub</a></p>
</div>
  </div>
</footer>




</body></html>