<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-23">

<title>Tallywurm – MTG Decks — Daily Standard Guides</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a8dd2cfac03084eab458e3b1c626e1f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MTG Decks — Daily Standard Guides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a>
  <ul class="collapse">
  <li><a href="#game-plan-phases" id="toc-game-plan-phases" class="nav-link" data-scroll-target="#game-plan-phases">Game plan phases</a></li>
  <li><a href="#card-roles" id="toc-card-roles" class="nav-link" data-scroll-target="#card-roles">Card roles</a></li>
  <li><a href="#lands-as-engines" id="toc-lands-as-engines" class="nav-link" data-scroll-target="#lands-as-engines">Lands as engines</a></li>
  <li><a href="#curve-and-mana" id="toc-curve-and-mana" class="nav-link" data-scroll-target="#curve-and-mana">Curve and mana</a></li>
  </ul></li>
  <li><a href="#gameplay-strategy" id="toc-gameplay-strategy" class="nav-link" data-scroll-target="#gameplay-strategy">Gameplay strategy</a>
  <ul class="collapse">
  <li><a href="#early-game" id="toc-early-game" class="nav-link" data-scroll-target="#early-game">Early game</a></li>
  <li><a href="#mid-game" id="toc-mid-game" class="nav-link" data-scroll-target="#mid-game">Mid game</a></li>
  <li><a href="#the-combo-turn" id="toc-the-combo-turn" class="nav-link" data-scroll-target="#the-combo-turn">The combo turn</a></li>
  <li><a href="#win-condition-2" id="toc-win-condition-2" class="nav-link" data-scroll-target="#win-condition-2">Win condition 2</a></li>
  <li><a href="#mulligan-guide" id="toc-mulligan-guide" class="nav-link" data-scroll-target="#mulligan-guide">Mulligan guide</a></li>
  <li><a href="#key-interactions-and-edge-cases" id="toc-key-interactions-and-edge-cases" class="nav-link" data-scroll-target="#key-interactions-and-edge-cases">Key interactions and edge cases</a></li>
  <li><a href="#matchups" id="toc-matchups" class="nav-link" data-scroll-target="#matchups">Matchups</a></li>
  </ul></li>
  <li><a href="#iterations" id="toc-iterations" class="nav-link" data-scroll-target="#iterations">Iterations</a></li>
  <li><a href="#deck-list-arena-import" id="toc-deck-list-arena-import" class="nav-link" data-scroll-target="#deck-list-arena-import">Deck list (Arena import)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tallywurm</h1>
<p class="subtitle lead">Green / White (two colors) — +1/+1 counters, fed by landfall, cashed in by Ouroboroid</p>
  <div class="quarto-categories">
    <div class="quarto-category">combo</div>
    <div class="quarto-category">counters</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 23, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="at-a-glance" class="level1">
<h1>At a glance</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 61%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Format</td>
<td>Standard (MTGA)</td>
</tr>
<tr class="even">
<td>Colors</td>
<td>Green / White (two colors — green on 30 of the 37 nonlands, white on 10, with Caradora carrying both)</td>
</tr>
<tr class="odd">
<td>Archetype</td>
<td>+1/+1 counters, built as a landfall-fed engine that ends games with one enormous combat step rather than a curve-out aggro deck</td>
</tr>
<tr class="even">
<td>Size</td>
<td>60 cards (26 creatures, 11 other spells and permanents, 23 lands; average mana value 2.35 across the 37 nonlands)</td>
</tr>
<tr class="odd">
<td>Signature mechanic</td>
<td>+1/+1 counters. Lands are the fuel: every fetch land is a landfall counter, every counter is a Caradora trigger, and Ouroboroid converts the whole board into counters on every combat</td>
</tr>
<tr class="even">
<td>Primary win</td>
<td>Ouroboroid: a 1/3 for {2}{G}{G} that, at the beginning of combat on your turn, puts X +1/+1 counters on each creature you control, where X is its own power. It feeds itself, so the second combat is four times the first</td>
</tr>
<tr class="odd">
<td>Secondary win</td>
<td>The air and the unblockable lane: Skyknight Squire has flying from three counters, Restless Prairie attacks as a 3/3 Llama and pumps the rest of the team, and Rogue’s Passage makes whichever creature is biggest unblockable</td>
</tr>
<tr class="even">
<td>Land win condition</td>
<td>Restless Prairie animates into a 3/3 green and white Llama for {2}{G}{W} and gives every other attacking creature +1/+1 when it attacks, so the land is a clock on its own and a team pump for the counter creatures. Rogue’s Passage is the finisher: four mana and a tap makes the Ouroboroid-pumped attacker unblockable</td>
</tr>
<tr class="odd">
<td>Measured performance</td>
<td>Synergy score 70.2, turn-4 consistency 0.579, four-land probability by turn 4 of 0.584, simulation 54.0 percent over three 500-game runs (59 / 54 / 49) on the recorded gate run</td>
</tr>
<tr class="even">
<td>Engine in one line</td>
<td>Fetch lands and Restless Prairie make landfall counters, Ouroboroid multiplies counters on every combat, Caradora adds one to each counter event, Training Regimen and Mossborn Hydra make the result trample, and Inspiring Call and Stocking the Pantry turn the counters into cards</td>
</tr>
</tbody>
</table>
</section>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>Every card in this list is a counter event, a counter multiplier, or a way to spend counters. The plan is to make land drops that are also spells.</p>
<p>Bristly Bill, Spine Sower and Mossborn Hydra both read “Landfall — whenever a land you control enters”. Bristly Bill puts a +1/+1 counter on any creature you control and can double the counters on the whole board for {3}{G}{G}; Mossborn Hydra doubles its own counters instead, and it has trample. With seven fetch lands in the base (Terramorphic Expanse, Evolving Wilds and Promising Vein) plus Restless Prairie, the deck runs landfall triggers on turns where it is not casting anything, and those triggers arrive as counters that Ouroboroid then multiplies.</p>
<p>Ouroboroid is the engine’s ceiling. It puts X counters on each creature you control at the beginning of combat, where X is its own power — and the ability counts its power as the trigger resolves, so the first combat (X equals 1) hands out one counter to everything, the next combat X is larger, and one Caradora, Heart of Alacria adds a counter to each of those events because any time counters would be put on a creature you control, it puts that many plus one instead.</p>
<p>The support cards exist to make those counters lethal and to keep the deck from running dry. Training Regimen gives every creature with a counter trample and adds a counter of its own every combat. Pawpatch Recruit brings offspring {2} for a second body and tramples. Wildwood Scourge grows every time another non-Hydra creature of yours receives counters, so Ouroboroid’s combat trigger is a second Ouroboroid. Skyknight Squire converts three counters into a flier. Inspiring Call draws one card per creature with a counter and makes them indestructible for the turn. Stocking the Pantry turns every counter event into a supply counter and every two mana into a card.</p>
<p>The mana is deliberately boring: five Forests, four Plains, two Temple of Plenty, two Restless Prairie, and seven lands that fetch a basic. Green is needed early (Bristly Bill, Wildwood Scourge, Pawpatch Recruit, Stocking the Pantry), white is needed from turn two (Skyknight Squire, Take Up the Shield) and turn four (Caradora), and the fetch lands thin the deck and trigger landfall in the same motion. Nothing in the 60 costs more than four mana, and 24 of the 37 nonlands cost two or less.</p>
</section>
<section id="approach" class="level1">
<h1>Approach</h1>
<section id="game-plan-phases" class="level2">
<h2 class="anchored" data-anchor-id="game-plan-phases">Game plan phases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>Turns</th>
<th>What the deck is doing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Open</td>
<td>1 to 2</td>
<td>Pawpatch Recruit or Stocking the Pantry on one, then Bristly Bill, Skyknight Squire, Broodguard Elite or Take Up the Shield on two. Start the counter ledger: every creature that lands should arrive with counters or make counters</td>
</tr>
<tr class="even">
<td>Build</td>
<td>3 to 4</td>
<td>Ouroboroid, Caradora, Heart of Alacria or Training Regimen. Crack a fetch land the turn you cast Ouroboroid so the landfall counter and the Caradora bonus land before the first combat trigger resolves</td>
</tr>
<tr class="odd">
<td>Multiplier turn</td>
<td>4 to 6</td>
<td>Two or three counter events in one combat: landfall trigger, Ouroboroid trigger, Training Regimen trigger, all of them plus one off Caradora and doubled by Bristly Bill if you have the mana. This is the turn the board stops being a board and becomes a clock</td>
</tr>
<tr class="even">
<td>Close</td>
<td>5 plus</td>
<td>Attack with everything. Training Regimen and Mossborn Hydra give trample, Skyknight Squire flies, Rogue’s Passage removes the one blocker that matters, and Inspiring Call protects the team from a sweeper while drawing into the next wave</td>
</tr>
</tbody>
</table>
</section>
<section id="card-roles" class="level2">
<h2 class="anchored" data-anchor-id="card-roles">Card roles</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 69%">
</colgroup>
<thead>
<tr class="header">
<th>Role</th>
<th>Cards</th>
<th>What the card actually does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Engine</td>
<td>Ouroboroid (3)</td>
<td>At the beginning of combat on your turn, put X +1/+1 counters on each creature you control, where X is its power. Because the trigger includes Ouroboroid itself, its power grows every combat and so does X</td>
</tr>
<tr class="even">
<td>Multipliers</td>
<td>Caradora, Heart of Alacria (3), Bristly Bill, Spine Sower (4), Mossborn Hydra (2)</td>
<td>Caradora makes every counter event one counter larger for every creature you control, and searches up a Mount or Vehicle on entry. Bristly Bill doubles the counters on each creature you control for {3}{G}{G}. Mossborn Hydra doubles only its own counters, but it does so for free on every land drop</td>
</tr>
<tr class="odd">
<td>Landfall payoffs</td>
<td>Bristly Bill, Spine Sower (4), Mossborn Hydra (2)</td>
<td>The two cards that turn Terramorphic Expanse, Evolving Wilds, Promising Vein, Temple of Plenty and Restless Prairie into counter events. Fetch lands trigger landfall the turn they are cracked, so they are one-mana spells that also fix the mana</td>
</tr>
<tr class="even">
<td>Counter carriers</td>
<td>Broodguard Elite (4), Wildwood Scourge (4), Skyknight Squire (4)</td>
<td>Broodguard Elite enters with X counters and passes its counters to another creature when it leaves, and its warp cost lets you buy it back later. Wildwood Scourge enters with X counters and adds one every time another non-Hydra creature of yours receives counters. Skyknight Squire gains a counter whenever any other creature enters and has flying from three counters</td>
</tr>
<tr class="odd">
<td>Body supply</td>
<td>Pawpatch Recruit (2)</td>
<td>A 2/1 trampler for {G} that makes a 1/1 token copy of itself for an extra {2}. Two bodies means two Skyknight Squire triggers, two Wildwood Scourge triggers and two attackers, and it also moves a counter onto another creature when the opponent points removal at it</td>
</tr>
<tr class="even">
<td>Combat fuel</td>
<td>Training Regimen (3)</td>
<td>Creatures you control with +1/+1 counters on them have trample, and at the beginning of combat on your turn you put a +1/+1 counter on a creature you control. It is a permanent counter event with the payoff attached</td>
</tr>
<tr class="odd">
<td>Card advantage</td>
<td>Stocking the Pantry (3), Inspiring Call (2)</td>
<td>Stocking the Pantry banks a supply counter on every counter event and converts two mana into a card. Inspiring Call draws one card per creature with a counter and grants the team indestructible for the turn, which is both the refill and the sweeper answer</td>
</tr>
<tr class="even">
<td>Protection</td>
<td>Take Up the Shield (3), Inspiring Call (2)</td>
<td>Take Up the Shield is a counter plus lifelink plus indestructible for one creature, which is how the deck wins a race or survives a removal spell on the turn it goes for lethal</td>
</tr>
</tbody>
</table>
</section>
<section id="lands-as-engines" class="level2">
<h2 class="anchored" data-anchor-id="lands-as-engines">Lands as engines</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Land</th>
<th>Count</th>
<th>Why it is in the deck</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Restless Prairie</td>
<td>2</td>
<td>The win-condition land. It enters tapped, taps for {G} or {W}, and for {2}{G}{W} it becomes a 3/3 green and white Llama creature that is still a land; whenever it attacks, every other creature you control gets +1/+1 until end of turn. It is a threat that dodges sorcery-speed creature removal and a team pump for the counter creatures at the same time</td>
</tr>
<tr class="even">
<td>Rogue’s Passage</td>
<td>2</td>
<td>The finisher. It taps for {C} and for four mana and a tap it makes target creature unblockable for the turn, so the single largest counter carrier in play connects regardless of the opponent’s board. It is the land that turns an Ouroboroid trigger into damage</td>
</tr>
<tr class="odd">
<td>Terramorphic Expanse</td>
<td>3</td>
<td>One mana, one landfall trigger, one Forest or Plains. With Bristly Bill or Mossborn Hydra in play it is a spell that fixes the mana</td>
</tr>
<tr class="even">
<td>Evolving Wilds</td>
<td>3</td>
<td>The second copy of the same effect, and a different name, which matters because the deck wants a high land count without drawing dead duplicates</td>
</tr>
<tr class="odd">
<td>Promising Vein</td>
<td>2</td>
<td>A Cave that taps for colourless and, for one mana, sacrifices itself for a basic land. Colourless early is fine in a deck that curves Pawpatch Recruit into Bristly Bill, and the fetch mode is another landfall trigger</td>
</tr>
<tr class="even">
<td>Temple of Plenty</td>
<td>2</td>
<td>The only unconditional green and white dual in the base, plus a free scry 1 that helps find the fourth land or the second engine piece</td>
</tr>
<tr class="odd">
<td>Forest</td>
<td>5</td>
<td>Green carries Bristly Bill, Wildwood Scourge, Broodguard Elite, Mossborn Hydra, Pawpatch Recruit, Stocking the Pantry, Training Regimen and Inspiring Call</td>
</tr>
<tr class="even">
<td>Plains</td>
<td>4</td>
<td>White carries Skyknight Squire and Take Up the Shield, and it pays the white half of Caradora, Heart of Alacria. Four Plains plus fetches is enough because only two cards in the deck need white before turn four</td>
</tr>
</tbody>
</table>
</section>
<section id="curve-and-mana" class="level2">
<h2 class="anchored" data-anchor-id="curve-and-mana">Curve and mana</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Mana value</th>
<th>Count</th>
<th>Cards</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One</td>
<td>9</td>
<td>Wildwood Scourge (4), Stocking the Pantry (3), Pawpatch Recruit (2)</td>
</tr>
<tr class="even">
<td>Two</td>
<td>15</td>
<td>Bristly Bill, Spine Sower (4), Broodguard Elite (4), Skyknight Squire (4), Take Up the Shield (3)</td>
</tr>
<tr class="odd">
<td>Three</td>
<td>4</td>
<td>Mossborn Hydra (2), Inspiring Call (2)</td>
</tr>
<tr class="even">
<td>Four</td>
<td>9</td>
<td>Ouroboroid (3), Caradora, Heart of Alacria (3), Training Regimen (3)</td>
</tr>
</tbody>
</table>
<p>Twenty-four of the thirty-seven nonlands cost two or less, and the deck never needs more than four mana for any single card. The two X-spells (Wildwood Scourge and Broodguard Elite) are counted at their minimum in the table and are usually cast for three or four mana once the third land is down. The twenty-three land base holds a four-land-by-turn-four rate of 0.584 with seven fetches, so the deck hits its fourth land on schedule while still triggering landfall on the way.</p>
</section>
</section>
<section id="gameplay-strategy" class="level1">
<h1>Gameplay strategy</h1>
<section id="early-game" class="level2">
<h2 class="anchored" data-anchor-id="early-game">Early game</h2>
<p>Turns one and two are about putting counter sources on the board, not about pressure. Stocking the Pantry on one is the best opening because it converts every later counter event into a card; Pawpatch Recruit on one is the fastest, because a 2/1 trampler that can make a token copy gives Skyknight Squire and Wildwood Scourge two triggers in one card.</p>
<p>Turn two is Bristly Bill whenever the mana allows it. Bristly Bill is the card that makes the fetch lands matter, and it is also the only way the deck doubles the whole board, so it is worth cracking Terramorphic Expanse or Evolving Wilds the same turn to put a counter somewhere immediately. Skyknight Squire on two is the alternative, and it snowballs by itself once the deck starts dropping creatures.</p>
<p>Take Up the Shield is the turn-two play to hold rather than cast: it is a counter, lifelink and indestructible for two mana, and it is nearly always better spent protecting the creature that is about to be pumped than on a 1/1 on turn two.</p>
</section>
<section id="mid-game" class="level2">
<h2 class="anchored" data-anchor-id="mid-game">Mid game</h2>
<p>Turns three to five are about stacking counter events in a single combat rather than deploying one threat at a time.</p>
<p>The highest-value sequence is to land Ouroboroid and then crack a fetch land before the beginning of the next combat. Ouroboroid’s trigger puts X counters on every creature (X equals its power, so one counter per creature on the first combat), the fetch land adds a landfall counter through Bristly Bill or Mossborn Hydra, Caradora makes each of those events one larger, and Wildwood Scourge adds a counter for each non-Hydra creature that received counters. A single combat step with those pieces in play adds four to six counters across the board at a cost of zero cards.</p>
<p>Broodguard Elite is the deck’s insurance policy. Cast for three or four mana it enters as a 3/3 or 4/4 with warp, and if it dies its counters move to another creature, so the investment is never wasted; warping it back later re-triggers the entry. Wildwood Scourge is the other card worth protecting, because every future counter event is worth an extra counter while it is in play.</p>
<p>Do not over-commit into a sweeper. The deck’s answer is Inspiring Call: hold it until the opponent taps out for a board wipe, cast it in response, draw four or five cards and keep every creature with a counter alive for the turn.</p>
</section>
<section id="the-combo-turn" class="level2">
<h2 class="anchored" data-anchor-id="the-combo-turn">The combo turn</h2>
<p>The engine turn needs three things: Ouroboroid in play, at least two other creatures with counters already on them, and a land drop or a fetch land still to use.</p>
<ol type="1">
<li>Start the turn with Ouroboroid and a board of counter carriers. Any Wildwood Scourge or Broodguard Elite counts double for the purposes of the next step.</li>
<li>Beginning of combat: Ouroboroid triggers for X, where X is its power. With Caradora in play every one of those placements becomes X plus one.</li>
<li>Crack a fetch land before the trigger resolves if the mana is open, so Bristly Bill or Mossborn Hydra adds its landfall counter to the same combat. Mossborn Hydra doubling its own counters is the single largest growth event in the deck.</li>
<li>Training Regimen adds one more counter and turns the whole board into tramplers, so the counters convert to damage in the same turn.</li>
<li>Attack with everything. Restless Prairie animates for {2}{G}{W} and pumps the rest of the team by +1/+1 when it attacks, which is the difference between a chump block and lethal.</li>
<li>If one blocker matters, Rogue’s Passage for four mana makes the biggest attacker unblockable, and Take Up the Shield gives it lifelink and indestructible so the swing is safe.</li>
</ol>
<p>A realistic turn five with Ouroboroid, Caradora and Training Regimen in play is six to eight counters on the team plus trample, which is lethal against most boards that do not have a sweeper.</p>
</section>
<section id="win-condition-2" class="level2">
<h2 class="anchored" data-anchor-id="win-condition-2">Win condition 2</h2>
<p>The second path does not need Ouroboroid: it needs counters on creatures that cannot be blocked.</p>
<p>Skyknight Squire is the cheapest route. It gains a counter every time any other creature enters, so a turn of Pawpatch Recruit plus offspring token, a fetch land and a Broodguard Elite takes it past three counters and turns it into a 4/4 or larger flier. Mossborn Hydra is the other: a landfall doubling trigger on top of trample makes it a two-turn clock from three mana, and its counters keep doubling for free as the deck plays lands.</p>
<p>The lands are part of both paths. Restless Prairie attacking gives every other attacker +1/+1, so the Llama is a team pump on a land that survives sorcery-speed removal, and Rogue’s Passage makes whichever of these creatures is largest unblockable. That combination is the deck’s answer to a stalled board: pump the team with the manland, clear the last blocker with the Passage, and attack for the win with counters rather than with card advantage.</p>
</section>
<section id="mulligan-guide" class="level2">
<h2 class="anchored" data-anchor-id="mulligan-guide">Mulligan guide</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 57%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Hand shape</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Two or three lands including a green source, plus Bristly Bill, Spine Sower and any other creature</td>
<td>Keep. This is the engine hand: landfall counters early, Ouroboroid on four</td>
</tr>
<tr class="even">
<td>Two lands, Pawpatch Recruit, Skyknight Squire, Stocking the Pantry</td>
<td>Keep. Three cheap counter sources and a way to turn them into cards</td>
</tr>
<tr class="odd">
<td>Two lands, Ouroboroid, Caradora, Heart of Alacria, plus a fetch land</td>
<td>Keep. The fetch land is the fourth land and a counter event in one card</td>
</tr>
<tr class="even">
<td>Three lands, Wildwood Scourge, Broodguard Elite, Training Regimen</td>
<td>Keep. Two X-spells with a payoff that makes them lethal</td>
</tr>
<tr class="odd">
<td>One land</td>
<td>Mulligan. The deck wants three mana on turn three and four on turn four, and it has no way to recover a missed land drop except the fetches it did not draw</td>
</tr>
<tr class="even">
<td>No green source</td>
<td>Mulligan. Thirty of the thirty-seven nonlands are green or partly green</td>
</tr>
<tr class="odd">
<td>Zero one- and two-mana spells</td>
<td>Mulligan. A hand of four-mana cards cannot start the counter ledger, and the deck has no removal to buy time</td>
</tr>
<tr class="even">
<td>Five lands and Ouroboroid with no other creature</td>
<td>Mulligan. Ouroboroid with X equal to 1 and nothing to pump is a 1/3 that does nothing for two turns</td>
</tr>
</tbody>
</table>
</section>
<section id="key-interactions-and-edge-cases" class="level2">
<h2 class="anchored" data-anchor-id="key-interactions-and-edge-cases">Key interactions and edge cases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 53%">
</colgroup>
<thead>
<tr class="header">
<th>Interaction</th>
<th>Ruling detail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ouroboroid’s X is locked in as the trigger resolves</td>
<td>It puts X counters on each creature, X being its power at that moment. Its own counters arrive with the same instruction, so its power grows every combat and the next trigger is larger</td>
</tr>
<tr class="even">
<td>Caradora, Heart of Alacria adds one per counter event</td>
<td>Any time one or more counters would be put on a creature you control, that many plus one are put on it instead. Ouroboroid’s mass placement counts as one event per creature, and so does a fetch land’s landfall trigger</td>
</tr>
<tr class="odd">
<td>Wildwood Scourge only counts non-Hydra recipients</td>
<td>It is a Hydra itself, so Ouroboroid’s counters on it do not trigger it, but every non-Hydra creature that receives counters does. A mass trigger across four non-Hydra creatures is four separate counters on the Scourge</td>
</tr>
<tr class="even">
<td>Mossborn Hydra doubles only its own counters</td>
<td>Its landfall trigger is “double the number of +1/+1 counters on this creature”, so it does not interact with Caradora for the rest of the team. It does stack with Bristly Bill’s doubling on a later combat</td>
</tr>
<tr class="odd">
<td>Skyknight Squire counts three counters, not three triggers</td>
<td>As long as it has three or more counters total it has flying and is a Knight. Broodguard Elite’s exit trigger and Take Up the Shield both push it over the line without a single landfall trigger</td>
</tr>
<tr class="even">
<td>Broodguard Elite passes counters when it leaves</td>
<td>The counters move to target creature you control, so using it as a chump blocker is a transfer rather than a loss. Its warp {X}{G} lets you recast it later, and the exit trigger fires again if it leaves a second time</td>
</tr>
<tr class="odd">
<td>Pawpatch Recruit’s second ability needs an opponent’s spell</td>
<td>Whenever a creature you control becomes the target of a spell or ability an opponent controls, put a +1/+1 counter on a different creature you control. Point their removal at the Recruit and the counter lands on Mossborn Hydra or Skyknight Squire instead</td>
</tr>
<tr class="even">
<td>The offspring token arrives with the entry trigger</td>
<td>Paying the extra {2} creates the token copy as the Recruit enters, so Skyknight Squire and Wildwood Scourge see two entries, not one</td>
</tr>
<tr class="odd">
<td>Training Regimen triggers every combat, not every turn</td>
<td>A single +1/+1 counter per combat step on a creature you control, and every creature you control with a counter has trample for as long as the enchantment is in play</td>
</tr>
<tr class="even">
<td>Inspiring Call is a draw spell first</td>
<td>It draws for each creature with a counter and only then grants indestructible, so cast it in response to a sweeper with the board already built. Board wipes that exile avoid it, and so do sacrifice effects</td>
</tr>
<tr class="odd">
<td>Take Up the Shield answers removal and wins races</td>
<td>The counter is permanent, the lifelink and indestructible are until end of turn. Cast it on the attacking creature in the turn you go for lethal to gain four or more life and survive the crack back</td>
</tr>
<tr class="even">
<td>Stocking the Pantry tracks events, not counters</td>
<td>One or more counters is one supply counter, so Ouroboroid’s mass trigger adds one supply counter, not five. Each supply counter is two mana for a card at sorcery speed</td>
</tr>
<tr class="odd">
<td>Restless Prairie is a land until end of turn</td>
<td>Animating it does not stop it from being a land, so landfall triggers still fire if it enters after animation, and it keeps tapping for mana. It also counts for Training Regimen because it has counters only if something puts them on it</td>
</tr>
<tr class="even">
<td>Rogue’s Passage ability timing</td>
<td>Four mana and a tap, at sorcery speed in practice because it is an activated ability of a land. Use it in the second main phase before attackers so the mana is not telegraphed, or in the mana you floated for a fetch</td>
</tr>
<tr class="odd">
<td>Fetches enter tapped but trigger landfall immediately</td>
<td>Terramorphic Expanse and Evolving Wilds sacrifice themselves and put the basic in tapped, and the basic entering is what triggers landfall. Promising Vein costs one mana for the same effect on a colourless land</td>
</tr>
</tbody>
</table>
</section>
<section id="matchups" class="level2">
<h2 class="anchored" data-anchor-id="matchups">Matchups</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 62%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Opponent</th>
<th>Plan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aggro, including fliers and lifegain</td>
<td>Race with counters and take the lifelink shield. Take Up the Shield is at its best here: the indestructible block plus four life swings the race by a full turn. Keep Skyknight Squire as a blocker until it has three counters, then race in the air</td>
</tr>
<tr class="even">
<td>Midrange</td>
<td>The best matchup. Midrange gives the deck time to assemble Ouroboroid plus Caradora plus Training Regimen, and a trampling counter board outclasses anything midrange can block. Fetch lands should be saved for the turn of the big attack so the landfall counters arrive with the Ouroboroid trigger</td>
</tr>
<tr class="odd">
<td>Control</td>
<td>The hardest matchup. Play two threats at a time rather than four, keep Stocking the Pantry and Inspiring Call for the turns after a sweeper, and treat Broodguard Elite as the creature that wants to die because its counters move to whatever survived. Restless Prairie dodges creature removal entirely</td>
</tr>
<tr class="even">
<td>Combo</td>
<td>The clock is turn five or six, so spend every card on damage. Rogue’s Passage and Restless Prairie are the cards that end the game through a stalled ground board, and Inspiring Call is the only card worth holding back because it refills after an interaction-heavy turn</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="iterations" class="level1">
<h1>Iterations</h1>
<p>The published list is version three. Version one failed the simulation and synergy gates, version two fixed the simulation with cheaper counter bodies but left cohesion short of the threshold, and version three rebuilt the top of the curve around landfall-fed counter creatures and a fetch-heavy mana base, which cleared both.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 40%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>What changed</th>
<th>Gate results</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v1 (baseline)</td>
<td>26 creatures built around Ouroboroid and Bristly Bill with Innkeeper’s Talent, Daydream, Emil, Vastlands Roamer, Byrke, Long Ear of the Law, Tendril of the Mycotyrant and a nine-tapland green and white base</td>
<td>sim 51.0, synergy 68.69, turn-4 0.579, four lands 0.585 (fail: simulation and synergy)</td>
</tr>
<tr class="even">
<td>v2</td>
<td>-2 Felling Blow, -1 Biosynthic Burst; +2 Ironpaw Aspirant, +1 Warden of the Inner Sky (why: the two removal spells added no counter events, and the one-mana and two-mana counter bodies lift the early clock)</td>
<td>sim 51.0 to 52.0, synergy 68.69 to 68.37, turn-4 0.579 to 0.593, four lands 0.585 to 0.590 (simulation passes, synergy still short)</td>
</tr>
<tr class="odd">
<td>v3 (published)</td>
<td>-3 Innkeeper’s Talent, -3 Creosote Heath, -2 Daydream, -2 Emil, Vastlands Roamer, -2 Byrke, Long Ear of the Law, -2 Ironpaw Aspirant, -2 Warden of the Inner Sky, -2 Tendril of the Mycotyrant, -4 Sunshower Druid, -2 Temple of Plenty, -1 Forest; +4 Wildwood Scourge, +4 Broodguard Elite, +3 Training Regimen, +3 Take Up the Shield, +3 Terramorphic Expanse, +3 Evolving Wilds, +2 Mossborn Hydra, +2 Pawpatch Recruit, +1 Skyknight Squire (why: cohesion was the only failing metric, so the deck swapped off-theme and off-curve cards for counters-plus-landfall pieces that share the matrix, and the cheaper counter carriers kept the simulation rising)</td>
<td>sim 52.0 to 54.0, synergy 68.37 to 70.22, turn-4 0.593 to 0.579, four lands 0.590 to 0.584 — every gate passes</td>
</tr>
</tbody>
</table>
<p>The published 60 cards: no missing names, Standard legal, zero rotating cards, synergy 70.22, turn-4 consistency 0.579, four-land probability 0.584 and a simulation average of 54.0 across the recorded three 500-game runs (59 / 54 / 49).</p>
</section>
<section id="deck-list-arena-import" class="level1">
<h1>Deck list (Arena import)</h1>
<pre class="text"><code>Tallywurm
Deck
4 Bristly Bill, Spine Sower
4 Wildwood Scourge
4 Skyknight Squire
4 Broodguard Elite
3 Ouroboroid
3 Caradora, Heart of Alacria
2 Mossborn Hydra
2 Pawpatch Recruit
3 Stocking the Pantry
3 Training Regimen
3 Take Up the Shield
2 Inspiring Call
3 Terramorphic Expanse
3 Evolving Wilds
2 Promising Vein
2 Temple of Plenty
2 Restless Prairie
2 Rogue's Passage
5 Forest
4 Plains</code></pre>


</section>

</main> <!-- /main -->
<script data-goatcounter="https://th3pajay.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>From th3pajay — a new Standard deck guide every morning</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/th3pajay/mtga-decks">Source on GitHub</a></p>
</div>
  </div>
</footer>




</body></html>