<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-16">

<title>Whiskerquake – MTG Decks — Daily Standard Guides</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a8dd2cfac03084eab458e3b1c626e1f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MTG Decks — Daily Standard Guides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a>
  <ul class="collapse">
  <li><a href="#game-plan-phases" id="toc-game-plan-phases" class="nav-link" data-scroll-target="#game-plan-phases">Game plan phases</a></li>
  <li><a href="#card-roles" id="toc-card-roles" class="nav-link" data-scroll-target="#card-roles">Card roles</a></li>
  <li><a href="#lands-as-engines" id="toc-lands-as-engines" class="nav-link" data-scroll-target="#lands-as-engines">Lands as engines</a></li>
  <li><a href="#curve-and-mana" id="toc-curve-and-mana" class="nav-link" data-scroll-target="#curve-and-mana">Curve and mana</a></li>
  </ul></li>
  <li><a href="#gameplay-strategy" id="toc-gameplay-strategy" class="nav-link" data-scroll-target="#gameplay-strategy">Gameplay strategy</a>
  <ul class="collapse">
  <li><a href="#early-game" id="toc-early-game" class="nav-link" data-scroll-target="#early-game">Early game</a></li>
  <li><a href="#mid-game" id="toc-mid-game" class="nav-link" data-scroll-target="#mid-game">Mid game</a></li>
  <li><a href="#the-combo-turn" id="toc-the-combo-turn" class="nav-link" data-scroll-target="#the-combo-turn">The combo turn</a></li>
  <li><a href="#win-condition-2" id="toc-win-condition-2" class="nav-link" data-scroll-target="#win-condition-2">Win condition 2</a></li>
  <li><a href="#mulligan-guide" id="toc-mulligan-guide" class="nav-link" data-scroll-target="#mulligan-guide">Mulligan guide</a></li>
  <li><a href="#key-interactions-and-edge-cases" id="toc-key-interactions-and-edge-cases" class="nav-link" data-scroll-target="#key-interactions-and-edge-cases">Key interactions and edge cases</a></li>
  <li><a href="#matchups" id="toc-matchups" class="nav-link" data-scroll-target="#matchups">Matchups</a></li>
  </ul></li>
  <li><a href="#iterations" id="toc-iterations" class="nav-link" data-scroll-target="#iterations">Iterations</a></li>
  <li><a href="#deck-list-arena-import" id="toc-deck-list-arena-import" class="nav-link" data-scroll-target="#deck-list-arena-import">Deck list (Arena import)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Whiskerquake</h1>
<p class="subtitle lead">White / Red / Green (three colors) - Valiant Mice meeting Earthbend land-awakening, with a counters bridge between them</p>
  <div class="quarto-categories">
    <div class="quarto-category">combo</div>
    <div class="quarto-category">Valiant</div>
    <div class="quarto-category">Earthbend</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 16, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="at-a-glance" class="level1">
<h1>At a glance</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 61%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Format</td>
<td>Standard (MTGA)</td>
</tr>
<tr class="even">
<td>Colors</td>
<td>White / Red / Green (three colors)</td>
</tr>
<tr class="odd">
<td>Archetype</td>
<td>Aggro-combo - Valiant targeting engine feeding an Earthbend land-creature payoff</td>
</tr>
<tr class="even">
<td>Size</td>
<td>60 cards (37 spells and permanents, 23 lands, average mana value 2.00 across nonlands)</td>
</tr>
<tr class="odd">
<td>Signature mechanics</td>
<td>Valiant (target your own creature each turn) and Earthbend (awaken a land as a hasty creature with +1/+1 counters)</td>
</tr>
<tr class="even">
<td>Primary win</td>
<td>Earthbend: Rockalanche and Ba Sing Se turn lands into hasted creatures carrying four or more +1/+1 counters, Toph, the Blind Bandit’s power equals the counters on your lands, and Knight of Wundagore copies every counter you place elsewhere</td>
</tr>
<tr class="odd">
<td>Secondary win</td>
<td>Valiant: a Mice team (Flowerfoot Swordmaster, Emberheart Challenger, Seedglaive Mentor, Whiskerquill Scribe) that gets paid for every target, with Whiskervale Forerunner putting free creatures onto the battlefield and Secret Tunnel making two of them unblockable</td>
</tr>
<tr class="even">
<td>Land win condition</td>
<td>Secret Tunnel ({4}, {T}: two creatures you control that share a creature type cannot be blocked), Restless Prairie (a 3/3 attacking land that pumps the team), Ba Sing Se and Rockface Village as in-land engines</td>
</tr>
<tr class="odd">
<td>Measured performance</td>
<td>Sim 51.3 percent average over three 500-game runs (gate is 52), turn-4 consistency 0.592, four-land probability by turn 4 of 0.574, synergy 73.5, cohesion 73.5</td>
</tr>
<tr class="even">
<td>Overlap</td>
<td>3 cards previously delivered (Flowerfoot Swordmaster, Emberheart Challenger, Seedglaive Mentor) out of a budget of 12 - spent only because those three are the only Standard Valiant threats outside the four cards this build introduces</td>
</tr>
</tbody>
</table>
</section>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>Whiskerquake is built on a single question: what happens when the deck’s targeting engine and its land-awakening engine are pointed at each other. Valiant rewards a creature the first time each turn it becomes the target of a spell or ability you control. Earthbend targets a land you control, turns it into a 0/0 creature with haste that is still a land, and puts counters on it equal to the earthbend number.</p>
<p>The bridge between the two is counters. Every Earthbend activation places +1/+1 counters on a permanent that is simultaneously a land and a creature, and Knight of Wundagore reads exactly that: whenever you put a +1/+1 counter on another creature, it takes one too, once each turn. Seedglaive Mentor’s Valiant trigger, Claim the Kingdom’s landfall trigger, Snakeskin Veil and the earthbend spells all feed the same clause, so the Knight is usually a 4/3 or 5/4 trampler by turn four without any card being spent on it directly.</p>
<p>The enablers are deliberately repeatable. Adventuring Gear’s equip cost of {1} is a targeting ability, so re-equipping each turn is a Valiant trigger each turn plus +2/+2 from its own landfall clause. Rockface Village gives a Mouse +1/+0 and haste for {R}. Secret Tunnel’s {4}, {T} activation targets two creatures that share a creature type - the Mice - which turns on two Valiant abilities with one activation and clears the way for the attack that matters. Claim the Kingdom and Snakeskin Veil are the one-shot versions, and both leave a counter behind.</p>
<p>Toph, the Blind Bandit is the payoff that ties the two halves together. She earthbends 2 when she enters, and her power equals the number of +1/+1 counters on lands you control - so every Rockalanche, every Ba Sing Se activation and her own enters-the-battlefield trigger makes her larger, and she is a three-drop.</p>
</section>
<section id="approach" class="level1">
<h1>Approach</h1>
<section id="game-plan-phases" class="level2">
<h2 class="anchored" data-anchor-id="game-plan-phases">Game plan phases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>Turns</th>
<th>What the deck is doing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Open</td>
<td>1 to 2</td>
<td>A one-drop and a two-drop, ideally Flowerfoot Swordmaster or Knight of Wundagore, then Emberheart Challenger or Whiskerquill Scribe. Adventuring Gear on turn one is the best opening because every later land drop pumps the equipped creature</td>
</tr>
<tr class="even">
<td>Build</td>
<td>3 to 4</td>
<td>Seedglaive Mentor arrives as a 3/2 with vigilance and haste. Toph, the Blind Bandit earthbends 2 and starts scaling. Claim the Kingdom converts land drops into counters. Re-equip Adventuring Gear every turn to keep a Valiant trigger live</td>
</tr>
<tr class="odd">
<td>Awaken</td>
<td>4 to 6</td>
<td>Rockalanche for X equal to your Forests - usually four or five - makes a land into a 4/4 or 5/5 attacker with haste. Ba Sing Se repeats the effect for {2}{G} every turn. Knight of Wundagore grows off each of these</td>
</tr>
<tr class="even">
<td>Close</td>
<td>5 plus</td>
<td>Secret Tunnel makes two Mice unblockable, Rockface Village grants haste to the last Mouse, Whiskervale Forerunner drops a free creature every turn it is targeted, and the team swings through an empty board</td>
</tr>
</tbody>
</table>
</section>
<section id="card-roles" class="level2">
<h2 class="anchored" data-anchor-id="card-roles">Card roles</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 69%">
</colgroup>
<thead>
<tr class="header">
<th>Role</th>
<th>Cards</th>
<th>What the card actually does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Valiant Mice</td>
<td>Flowerfoot Swordmaster (4), Emberheart Challenger (4), Seedglaive Mentor (4), Whiskerquill Scribe (3), Nettle Guard (2), Whiskervale Forerunner (2)</td>
<td>Each pays off the first time each turn it becomes the target of your spell or ability. Swordmaster pumps every Mouse +1/+0 (and has offspring {2} for a second body), Challenger exiles the top card and lets you play it, Mentor takes a +1/+1 counter, Scribe loots, Guard gains +0/+2, and Forerunner looks at the top five for a creature of mana value 3 or less and puts it onto the battlefield</td>
</tr>
<tr class="even">
<td>Repeatable targeting</td>
<td>Adventuring Gear (3), Rockface Village (1), Secret Tunnel (1), Claim the Kingdom (2)</td>
<td>Gear equips for {1} and gives +2/+2 on every landfall. Rockface Village pays {R} for +1/+0 and haste on a Mouse. Secret Tunnel’s {4}, {T} makes two same-type creatures unblockable. Claim the Kingdom targets a creature you control on every landfall and adds a plan counter, then hands out an indestructible counter on the fourth</td>
</tr>
<tr class="odd">
<td>One-shot targeting</td>
<td>Snakeskin Veil (3), Hard-Hitting Question (2)</td>
<td>Veil is a +1/+1 counter plus hexproof for {G}, so it is both a Valiant trigger and protection. Hard-Hitting Question is a one-mana fight: your creature deals damage equal to its power to a creature or planeswalker you do not control, which is the deck’s cleanest answer to a blocker</td>
</tr>
<tr class="even">
<td>Earthbend engine</td>
<td>Toph, the Blind Bandit (2), Rockalanche (2), Ba Sing Se (2)</td>
<td>Toph earthbends 2 on entry and her power equals the counters on your lands. Rockalanche earthbends X where X is your Forest count and has flashback {5}{G} for a second land creature. Ba Sing Se is a green land whose {2}{G}, {T} ability earthbends 2 at sorcery speed</td>
</tr>
<tr class="odd">
<td>Counters bridge</td>
<td>Knight of Wundagore (4)</td>
<td>A 2/1 trampler for {1}{G} that takes a +1/+1 counter whenever you put one on another creature, once each turn. It is the card that converts every earthbend and every Valiant counter into an extra body’s worth of damage</td>
</tr>
</tbody>
</table>
</section>
<section id="lands-as-engines" class="level2">
<h2 class="anchored" data-anchor-id="lands-as-engines">Lands as engines</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Land</th>
<th>Count</th>
<th>Why it is in the deck</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ba Sing Se</td>
<td>2</td>
<td>Enters untapped if you control a basic land, taps for {G}, and for {2}{G} plus the tap it earthbends 2. This is the land that makes the Earthbend half of the deck a permanent, repeatable engine rather than a one-shot spell</td>
</tr>
<tr class="even">
<td>Secret Tunnel</td>
<td>1</td>
<td>The win-condition land. It taps for {C} and for {4} and the tap it makes two creatures you control that share a creature type unblockable, which is a double Valiant trigger on the Mice and the way the last points of damage get through</td>
</tr>
<tr class="odd">
<td>Rockface Village</td>
<td>1</td>
<td>Taps for {C}, or for {R} restricted to creature spells - it is a real red source in a deck with only four Mountains. Its {R}, {T} activation targets a Lizard, Mouse, Otter or Raccoon for +1/+0 and haste, so it is a recurring Valiant trigger aimed at the Mice</td>
</tr>
<tr class="even">
<td>Restless Prairie</td>
<td>1</td>
<td>Enters tapped, taps for {G} or {W}, and for {2}{G}{W} becomes a 3/3 Llama creature that is still a land. Whenever it attacks, your other creatures get +1/+1, so it is both an attacker and an anthem</td>
</tr>
<tr class="odd">
<td>Forest, Plains, Mountain</td>
<td>8 / 5 / 5</td>
<td>Basics only - the deck is a green base with white and red support. Green has ten sources, white six and red six, with Rockface Village’s restricted red on top</td>
</tr>
</tbody>
</table>
</section>
<section id="curve-and-mana" class="level2">
<h2 class="anchored" data-anchor-id="curve-and-mana">Curve and mana</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Mana value</th>
<th>Count</th>
<th>Cards</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One</td>
<td>12</td>
<td>Flowerfoot Swordmaster (4), Adventuring Gear (3), Snakeskin Veil (3), Hard-Hitting Question (2)</td>
</tr>
<tr class="even">
<td>Two</td>
<td>15</td>
<td>Emberheart Challenger (4), Knight of Wundagore (4), Whiskerquill Scribe (3), Nettle Guard (2), Claim the Kingdom (2)</td>
</tr>
<tr class="odd">
<td>Three</td>
<td>8</td>
<td>Seedglaive Mentor (4), Rockalanche (2), Toph, the Blind Bandit (2)</td>
</tr>
<tr class="even">
<td>Four</td>
<td>2</td>
<td>Whiskervale Forerunner (2)</td>
</tr>
</tbody>
</table>
<p>Average mana value is 2.00 across the 37 nonland cards, and the curve carries no card above four mana. Turn-four consistency is 0.592 and the probability of four lands by turn four is 0.574, both above the 0.55 threshold this build is held to. Because the top of the curve is four, the deck functions on three lands and is happy on four, which is what the one-land-heavy basic manabase is for.</p>
</section>
</section>
<section id="gameplay-strategy" class="level1">
<h1>Gameplay strategy</h1>
<section id="early-game" class="level2">
<h2 class="anchored" data-anchor-id="early-game">Early game</h2>
<p>Turn one is Flowerfoot Swordmaster or Adventuring Gear. The Swordmaster is the better body, the Gear is the better long game: equip is a targeting ability, so from turn two onward it is a Valiant trigger every single turn at the cost of one mana, and its landfall clause gives the equipped creature +2/+2 whenever a land enters, which is every turn in this deck.</p>
<p>Turn two is Knight of Wundagore or Emberheart Challenger. The Knight is the one that compounds - an Earthbend later in the game, a Seedglaive Mentor Valiant trigger, or a Snakeskin Veil all put a counter on it. The Challenger is the one that keeps the hand full: its Valiant trigger exiles the top card and lets you play it, and with Hard-Hitting Question and land drops available it is not unusual to play two cards a turn off it.</p>
<p>Do not sandbag the fight spells. Hard-Hitting Question at one mana is the deck’s answer to the first real blocker, and the creature it targets gets a Valiant trigger on the way through.</p>
</section>
<section id="mid-game" class="level2">
<h2 class="anchored" data-anchor-id="mid-game">Mid game</h2>
<p>Turn three is Seedglaive Mentor or Toph, the Blind Bandit, and this is where the two themes start reinforcing each other. Mentor is a 3/2 with vigilance and haste who takes a +1/+1 counter every turn you target it - typically by re-equipping Adventuring Gear or paying for Rockface Village. Toph earthbends 2 on entry, which makes one land a 2/2 hasty creature, and her power is the number of +1/+1 counters on your lands, so she is a 2/3 that becomes a 3/3, then a 4/3, as the earthbend count climbs.</p>
<p>Claim the Kingdom is the card that most opponents misread. It targets a creature you control on every landfall, so a single land drop per turn is a Valiant trigger plus a counter plus a plan counter, and on the fourth plan counter it sacrifices itself to give a creature an indestructible counter - which should go on whichever creature is carrying Adventuring Gear.</p>
</section>
<section id="the-combo-turn" class="level2">
<h2 class="anchored" data-anchor-id="the-combo-turn">The combo turn</h2>
<p>The engine turn needs a Valiant Mouse, one repeatable targeting source, and an earthbend effect.</p>
<ol type="1">
<li>Play the land for the turn. Adventuring Gear pumps the equipped creature +2/+2 and Claim the Kingdom targets a creature you control for a +1/+1 counter - two triggers, and the Claim target can be a Valiant creature for a third.</li>
<li>Activate Rockface Village for {R} targeting a Mouse: +1/+0 and haste, and the Valiant ability fires. If the Mouse is Flowerfoot Swordmaster, the whole Mice team gets +1/+0.</li>
<li>Cast Rockalanche for {2}{G} with five Forests in play: a land becomes a 5/5 creature with haste that is still a land. Knight of Wundagore takes a counter, and Toph, the Blind Bandit’s power goes up by five.</li>
<li>Activate Ba Sing Se for {2}{G} plus the tap to earthbend 2 again - a second land creature, two more counters on your lands, another Knight trigger, another point of Toph power.</li>
<li>Cast Snakeskin Veil on the attacker you want to keep: a +1/+1 counter, hexproof, and another Valiant trigger.</li>
<li>Activate Secret Tunnel for {4} and the tap to make two Mice unblockable, then attack with the land creatures, the Mice and Restless Prairie, whose attack trigger gives your other creatures +1/+1.</li>
</ol>
<p>Two earthbend activations plus three targeting effects is typically twelve or more points of damage on a board that was two creatures wide at the start of the turn. Sequence matters: do the earthbends and the counter placement first so that Knight of Wundagore and Toph are as large as possible before the unblockable activation decides who attacks.</p>
</section>
<section id="win-condition-2" class="level2">
<h2 class="anchored" data-anchor-id="win-condition-2">Win condition 2</h2>
<p>The Valiant plan does not need a single land to be awakened. Flowerfoot Swordmaster’s Valiant trigger gives every Mouse +1/+0 until end of turn, and with offspring it can put two of itself on the battlefield. Emberheart Challenger trades a target into a card off the top of the library every turn, Whiskerquill Scribe turns a spare card into a fresh one, and Whiskervale Forerunner - itself a 3/4 - puts a creature of mana value 3 or less directly onto the battlefield on every turn it is targeted. Re-equipping Adventuring Gear each turn pays all of those triggers at once, and Secret Tunnel then makes two of them unblockable for the kill.</p>
<p>The Valiant plan is better against a deck with one large blocker that hard-hitting Question cannot reach; the earthbend plan is better against a deck with many small blockers, because a 5/5 hasty land creature does not care about a 2/2.</p>
</section>
<section id="mulligan-guide" class="level2">
<h2 class="anchored" data-anchor-id="mulligan-guide">Mulligan guide</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 57%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Hand shape</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Two lands, a one-drop and a two-drop</td>
<td>Keep. This is the ideal opening for a deck with a 2.00 average mana value</td>
</tr>
<tr class="even">
<td>Two lands, Adventuring Gear and Seedglaive Mentor</td>
<td>Keep. Gear on one, Mentor on three, and every land from then on is a Valiant trigger</td>
</tr>
<tr class="odd">
<td>One land and two three-drops</td>
<td>Mulligan. The deck wins on two lands and three mana, not on one</td>
</tr>
<tr class="even">
<td>Three lands, Knight of Wundagore and Toph, the Blind Bandit</td>
<td>Keep. This is the counters line and it plays out on curve</td>
</tr>
<tr class="odd">
<td>Four lands and no creature</td>
<td>Mulligan. Land count matters, but the deck needs a body to put counters on</td>
</tr>
<tr class="even">
<td>Two lands, Rockalanche and either Valiant Mouse</td>
<td>Keep. Rockalanche for four or five is the fastest path to a lethal attacker</td>
</tr>
</tbody>
</table>
</section>
<section id="key-interactions-and-edge-cases" class="level2">
<h2 class="anchored" data-anchor-id="key-interactions-and-edge-cases">Key interactions and edge cases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 53%">
</colgroup>
<thead>
<tr class="header">
<th>Interaction</th>
<th>Ruling detail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Valiant triggers once per creature per turn</td>
<td>Each Valiant creature has its own trigger, but only the first time that creature is targeted in a turn. Secret Tunnel’s ability targets two creatures, so it fires two different Valiant abilities with one activation - but targeting the same creature twice in a turn does nothing the second time</td>
</tr>
<tr class="even">
<td>Equip is a targeting ability</td>
<td>Re-equipping Adventuring Gear each turn is a Valiant trigger on the creature that receives it. Equip only as a sorcery, so it is a main-phase trigger, not a combat trick</td>
</tr>
<tr class="odd">
<td>Earthbend lands stay lands</td>
<td>The awakened land is still a land, so it counts for Toph, the Blind Bandit’s power and it still taps for mana. If it dies or is exiled it returns to the battlefield tapped, so an earthbend is a permanent upgrade, not a temporary animation</td>
</tr>
<tr class="even">
<td>Earthbend is a 0/0 base plus counters</td>
<td>The land enters as a 0/0 and receives counters equal to the earthbend number. Anything that removes counters or sets base power can shrink it, and a land awakened twice keeps both sets of counters</td>
</tr>
<tr class="odd">
<td>Knight of Wundagore is once per turn</td>
<td>Only the first counter you place on another creature each turn gives the Knight a counter. Place the biggest counter source first - Earthbend 4 or 5 rather than a one-shot Snakeskin Veil</td>
</tr>
<tr class="even">
<td>Toph counts counters on lands, not lands</td>
<td>Her power is the number of +1/+1 counters on lands you control, so one land with five counters makes her a 5/3, and five lands with one counter each does the same thing</td>
</tr>
<tr class="odd">
<td>Claim the Kingdom’s indestructible counter</td>
<td>The fourth plan counter sacrifices the enchantment, and the indestructible counter goes on a target creature you control. Put it on the creature wearing Adventuring Gear so the pump and the protection stay together</td>
</tr>
<tr class="even">
<td>Rockalanche counts Forests, not lands</td>
<td>X is the number of Forests you control, so Rockface Village, Secret Tunnel and Restless Prairie do not add to it. Flashback {5}{G} casts it a second time later, which is the last land creature of the game</td>
</tr>
<tr class="odd">
<td>Hard-Hitting Question targets your creature first</td>
<td>The spell is a fight effect, so the chosen creature needs to survive the exchange. It is best aimed from a boosted Seedglaive Mentor or an earthbent land creature</td>
</tr>
</tbody>
</table>
</section>
<section id="matchups" class="level2">
<h2 class="anchored" data-anchor-id="matchups">Matchups</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 62%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Opponent</th>
<th>Plan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aggro, including fliers and lifegain counters</td>
<td>Race with haste. Seedglaive Mentor and Emberheart Challenger both have haste, the earthbent land creatures have haste, and Nettle Guard plus Snakeskin Veil trade with the first threat. Hard-Hitting Question is the answer to a large lifelinker</td>
</tr>
<tr class="even">
<td>Midrange</td>
<td>The strong matchup. Knight of Wundagore and Toph, the Blind Bandit outscale single large blockers, and Rockalanche’s flashback plus Ba Sing Se keep land creatures arriving after the first wave is answered</td>
</tr>
<tr class="odd">
<td>Control</td>
<td>The weaker matchup. Commit one threat at a time, keep Adventuring Gear as the recurring Valiant trigger, and hold Snakeskin Veil for the removal spell aimed at the largest creature. Emberheart Challenger’s exiled card is the way to keep pressure after a wipe</td>
</tr>
<tr class="even">
<td>Combo</td>
<td>The deck’s clock is turn five or six, so the plan is to attack every turn and force blocks. Secret Tunnel’s unblockable activation is the way through a stalled ground, and Hard-Hitting Question answers any creature that a combo needs on the battlefield</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="iterations" class="level1">
<h1>Iterations</h1>
<p>The list was run through the viability battery three times. Round one missed only the simulation gate; round two lowered the curve with a free-creature engine and one-mana interaction and improved every metric, and rounds three and four tested higher-power packages that scored worse, so the round-two list is the published one.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 40%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>What changed</th>
<th>Gate results</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v1</td>
<td>Baseline: Valiant Mice plus Knight of Wundagore, Nettle Guard, Toph, the Blind Bandit, Badgermole, Adventuring Gear, Snakeskin Veil, Overprotect, Claim the Kingdom, Rockalanche</td>
<td>sim 50.7 (FAIL vs 52), synergy 72.4, turn-4 0.595, four lands 0.594</td>
</tr>
<tr class="even">
<td>v2 (final)</td>
<td>-2 Badgermole, -2 Overprotect; +2 Whiskervale Forerunner, +2 Hard-Hitting Question (why: the two five-drops were the slowest cards in a 2.00 average deck, and one-mana interaction plus a creature that arrives for free on every target is the same engine for less mana)</td>
<td>sim 50.7 to 51.3, synergy 72.4 to 73.5, turn-4 0.595 to 0.592, four lands 0.594 to 0.574</td>
</tr>
<tr class="odd">
<td>v3 (tested, reverted)</td>
<td>-3 Whiskerquill Scribe, -2 Nettle Guard, -3 Adventuring Gear, -2 Hard-Hitting Question, -2 Claim the Kingdom, -2 Toph; +4 Pawpatch Recruit, +3 Bristly Bill, Spine Sower, +3 Erode, +3 Earthbender Ascension (why: swap in the highest-power Standard green and white cards from the current metagame)</td>
<td>sim 50.0, synergy 71.1, turn-4 0.571, four lands 0.559 - worse on every gate, so the round-two list was restored</td>
</tr>
<tr class="even">
<td>v4 (tested, reverted)</td>
<td>Round three plus a three-colour fixer manabase (3 Multiversal Passage, 2 Fabled Passage replacing basics and Ba Sing Se copies)</td>
<td>sim 49.3, synergy 71.4, turn-4 0.583, four lands 0.585 - the fixers cost more tempo than the colour consistency returned</td>
</tr>
</tbody>
</table>
<p>The published list is v2. Size 60 with no missing cards, Standard legal, zero rotating cards, synergy 73.5, turn-4 consistency 0.592 and four-land probability 0.574 all pass. The simulation gate reads 51.3 against a threshold of 52 across three 500-game runs (individual runs 47.0, 55.0, 52.0), which is inside the run-to-run variance of the mirror simulation but is still a miss, so this build ships flagged on that one metric.</p>
</section>
<section id="deck-list-arena-import" class="level1">
<h1>Deck list (Arena import)</h1>
<pre class="text"><code>Whiskerquake
Deck
4 Flowerfoot Swordmaster
4 Emberheart Challenger
4 Seedglaive Mentor
4 Knight of Wundagore
3 Whiskerquill Scribe
2 Nettle Guard
2 Whiskervale Forerunner
2 Toph, the Blind Bandit
3 Adventuring Gear
3 Snakeskin Veil
2 Hard-Hitting Question
2 Claim the Kingdom
2 Rockalanche
8 Forest
5 Plains
5 Mountain
2 Ba Sing Se
1 Rockface Village
1 Secret Tunnel
1 Restless Prairie</code></pre>


</section>

</main> <!-- /main -->
<script data-goatcounter="https://th3pajay.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>From th3pajay — a new Standard deck guide every morning</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/th3pajay/mtga-decks">Source on GitHub</a></p>
</div>
  </div>
</footer>




</body></html>