<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-22">

<title>Sack and Sunder – MTG Decks — Daily Standard Guides</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a8dd2cfac03084eab458e3b1c626e1f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MTG Decks — Daily Standard Guides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a>
  <ul class="collapse">
  <li><a href="#game-plan-phases" id="toc-game-plan-phases" class="nav-link" data-scroll-target="#game-plan-phases">Game plan phases</a></li>
  <li><a href="#card-roles" id="toc-card-roles" class="nav-link" data-scroll-target="#card-roles">Card roles</a></li>
  <li><a href="#lands-as-engines" id="toc-lands-as-engines" class="nav-link" data-scroll-target="#lands-as-engines">Lands as engines</a></li>
  <li><a href="#curve-and-mana" id="toc-curve-and-mana" class="nav-link" data-scroll-target="#curve-and-mana">Curve and mana</a></li>
  </ul></li>
  <li><a href="#gameplay-strategy" id="toc-gameplay-strategy" class="nav-link" data-scroll-target="#gameplay-strategy">Gameplay strategy</a>
  <ul class="collapse">
  <li><a href="#early-game" id="toc-early-game" class="nav-link" data-scroll-target="#early-game">Early game</a></li>
  <li><a href="#mid-game" id="toc-mid-game" class="nav-link" data-scroll-target="#mid-game">Mid game</a></li>
  <li><a href="#the-combo-turn" id="toc-the-combo-turn" class="nav-link" data-scroll-target="#the-combo-turn">The combo turn</a></li>
  <li><a href="#win-condition-2" id="toc-win-condition-2" class="nav-link" data-scroll-target="#win-condition-2">Win condition 2</a></li>
  <li><a href="#mulligan-guide" id="toc-mulligan-guide" class="nav-link" data-scroll-target="#mulligan-guide">Mulligan guide</a></li>
  <li><a href="#key-interactions-and-edge-cases" id="toc-key-interactions-and-edge-cases" class="nav-link" data-scroll-target="#key-interactions-and-edge-cases">Key interactions and edge cases</a></li>
  <li><a href="#matchups" id="toc-matchups" class="nav-link" data-scroll-target="#matchups">Matchups</a></li>
  </ul></li>
  <li><a href="#iterations" id="toc-iterations" class="nav-link" data-scroll-target="#iterations">Iterations</a></li>
  <li><a href="#deck-list-arena-import" id="toc-deck-list-arena-import" class="nav-link" data-scroll-target="#deck-list-arena-import">Deck list (Arena import)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Sack and Sunder</h1>
<p class="subtitle lead">Black / Red / Green (three colors) — Goblin amass sacrifice engine into The Great Goblin burn</p>
  <div class="quarto-categories">
    <div class="quarto-category">hobbit</div>
    <div class="quarto-category">amass</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 22, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="at-a-glance" class="level1">
<h1>At a glance</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 61%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Format</td>
<td>Standard (MTGA)</td>
</tr>
<tr class="even">
<td>Colors</td>
<td>Black / Red / Green (three colors — red in 20 of the 37 nonlands, black in 22, green in 4; hybrid costs on Fearsome Goblin Pair, The Great Goblin and Goblin Plate Mail pay in either black or red)</td>
</tr>
<tr class="odd">
<td>Archetype</td>
<td>Amass Goblins, built as a sacrifice-and-counters engine rather than a curve-out aggro deck</td>
</tr>
<tr class="even">
<td>Size</td>
<td>60 cards (24 creatures, 13 other spells and permanents, 23 lands; average mana value 2.32 across the 37 nonlands)</td>
</tr>
<tr class="odd">
<td>Signature mechanic</td>
<td>Amass Goblins. Every amass is a counter event, every counter event is damage off The Great Goblin, and this list sacrifices its own creatures to buy more of them</td>
</tr>
<tr class="even">
<td>Primary win</td>
<td>The Great Goblin: a 3/2 for {1}{B/R}{B/R} that deals 2 damage to target opponent every time you put one or more counters on a Goblin, Orc or Army you control</td>
</tr>
<tr class="odd">
<td>Secondary win</td>
<td>The Goblin Army itself: one shared token fed by every amass card in the deck, made trampling by Wargling and menacing by Goblin Plate Mail</td>
</tr>
<tr class="even">
<td>Land win condition</td>
<td>Goblin-town — {2}{B}{R}, {T}, sacrifice it: two +1/+1 counters on target Goblin or Orc, which is two damage off The Great Goblin and two power on the Army. Mirkwood is the second: {2}{B}{G}, {T}, sacrifice it for two counters on a Wolf, which is Rhovanion Rampager’s power and therefore the size of the amass trigger it leaves behind when it dies</td>
</tr>
<tr class="odd">
<td>Sacrifice engine</td>
<td>Rhovanion Rampager sacrifices a creature on every attack for counters equal to its power, and turns its own death into an amass of that size. Front Porch Sentries, Stony-Voiced Goblins and Fearsome Goblin Pair are all worth more dead than alive</td>
</tr>
<tr class="even">
<td>Measured performance</td>
<td>Synergy score 72.2, turn-4 consistency 0.571, four-land probability by turn 4 of 0.566, simulation 52.0 percent over three 500-game runs (48 / 57 / 51) on the recorded gate run; repeat runs of the same 60 read 58.0 (60 / 54 / 60) and 50.3 (54 / 49 / 48), so the simulation gate sits inside the run-to-run noise band and every other gate clears its threshold comfortably</td>
</tr>
<tr class="odd">
<td>Set note</td>
<td>The Hobbit (set code hob, 193 cards: 70 common / 55 uncommon / 53 rare / 15 mythic) is Standard legal and lands on Arena 2026-08-14, so the import list below is live from that date onward. Some Hobbit printings still carry an empty arena_id until release</td>
</tr>
</tbody>
</table>
</section>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>Amass Goblins is a strange keyword: it puts +1/+1 counters on an Army you control and makes that Army a Goblin, so the token it creates is the only creature the deck really cares about. The Great Goblin is the reason to build around it. His first ability reads “whenever you put one or more counters on a Goblin, Orc or Army you control, The Great Goblin deals 2 damage to target opponent” — it counts events, not counters. Amass 1 and amass 4 are both 2 damage. That single clause sets the deck’s whole priority order: the cheapest, most repeatable amass wins, and the size of the counters is almost irrelevant.</p>
<p>That is why this build is a sacrifice deck and not an aggro deck. The cheapest repeatable counter events in the set are all attached to creatures that want to die. Fearsome Goblin Pair is a 1/1 for {2}{B/R} that amasses 4 when it dies, which is 2 damage and a 4/4 Army for one card. Rhovanion Rampager is a 3/2 Wolf for {2}{B} that sacrifices another creature every time it attacks for +1/+1 counters equal to that creature’s power — so sacrificing the Pair to the Rampager in the same attack step is a counter event, a death trigger and a 5/4 attacker — and when the Rampager itself dies it amasses X, where X is its power at that moment. A Rampager that ate a four-power creature and then died is amass 7: seven counters on the Army and 2 damage off The Great Goblin.</p>
<p>The rest of the list is built from the cheapest counter events available. Tidings of War is one mana for amass 1, and it flashes back for {3}{R} to amass 3 — a noncreature spell that triggers Bothersome Noisemaker for another amass, which is itself another counter event. Goblin-town Flunkies amasses on entry and has haste. Goblin Plate Mail amasses on entry and then attaches itself to the Army it just made bigger, giving it menace so the counters connect. Goblin-town and Mirkwood do the same job from the mana base, sacrificing themselves for two counters at a time.</p>
<p>Black supplies the grind, red supplies the speed, and green supplies the two cards that make the Army matter in combat: Wargling gives the whole team trample the moment any of your creatures reaches power 4, and Warg Tactics is either a flier answer or a counter plus trample and hexproof on demand. Nothing in the 60 costs more than four mana, and twenty-two of the thirty-seven nonland cards cost two or less.</p>
</section>
<section id="approach" class="level1">
<h1>Approach</h1>
<section id="game-plan-phases" class="level2">
<h2 class="anchored" data-anchor-id="game-plan-phases">Game plan phases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>Turns</th>
<th>What the deck is doing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Open</td>
<td>1 to 2</td>
<td>Tidings of War on one if the hand has it, otherwise Goblin-town Flunkies or Bothersome Noisemaker on two. Amass early and often: the first Army token is the creature every later card grows</td>
</tr>
<tr class="even">
<td>Engine</td>
<td>3 to 4</td>
<td>The Great Goblin converts the counters into damage, and Rhovanion Rampager plus Fearsome Goblin Pair arrive in the same window. From here the deck is sacrificing its own board on purpose</td>
</tr>
<tr class="odd">
<td>Trigger turn</td>
<td>4 to 6</td>
<td>Two or three counter events in one turn: sacrifice the Pair to the Rampager, flash back Tidings of War, cast Rage into the Valley, then crack Goblin-town. Each event is 2 damage and each one leaves the Army larger</td>
</tr>
<tr class="even">
<td>Close</td>
<td>5 plus</td>
<td>The Army is 6/6 or larger, Wargling gives it trample once anything has power 4, and Goblin Plate Mail gives it menace. Games end on Army damage, with the burn as a second clock</td>
</tr>
</tbody>
</table>
</section>
<section id="card-roles" class="level2">
<h2 class="anchored" data-anchor-id="card-roles">Card roles</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 69%">
</colgroup>
<thead>
<tr class="header">
<th>Role</th>
<th>Cards</th>
<th>What the card actually does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Burn payoff</td>
<td>The Great Goblin (3)</td>
<td>The title card: 2 damage to target opponent per counter event on a Goblin, Orc or Army. Also exiles the top card of your library whenever another Goblin, Orc or Army you control dies, and you may play it until the end of your next turn, so the deck’s own sacrifices hand you cards</td>
</tr>
<tr class="even">
<td>Counter engines</td>
<td>Tidings of War (4), Bothersome Noisemaker (3), Goblin-town Flunkies (4), Rage into the Valley (2), Gathering of Darkness (1), Goblin Plate Mail (2)</td>
<td>Tidings of War amasses 1 for {R} and 3 on flashback. Noisemaker amasses 1 on every noncreature spell. Flunkies amasses 1 on entry and attacks the turn it lands. Rage into the Valley draws a card, loses 1 life and amasses 2. Gathering of Darkness rebuys a creature and amasses 3. Plate Mail amasses 1 on entry and attaches to the Army</td>
</tr>
<tr class="odd">
<td>Sacrifice fodder</td>
<td>Fearsome Goblin Pair (4), Front Porch Sentries (3), Stony-Voiced Goblins (2)</td>
<td>The Pair is the cleanest: amass 4 when it dies and nothing else. Front Porch Sentries is a 2/2 for {1}{B} that shrinks a creature when it dies. Stony-Voiced Goblins takes a card out of the opponent’s hand on entry and is then expendable</td>
</tr>
<tr class="even">
<td>Sacrifice outlets</td>
<td>Rhovanion Rampager (3)</td>
<td>Every attack, it may eat another creature for +1/+1 counters equal to that creature’s power, and its death trigger converts its final power into an amass of the same size. It is both the way to kill your own Goblins and the biggest single counter event in the deck</td>
</tr>
<tr class="odd">
<td>Rebuy and recursion</td>
<td>Along the Crooked Way (2), Gathering of Darkness (1), The Great Goblin (3)</td>
<td>Along the Crooked Way returns a creature card from the graveyard to hand on entry and amasses 1 every time a creature card leaves your graveyard — so the return itself is a counter event, and it also gives Goblins and Orcs menace for {1}{B}. Gathering of Darkness rebuys a creature and amasses 3 in one card</td>
</tr>
<tr class="even">
<td>Combat support</td>
<td>Wargling (2), Warg Tactics (2), Goblin Plate Mail (2)</td>
<td>Wargling is a 2/2 for {1}{G} that, once you control anything with power 4 or greater, gives itself +1/+0 and your whole board trample — which a large Army usually is. Warg Tactics destroys a flier or puts a counter on the Army and gives it trample and hexproof. Goblin Plate Mail gives +1/+0 and menace</td>
</tr>
</tbody>
</table>
</section>
<section id="lands-as-engines" class="level2">
<h2 class="anchored" data-anchor-id="lands-as-engines">Lands as engines</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Land</th>
<th>Count</th>
<th>Why it is in the deck</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Goblin-town</td>
<td>2</td>
<td>The win-condition land. It enters tapped, taps for {B} or {R}, and {2}{B}{R} plus the land sacrifices it for two +1/+1 counters on target Goblin or Orc: 2 damage off The Great Goblin, 2 power on the Army, no card spent. It is the deck’s answer to flooding</td>
</tr>
<tr class="even">
<td>Mirkwood</td>
<td>2</td>
<td>The colourless fixer that also plays. It enters tapped and taps for {B} or {G}, and {2}{B}{G} plus the land sacrifices it for two counters on target Bear, Spider or Wolf. Rhovanion Rampager and Wargling are both Wolves, so the counters on the Rampager become 2 points of future amass when it dies, and the counters on Wargling turn on ferocious for the whole team</td>
</tr>
<tr class="odd">
<td>Swamp</td>
<td>9</td>
<td>The largest basic count. Black carries Rampager, Front Porch Sentries, Stony-Voiced Goblins, Rage into the Valley, Along the Crooked Way and Gathering of Darkness, plus the black half of every hybrid cost</td>
</tr>
<tr class="even">
<td>Mountain</td>
<td>6</td>
<td>Red carries Goblin-town Flunkies, Bothersome Noisemaker and Tidings of War, and both halves of the hybrid cards can be paid in red when the Swamps are tied up</td>
</tr>
<tr class="odd">
<td>Forest</td>
<td>4</td>
<td>The green splash: four Forests cover all four green cards (Wargling and Warg Tactics), and only Wargling wants green before turn three</td>
</tr>
</tbody>
</table>
<p>Coloured sources: eight red, thirteen black and six green across the twenty-three lands. Green is deliberately thin, so the two Warg Tactics are held as instants — they are worth playing a turn later rather than colour-screwing the mana base for a two-mana trick. Wargling is the one green card worth fetching for early, because trample is what turns a large Army into a lethal one.</p>
</section>
<section id="curve-and-mana" class="level2">
<h2 class="anchored" data-anchor-id="curve-and-mana">Curve and mana</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Mana value</th>
<th>Count</th>
<th>Cards</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One</td>
<td>4</td>
<td>Tidings of War</td>
</tr>
<tr class="even">
<td>Two</td>
<td>18</td>
<td>Goblin-town Flunkies, Bothersome Noisemaker, Front Porch Sentries, Stony-Voiced Goblins, Wargling, Goblin Plate Mail, Warg Tactics</td>
</tr>
<tr class="odd">
<td>Three</td>
<td>14</td>
<td>Fearsome Goblin Pair, The Great Goblin, Rhovanion Rampager, Rage into the Valley, Along the Crooked Way</td>
</tr>
<tr class="even">
<td>Four</td>
<td>1</td>
<td>Gathering of Darkness</td>
</tr>
</tbody>
</table>
<p>Twenty-two of the thirty-seven nonlands cost two or less and exactly one card costs four, so the deck plays two spells a turn from turn three and never has to choose between its engine and its interaction. The mana base is 23 lands with no colourless utility land that cannot also cast something, which is what keeps the four-land-by-turn-four rate at 0.566 while still supporting three colours.</p>
</section>
</section>
<section id="gameplay-strategy" class="level1">
<h1>Gameplay strategy</h1>
<section id="early-game" class="level2">
<h2 class="anchored" data-anchor-id="early-game">Early game</h2>
<p>The best one-two is Tidings of War into Goblin-town Flunkies or Bothersome Noisemaker. Tidings of War for {R} makes the first Army token, and because amass creates a 0/0 Goblin Army and then puts the counters on it, the token does not die to its own size — it arrives as a 1/1 Goblin. Flunkies then amasses on entry and attacks immediately for 1, and the Noisemaker turns every later cheap spell into another counter event.</p>
<p>Turn three is The Great Goblin whenever possible. He is a 3/2 that blocks, so the turn is not wasted while the board is small, and from the moment he lands every amass in hand is worth 2 damage. If the hand has no Great Goblin, the second-best turn three is Rhovanion Rampager plus a spare one-drop to feed it.</p>
<p>Stony-Voiced Goblins on two is the anti-control opening: a 1/1 that forces a discard is fine to sacrifice later to the Rampager, and taking their sweeper or their answer is worth more than the body.</p>
</section>
<section id="mid-game" class="level2">
<h2 class="anchored" data-anchor-id="mid-game">Mid game</h2>
<p>Turns four to six are about stacking counter events in a single turn rather than deploying one threat at a time.</p>
<p>The core loop is the Rampager and the Pair together. Attack with the Rampager and sacrifice Fearsome Goblin Pair to its attack trigger: the Rampager gets +1/+1 from a 1/1 and the Pair’s death trigger amasses 4, which is 2 damage and a permanently larger Army. Sacrifice something larger — a Plate Mail–equipped Goblin, a Wargling, or anything that has been pumped — and the Rampager grows by that much instead; its own death trigger then amasses that number, so the deck converts any big creature into an Army of the same size.</p>
<p>Along the Crooked Way is the value card that holds the loop together. It returns a creature card from the graveyard to hand when it enters, which is itself a “creature card leaves your graveyard” trigger for amass 1, and the returned creature is a second sacrifice for the Rampager. It also gives Goblins and Orcs menace for {1}{B} to push the Army through a stalled board.</p>
<p>Keep the Army alive. It is one token shared by every amass card in the deck, so losing it resets the clock; that is the main reason the list plays 24 creatures and only 13 nonland support cards.</p>
</section>
<section id="the-combo-turn" class="level2">
<h2 class="anchored" data-anchor-id="the-combo-turn">The combo turn</h2>
<p>The engine turn needs three things: The Great Goblin, an Army (or any Goblin) to receive counters, and a hand or graveyard full of cheap counter events.</p>
<ol type="1">
<li>Start the turn with The Great Goblin and an Army in play. Any amassed Army counts as the Goblin for the counters and as a legal attacker.</li>
<li>Cast Tidings of War for {R}. Amass 1 is 2 damage. Flash it back later for {3}{R} for amass 3, which is 2 more damage off the same card.</li>
<li>Cast Rage into the Valley for {2}{B}: draw a card, lose 1 life, amass 2, 2 damage.</li>
<li>Attack with Rhovanion Rampager, sacrificing whatever is smallest. If the sacrificed creature is Fearsome Goblin Pair, its death trigger amasses 4 — 2 damage — and the Rampager is now a 4/3.</li>
<li>Cast Warg Tactics for {1}{G} targeting the Army: one +1/+1 counter, 2 damage, plus trample and hexproof so the attack connects. Every noncreature spell in this sequence also triggers Bothersome Noisemaker for its own amass and another 2 damage.</li>
<li>Sacrifice Goblin-town for {2}{B}{R}: two more counters, 2 more damage, no card spent.</li>
</ol>
<p>A realistic turn five with both engines in play is 10 to 14 damage that never needed a big creature, on top of an Army that grew by five or more counters.</p>
</section>
<section id="win-condition-2" class="level2">
<h2 class="anchored" data-anchor-id="win-condition-2">Win condition 2</h2>
<p>The Army is the second win condition, and unlike the burn it needs a board rather than a hand. Every amass card in the list feeds the same token, so an Army that has been through a Goblin-town activation, a flashed-back Tidings of War, one Rampager death and a killed Pair is an 8/8 or larger.</p>
<p>Three cards make it lethal rather than merely large. Wargling gives your whole team trample as soon as you control a creature with power 4 or greater, and the Army qualifies on its own. Goblin Plate Mail gives the equipped Army +1/+0 and menace, which forces two blockers. Warg Tactics grants trample and hexproof for a turn. Between them the Army usually cannot be chump-blocked and cannot be targeted.</p>
<p>The third, quiet path is The Great Goblin’s second ability: every time another Goblin, Orc or Army you control dies, he exiles the top card of your library and lets you play it until the end of your next turn. This deck kills its own creatures on purpose, so in a long game the sacrifices are also card advantage, and the cards they find are more cheap counter events.</p>
</section>
<section id="mulligan-guide" class="level2">
<h2 class="anchored" data-anchor-id="mulligan-guide">Mulligan guide</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 57%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Hand shape</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Two or three lands including black or red, plus any two-mana Goblin and a Tidings of War</td>
<td>Keep. This is the engine hand: amass early, The Great Goblin on three, and cheap spells from turn three onward</td>
</tr>
<tr class="even">
<td>Two lands, Goblin-town Flunkies, Fearsome Goblin Pair, Rhovanion Rampager</td>
<td>Keep. Two bodies that want to die and the outlet that kills them</td>
</tr>
<tr class="odd">
<td>Two lands, The Great Goblin, Rage into the Valley, Goblin Plate Mail</td>
<td>Keep. Plate Mail amasses on entry and attaches to the token it makes, so it is a counter event and a threat in one card</td>
</tr>
<tr class="even">
<td>Two lands, Warg Tactics and Wargling with no black source</td>
<td>Borderline keep. Both green cards are fine, but a hand with no black land cannot cast the sacrifice engine</td>
</tr>
<tr class="odd">
<td>One land</td>
<td>Mulligan. The deck wants three mana on turn three and four on turn four, and it has no way to recover a missed land drop</td>
</tr>
<tr class="even">
<td>No black source at all</td>
<td>Mulligan. Rampager, the Pair, the Sentries, Rage into the Valley and Along the Crooked Way are all black</td>
</tr>
<tr class="odd">
<td>Five lands, Gathering of Darkness, Warg Tactics</td>
<td>Mulligan. The deck floods; Goblin-town and Mirkwood are the only lands that do anything on their own, and neither profits from a hand that cannot cast creatures</td>
</tr>
<tr class="even">
<td>Zero counter events</td>
<td>Mulligan. Lands plus Warg Tactics with no amass, no Flunkies and no Great Goblin is a hand that cannot deal damage</td>
</tr>
</tbody>
</table>
</section>
<section id="key-interactions-and-edge-cases" class="level2">
<h2 class="anchored" data-anchor-id="key-interactions-and-edge-cases">Key interactions and edge cases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 53%">
</colgroup>
<thead>
<tr class="header">
<th>Interaction</th>
<th>Ruling detail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>The Great Goblin counts events, not counters</td>
<td>“Whenever you put one or more counters” triggers once no matter how many counters arrive. Fearsome Goblin Pair’s amass 4 is 2 damage, and so is a one-mana Tidings of War</td>
</tr>
<tr class="even">
<td>Amass creates the Army first, then adds the counters</td>
<td>With no Army in play, amass creates a 0/0 black Goblin Army token and then puts the counters on it. The token survives because the counters arrive as part of the same instruction</td>
</tr>
<tr class="odd">
<td>The Army is a Goblin for every other card</td>
<td>Amass makes the token a Goblin, so its counters trigger The Great Goblin, Goblin-town can target it, Plate Mail can attach to it, and it is a legal sacrifice for the Rampager</td>
</tr>
<tr class="even">
<td>The Rampager’s counters use the sacrificed creature’s power</td>
<td>Sacrifice a 4-power creature and the Rampager gets four +1/+1 counters, so it is usually worth feeding it the biggest expendable body rather than the smallest</td>
</tr>
<tr class="odd">
<td>The Rampager’s death trigger reads its power at that moment</td>
<td>Its amass X is the power it had when it died, counters included. A Rampager that ate a 4/4 and then traded is amass 7 — 2 damage and seven counters</td>
</tr>
<tr class="even">
<td>Sacrificing to the Rampager happens during the attack declaration</td>
<td>The trigger occurs when it attacks, before blockers, so the sacrificed creature cannot also block. Do not feed it a creature you needed as a blocker</td>
</tr>
<tr class="odd">
<td>The Great Goblin is legendary</td>
<td>A second copy cannot stay on the battlefield. Play the first and hold the rest; his second ability does not trigger for his own death</td>
</tr>
<tr class="even">
<td>The Great Goblin’s exile-play trigger needs a death</td>
<td>It fires when another Goblin, Orc or Army you control dies, and the card is playable until the end of your next turn. Sacrificing on your own turn and casting the exiled card immediately is legal</td>
</tr>
<tr class="odd">
<td>Along the Crooked Way triggers on any creature card leaving the graveyard</td>
<td>Its own entry trigger returning a creature card to hand counts, so the enchantment amasses 1 the turn it lands. Flashing back Tidings of War does not count — that exiles a sorcery, not a creature card</td>
</tr>
<tr class="even">
<td>The menace ability on Along the Crooked Way costs mana every turn</td>
<td>{1}{B} until end of turn for the whole team. Cast it after blocks are declared in a race, or before attacks when the Army needs to force two blockers</td>
</tr>
<tr class="odd">
<td>Goblin Plate Mail amasses and attaches to the token it makes</td>
<td>The Equipment’s entry trigger amasses 1 and then attaches to that Army, so it is never a dead card with no Goblin in play. Its equip cost is {4}, so the first attachment is the free one that matters</td>
</tr>
<tr class="even">
<td>Tidings of War’s flashback is a different size</td>
<td>Amass 1 when cast from hand, amass 3 when cast from the graveyard for {3}{R}, and it is a noncreature spell either way — so Bothersome Noisemaker amasses 1 on top of it</td>
</tr>
<tr class="odd">
<td>Goblin-town and Mirkwood sacrifice themselves</td>
<td>Both enter tapped and both are cracked for {2} plus a coloured pair of mana. They are the deck’s flood insurance; activating them is a sorcery-speed play, so do it in the second main phase</td>
</tr>
<tr class="even">
<td>Mirkwood can only target a Bear, Spider or Wolf</td>
<td>In this list only Rhovanion Rampager and Wargling qualify. Two counters on the Rampager is 2 extra points of amass when it later dies, and two counters on Wargling turns on ferocious for the whole board</td>
</tr>
<tr class="odd">
<td>Warg Tactics usually wants the counter mode</td>
<td>Destroy target flier is the mode to use against fliers; the counter plus trample and hexproof mode is the one that adds 2 damage through The Great Goblin and pushes the Army through</td>
</tr>
</tbody>
</table>
</section>
<section id="matchups" class="level2">
<h2 class="anchored" data-anchor-id="matchups">Matchups</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 62%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Opponent</th>
<th>Plan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aggro, including fliers and lifegain</td>
<td>Race with the Army and keep one Warg Tactics for the first flier that attacks. The burn plan punishes a deck that spends turns attacking rather than blocking, and Goblin-town adds 2 damage without a card. Trade the small Goblins early so the Army survives</td>
</tr>
<tr class="even">
<td>Midrange</td>
<td>The best matchup. Midrange does not pressure life totals, so The Great Goblin’s triggers accumulate unanswered. Feed the Rampager the largest expendable body, keep the Army back as a blocker until trample is online from Wargling, then attack with an Army that forces two blockers through menace</td>
</tr>
<tr class="odd">
<td>Control</td>
<td>The hardest matchup. Their sweepers kill the Army, so play two threats at a time and keep Along the Crooked Way and Gathering of Darkness as post-sweeper rebuys — each of them is also a counter event. The Great Goblin’s exile-play trigger turns every blocked or sacrificed Goblin into a card</td>
</tr>
<tr class="even">
<td>Combo</td>
<td>The clock is turn five or six. Warg Tactics is the only piece of interaction that matters, so spend every card on damage and point the burn at the player. An Army with trample and menace ends the game faster than most combos assemble if the counter events are stacked in one turn</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="iterations" class="level1">
<h1>Iterations</h1>
<p>The published list was reached by running the viability battery on four versions. Version two fixed the only failing gate and every later round tested worse on the simulation, so version two is the list below.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 40%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>What changed</th>
<th>Gate results</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v1 (baseline)</td>
<td>26 creatures including Dreaded Bat-Cloud (2), Gundabad Opportunist (2) and Snowslope Hunter (2), with two Gathering of Darkness and a 22-land base</td>
<td>sim 54.3, synergy 71.5, turn-4 0.534 (fail vs 0.55), four lands 0.550</td>
</tr>
<tr class="even">
<td>v2 (published)</td>
<td>-2 Dreaded Bat-Cloud, -2 Gundabad Opportunist, -2 Snowslope Hunter, -1 Gathering of Darkness; +3 Bothersome Noisemaker, +1 Front Porch Sentries, +2 Warg Tactics, +1 Forest (why: the five- and four-mana cards were the slowest in a 2.3-average deck, and Noisemaker is the same engine at two mana with a body attached)</td>
<td>sim 54.3 to 52.0, synergy 71.5 to 72.2, turn-4 0.534 to 0.571, four lands 0.550 to 0.566 — every gate passes</td>
</tr>
<tr class="odd">
<td>v3 (tested, reverted)</td>
<td>-2 Stony-Voiced Goblins, -1 Gathering of Darkness, -1 Warg Tactics; +1 The Great Goblin, +2 Bilbo’s Deadly Slice, +1 Quarrel (why: add straight removal to the burn plan)</td>
<td>sim 50.7, synergy 71.8, turn-4 0.589, four lands 0.595 — the two removal spells added no counter events and the simulation dropped below 52, so the round-two list was restored</td>
</tr>
<tr class="even">
<td>v4 (tested, reverted)</td>
<td>-2 Stony-Voiced Goblins, -1 Gathering of Darkness; +1 The Great Goblin, +1 Bothersome Noisemaker, +1 Front Porch Sentries (why: push creature density and cheap amass to the maximum)</td>
<td>sim 51.7, synergy 71.9, turn-4 0.579, four lands 0.587 — better on every deterministic metric than v2 but a worse 3-run simulation average, so v2 was restored</td>
</tr>
</tbody>
</table>
<p>The published list is v2: 60 cards with no missing names, Standard legal, zero rotating cards, synergy 72.2, turn-4 consistency 0.571 and four-land probability 0.566. Repeat runs of the same 60 cards read 58.0 and 50.3 on the simulation, which is the run-to-run spread of the mirror simulation rather than a property of the list — the recorded gate run passed at 52.0 and the deck’s average across three gate runs is 53.4.</p>
</section>
<section id="deck-list-arena-import" class="level1">
<h1>Deck list (Arena import)</h1>
<pre class="text"><code>Sack and Sunder
Deck
4 Goblin-town Flunkies
4 Fearsome Goblin Pair
3 The Great Goblin
3 Rhovanion Rampager
3 Bothersome Noisemaker
3 Front Porch Sentries
2 Stony-Voiced Goblins
2 Wargling
4 Tidings of War
2 Rage into the Valley
2 Along the Crooked Way
2 Goblin Plate Mail
2 Warg Tactics
1 Gathering of Darkness
2 Goblin-town
2 Mirkwood
9 Swamp
6 Mountain
4 Forest</code></pre>


</section>

</main> <!-- /main -->
<script data-goatcounter="https://th3pajay.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>From th3pajay — a new Standard deck guide every morning</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/th3pajay/mtga-decks">Source on GitHub</a></p>
</div>
  </div>
</footer>




</body></html>