<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-17">

<title>Gift Economy – MTG Decks — Daily Standard Guides</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a8dd2cfac03084eab458e3b1c626e1f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MTG Decks — Daily Standard Guides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a>
  <ul class="collapse">
  <li><a href="#game-plan-phases" id="toc-game-plan-phases" class="nav-link" data-scroll-target="#game-plan-phases">Game plan phases</a></li>
  <li><a href="#card-roles" id="toc-card-roles" class="nav-link" data-scroll-target="#card-roles">Card roles</a></li>
  <li><a href="#lands-as-engines" id="toc-lands-as-engines" class="nav-link" data-scroll-target="#lands-as-engines">Lands as engines</a></li>
  <li><a href="#curve-and-mana" id="toc-curve-and-mana" class="nav-link" data-scroll-target="#curve-and-mana">Curve and mana</a></li>
  </ul></li>
  <li><a href="#gameplay-strategy" id="toc-gameplay-strategy" class="nav-link" data-scroll-target="#gameplay-strategy">Gameplay strategy</a>
  <ul class="collapse">
  <li><a href="#early-game" id="toc-early-game" class="nav-link" data-scroll-target="#early-game">Early game</a></li>
  <li><a href="#mid-game" id="toc-mid-game" class="nav-link" data-scroll-target="#mid-game">Mid game</a></li>
  <li><a href="#the-combo-turn" id="toc-the-combo-turn" class="nav-link" data-scroll-target="#the-combo-turn">The combo turn</a></li>
  <li><a href="#win-condition-2" id="toc-win-condition-2" class="nav-link" data-scroll-target="#win-condition-2">Win condition 2</a></li>
  <li><a href="#mulligan-guide" id="toc-mulligan-guide" class="nav-link" data-scroll-target="#mulligan-guide">Mulligan guide</a></li>
  <li><a href="#key-interactions-and-edge-cases" id="toc-key-interactions-and-edge-cases" class="nav-link" data-scroll-target="#key-interactions-and-edge-cases">Key interactions and edge cases</a></li>
  <li><a href="#matchups" id="toc-matchups" class="nav-link" data-scroll-target="#matchups">Matchups</a></li>
  </ul></li>
  <li><a href="#deck-list-arena-import" id="toc-deck-list-arena-import" class="nav-link" data-scroll-target="#deck-list-arena-import">Deck list (Arena import)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Gift Economy</h1>
<p class="subtitle lead">Black / Red / White (three colors) — a Gift build-around that turns every promised gift into a drain trigger</p>
  <div class="quarto-categories">
    <div class="quarto-category">combo</div>
    <div class="quarto-category">gift</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 17, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="at-a-glance" class="level1">
<h1>At a glance</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 61%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Format</td>
<td>Standard (MTGA)</td>
</tr>
<tr class="even">
<td>Colors</td>
<td>Black / Red / White (three colors)</td>
</tr>
<tr class="odd">
<td>Archetype</td>
<td>Midrange combo — Gift spells plus a draw-punishment drain engine</td>
</tr>
<tr class="even">
<td>Size</td>
<td>60 cards (36 spells and permanents, 24 lands, average mana value 2.61 across nonlands)</td>
</tr>
<tr class="odd">
<td>Signature mechanic</td>
<td>Gift: you may promise an opponent a gift as you cast the spell, which makes them draw a card or create a token before the spell’s other effects</td>
</tr>
<tr class="even">
<td>Primary win</td>
<td>Drain engine: Razorkin Needlehead and Scrawling Crawler punish every card the opponent draws, and each promised Gift-a-card spell hands them a card first, so removal doubles as damage</td>
</tr>
<tr class="odd">
<td>Secondary win</td>
<td>Lethal loop: Marauding Blight-Priest plus Bloodthirsty Conqueror loop without end — an opponent losing life makes you gain that much life, and every life gain makes each opponent lose 1 life</td>
</tr>
<tr class="even">
<td>Land win condition</td>
<td>Restless Fortress, the black-white land that becomes a 1/4 Nightmare and drains 2 life from the defending player every time it attacks; Soulstone Sanctuary is the backup 3/3 vigilance attacker</td>
</tr>
<tr class="odd">
<td>Measured performance</td>
<td>Sim 52.3 percent over three 500-game runs (50, 58, 49), turn-4 consistency 0.623, four-land probability by turn 4 of 0.602, synergy 72.04, cohesion 72</td>
</tr>
</tbody>
</table>
</section>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>Gift Economy is built on the one thing the Gift mechanic always does: it pays a cost. Promising a gift means an opponent draws a card or creates a token before the spell’s other effects resolve, and every single Gift card in the deck is a card that would be played anyway — removal, an edict, recursion, a two-card draw spell. The deck simply refuses to pay that cost in a vacuum.</p>
<p>Every promised gift of a card is a draw for the opponent, and that draw is the engine. Razorkin Needlehead deals 1 damage to the opponent each time they draw a card. Scrawling Crawler makes them lose 1 life for the same event and keeps both players’ hands full at every upkeep. Gleaming Splendor turns the opponent’s second draw of a turn into a Treasure token for us. Cast Consumed by Greed with the gift promised and the opponent draws a card first — so the spell is an edict plus 1 or 2 points of drain, and on their own draw step it also pays a Treasure. Seven copies across three Gift spells promise a card, and every one of them is a spell the deck wants to cast anyway.</p>
<p>The other four Gift spells promise a token instead — a tapped Fish, a Food, a Treasure. Those promises cost the opponent nothing in cards, so the drain engine ignores them, but they cost the deck nothing either: Nocturnal Hunger destroys any creature for {2}{B} once the Food is promised and only costs us 2 life when it is not, Parting Gust exiles a creature permanently for {W}{W}, and Blooming Blast adds 3 damage to the controller’s face. In this deck the gift is never the downside it looks like on the card.</p>
<p>The second half of the deck is the life ledger. Sanguine Syphoner drains 1 on every attack. Melancholic Poet drains 1 every time an instant or sorcery targets a creature, which in this list is most of the deck. Marauding Blight-Priest turns every point of life we gain into a point each opponent loses. Bloodthirsty Conqueror refunds us every point of life an opponent loses. Put Blight-Priest and Conqueror together and the ledger never closes: as soon as one life is lost anywhere, the loop runs until the table is dead.</p>
<p><strong>Note on the mechanic:</strong> a promised gift resolves before the rest of the spell, and the word “gift” in the reminder text means exactly the object named — a card (the opponent draws), a tapped 1/1 blue Fish token, a Food token, or a Treasure token. Nothing else changes about the spell, and the promise is always optional, so a Gift spell cast without a promise is just a worse card.</p>
</section>
<section id="approach" class="level1">
<h1>Approach</h1>
<section id="game-plan-phases" class="level2">
<h2 class="anchored" data-anchor-id="game-plan-phases">Game plan phases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>Turns</th>
<th>What the deck is doing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Open</td>
<td>1 to 2</td>
<td>Nothing costs one. Turn two is the engine turn: Razorkin Needlehead as a 2/2 for {R}{R}, Gleaming Splendor as a two-mana enchantment, Sanguine Syphoner as a blocker that drains, or Melancholic Poet in front of a hand full of removal</td>
</tr>
<tr class="even">
<td>Build</td>
<td>3 to 4</td>
<td>Scrawling Crawler, Marauding Blight-Priest and the first Gift spells. Every removal spell is now a drain trigger, and the opponent is drawing into a board they cannot keep up with</td>
</tr>
<tr class="odd">
<td>Drain</td>
<td>4 to 6</td>
<td>Parting Gust and Consumed by Greed clear the way while the opponent loses 2 to 3 life a turn to their own draw steps. Sanguine Syphoner and Marauding Blight-Priest convert attacks and life gain into more damage</td>
</tr>
<tr class="even">
<td>Close</td>
<td>5 plus</td>
<td>Bloodthirsty Conqueror, an active Marauding Blight-Priest, or the attacking Restless Fortress end it. Coiling Rebirth and Dewdrop Cure rebuild the engine after a wipe</td>
</tr>
</tbody>
</table>
</section>
<section id="card-roles" class="level2">
<h2 class="anchored" data-anchor-id="card-roles">Card roles</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 69%">
</colgroup>
<thead>
<tr class="header">
<th>Role</th>
<th>Cards</th>
<th>What the card actually does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Draw-punishment engine</td>
<td>Razorkin Needlehead (4), Scrawling Crawler (3)</td>
<td>Needlehead is a 2/2 for {R}{R} with first strike during your turn that deals 1 damage to an opponent whenever they draw a card. Crawler is a colorless 3/2 artifact creature for {3} that makes each player draw during your upkeep and takes 1 life from an opponent whenever they draw</td>
</tr>
<tr class="even">
<td>Gift-to-Treasure engine</td>
<td>Gleaming Splendor (3)</td>
<td>A two-mana white enchantment that hands us a Treasure token every time an opponent draws their second card in a turn. Its own {2}{W} ability, two target players each draw a card, is both a repeatable way to trigger the rest of the engine and a way to keep our own hand full</td>
</tr>
<tr class="odd">
<td>Gift spells, removal</td>
<td>Parting Gust (4), Nocturnal Hunger (3), Blooming Blast (3), Consumed by Greed (3)</td>
<td>Parting Gust exiles a nontoken creature permanently with a promised Fish, and is a +1/+1 flicker for our own creatures without one. Nocturnal Hunger destroys any creature and only costs life if the Food is not promised. Blooming Blast kills a small creature and adds 3 damage to its controller. Consumed by Greed is an edict that returns a creature card from our graveyard to hand on a promised gift</td>
</tr>
<tr class="even">
<td>Gift spells, recursion and reach</td>
<td>Dewdrop Cure (2), Coiling Rebirth (2), Sazacap’s Brew (2)</td>
<td>Dewdrop Cure returns up to three creatures with mana value 2 or less — the whole engine, including Needlehead and Melancholic Poet — for three mana. Coiling Rebirth reanimates and, with a promised gift, also makes a 1/1 copy of the body if it is not legendary. Sazacap’s Brew discards one and lets a player draw two: point it at the opponent and it is 2 drain triggers plus a Treasure</td>
</tr>
<tr class="odd">
<td>Life ledger</td>
<td>Marauding Blight-Priest (2), Sanguine Syphoner (2), Melancholic Poet (2), Bloodthirsty Conqueror (1)</td>
<td>Blight-Priest converts our life gain into 1 life lost by each opponent. Syphoner drains on every attack. Poet drains on every instant or sorcery that targets a creature. Conqueror is a 5/5 flying deathtouch body that refunds us every point an opponent loses and completes the loop with Blight-Priest</td>
</tr>
</tbody>
</table>
</section>
<section id="lands-as-engines" class="level2">
<h2 class="anchored" data-anchor-id="lands-as-engines">Lands as engines</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Land</th>
<th>Count</th>
<th>Why it is in the deck</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Restless Fortress</td>
<td>2</td>
<td>The win-condition land. It enters tapped and taps for white or black, and for {2}{W}{B} it becomes a 1/4 white and black Nightmare that drains 2 from the defending player and gains us 2 every time it attacks — which is itself a Marauding Blight-Priest trigger and, with Bloodthirsty Conqueror, a refund</td>
</tr>
<tr class="even">
<td>Soulstone Sanctuary</td>
<td>1</td>
<td>Colorless backup attacker: {4} turns it into a 3/3 with vigilance and all creature types. It is the land that keeps attacking after a wipe has taken the creatures</td>
</tr>
<tr class="odd">
<td>Temple of Malice</td>
<td>2</td>
<td>Black-red dual that enters tapped and scries 1, which is one of only seven red sources in the deck</td>
</tr>
<tr class="even">
<td>Temple of Silence</td>
<td>2</td>
<td>Black-white dual that enters tapped and scries 1; the scry is how the deck digs for a missing engine piece in the first four turns</td>
</tr>
<tr class="odd">
<td>Bleachbone Verge</td>
<td>2</td>
<td>Black always, white once a Plains or Swamp is down, which is usually turn two</td>
</tr>
<tr class="even">
<td>Plains, Swamp, Mountain</td>
<td>5 / 5 / 5</td>
<td>Basics. Fifteen basics are deliberate: the deck plays scry lands and one colorless utility land, so it wants its first four land drops to be untapped and on colour</td>
</tr>
</tbody>
</table>
<p>Coloured sources: thirteen black, eleven white including the two conditional white sources on Bleachbone Verge, seven red. Black is the deepest colour and carries the win condition; red is the splash that pays for Razorkin Needlehead, Blooming Blast and Sazacap’s Brew, and the four copies of a {R}{R} two-drop are the reason the two Temples of Malice are in the manabase.</p>
</section>
<section id="curve-and-mana" class="level2">
<h2 class="anchored" data-anchor-id="curve-and-mana">Curve and mana</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Mana value</th>
<th>Count</th>
<th>Cards</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One</td>
<td>0</td>
<td>none — the deck starts at two</td>
</tr>
<tr class="even">
<td>Two</td>
<td>22</td>
<td>Razorkin Needlehead, Melancholic Poet, Sanguine Syphoner, Gleaming Splendor, Parting Gust, Blooming Blast, Sazacap’s Brew</td>
</tr>
<tr class="odd">
<td>Three</td>
<td>10</td>
<td>Scrawling Crawler, Marauding Blight-Priest, Nocturnal Hunger, Consumed by Greed, Dewdrop Cure</td>
</tr>
<tr class="even">
<td>Four</td>
<td>0</td>
<td>none</td>
</tr>
<tr class="odd">
<td>Five</td>
<td>3</td>
<td>Bloodthirsty Conqueror, Coiling Rebirth</td>
</tr>
</tbody>
</table>
<p>There is no one-drop and no four-drop, which is the shape of a deck whose turn two is the engine and whose turn three is interaction. Two mana holds twenty-two of the thirty-six nonlands, and the average nonland mana value is 2.61, well under the four-mana ceiling the build is held to. Twenty-four lands is deliberate: four-land probability by turn four is 0.602 and turn-four consistency 0.623, and the deck genuinely wants the fourth land so that Coiling Rebirth or Consumed by Greed plus a promise can be cast on curve.</p>
</section>
</section>
<section id="gameplay-strategy" class="level1">
<h1>Gameplay strategy</h1>
<section id="early-game" class="level2">
<h2 class="anchored" data-anchor-id="early-game">Early game</h2>
<p>Turns one and two are for the engine, not for damage. Razorkin Needlehead is the best turn-two play in the deck because it turns every later Gift spell into damage, but Gleaming Splendor is the more important one against anything slow: it starts paying Treasures the moment the opponent’s draw step plus any gift draw makes two cards, and the Treasures are what pay for the three- and five-mana halves of the deck.</p>
<p>Do not cast removal without the gift. Parting Gust without a promise is a temporary exile that gives the creature back with a +1/+1 counter; with the promise it exiles the creature forever, and if Needlehead or Crawler is out the card the opponent draws costs them 1 or 2 life. The same logic applies to Nocturnal Hunger, which only makes us lose 2 life when the Food is not promised, and to Blooming Blast, which loses 3 points of reach without its Treasure.</p>
<p>Sanguine Syphoner is the safest turn-two body: a 1/3 that drains on every attack and survives most one- and two-mana removal. Melancholic Poet, on the other hand, is a 2/2 that should be played on a turn when a Parting Gust, Nocturnal Hunger or Blooming Blast is already in hand, because otherwise it does nothing.</p>
</section>
<section id="mid-game" class="level2">
<h2 class="anchored" data-anchor-id="mid-game">Mid game</h2>
<p>Turn three is when the drain engine starts compounding. Scrawling Crawler draws both players a card in the upkeep, taking 1 life off the opponent, and then any Gift-a-card spell that turn takes another 1 or 2 and hands us a Treasure from Gleaming Splendor. A turn of Crawler, Consumed by Greed with the gift promised and a Melancholic Poet trigger is 4 points of life loss and a creature sacrificed, from three cards.</p>
<p>The board is meant to be small. Marauding Blight-Priest is a 3/2 that exists only for its trigger; Sanguine Syphoner attacks every turn whether or not it can be blocked. What matters is that the opponent keeps drawing: their draw step, our Gift spells, Scrawling Crawler’s upkeep trigger and Gleaming Splendor’s {2}{W} ability all feed the same three payoffs, so the deck is never short of triggers, only of cards — which is why the Splendor ability targeting us and the opponent at once is almost always correct in the mid game.</p>
<p>Dewdrop Cure is the engine’s reset button. With the gift promised it returns up to three creatures with mana value 2 or less, which is Razorkin Needlehead, Melancholic Poet and Sanguine Syphoner in one card. Against a wipe, that is the play that decides whether the deck still has a game.</p>
</section>
<section id="the-combo-turn" class="level2">
<h2 class="anchored" data-anchor-id="the-combo-turn">The combo turn</h2>
<p>The kill turn is either a drain turn or the loop.</p>
<ol type="1">
<li>Get Marauding Blight-Priest and Bloodthirsty Conqueror onto the board at the same time. The loop is mandatory on both sides: an opponent losing life makes Conqueror gain us that much life, and every life gain makes Blight-Priest drain each opponent for 1. One point of life loss anywhere — a Needlehead ping, a Syphoner attack, a Restless Fortress swing, one damage from Blooming Blast — and the drain repeats without end.</li>
<li>If the loop pieces are not both available, drain instead: play two Gift-a-card spells in one turn with Needlehead and Crawler on the board. Each promised gift is a draw, and each draw is 2 life — 1 from Needlehead and 1 from Crawler — so two gifts plus the opponent’s own draw step is 6 life, and Scrawling Crawler’s upkeep trigger makes it 8. Blooming Blast adds 3 more to a creature controller’s face.</li>
<li>Attack with Restless Fortress activated for {2}{W}{B}. The attacking Nightmare drains 2 from the defending player and gains us 2, which triggers Blight-Priest for 1 more to each opponent.</li>
<li>Hold Parting Gust for the turn the opponent commits their best creature. With the Fish promised it exiles it permanently for two mana, and the Fish token is the cheapest gift in the deck because it costs the opponent no cards.</li>
</ol>
</section>
<section id="win-condition-2" class="level2">
<h2 class="anchored" data-anchor-id="win-condition-2">Win condition 2</h2>
<p>The deck also wins with creatures, and that plan needs no loop: Sanguine Syphoner drains on every attack, Melancholic Poet drains on every removal spell, Restless Fortress attacks as a 1/4 that drains 2, and Soulstone Sanctuary becomes a 3/3 vigilant attacker out of spare mana. Against a deck that removes the engine, keep attacking with whatever survives and let the split damage from attacks, drain triggers and the Restless Fortress activation add up.</p>
<p>Coiling Rebirth is the bridge between the two plans. Reanimating a Bloodthirsty Conqueror with the gift promised returns a 5/5 flying deathtouch body plus a 1/1 copy of it, which is two Conqueror triggers on the stack and two attack steps from one card. Reanimating a Scrawling Crawler after a wipe restarts the draw engine immediately.</p>
</section>
<section id="mulligan-guide" class="level2">
<h2 class="anchored" data-anchor-id="mulligan-guide">Mulligan guide</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 57%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Hand shape</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Two lands, Razorkin Needlehead and any Gift spell</td>
<td>Keep. This is the deck’s ideal opening: the engine online on turn two with a way to fire it</td>
</tr>
<tr class="even">
<td>Two lands, Gleaming Splendor and two black removal spells</td>
<td>Keep. The Splendor pays for the rest and the removal is drain once anything is on the board</td>
</tr>
<tr class="odd">
<td>One land, any hand</td>
<td>Mulligan. The deck has no one-drop and needs three mana before the drain plan is worth anything</td>
</tr>
<tr class="even">
<td>Four lands, Dewdrop Cure, Coiling Rebirth, Scrawling Crawler</td>
<td>Keep. Crawler restarts the engine and the recursion spells mean the first wipe is survivable</td>
</tr>
<tr class="odd">
<td>Five lands, Bloodthirsty Conqueror, Coiling Rebirth</td>
<td>Mulligan. Two five-drops in the opener without an engine is a hand that loses to its own curve</td>
</tr>
<tr class="even">
<td>Two lands, but only one colour of source in hand</td>
<td>Mulligan. Black is the deepest colour but Razorkin Needlehead wants two red, so an opener with no black source is the one to send back</td>
</tr>
</tbody>
</table>
</section>
<section id="key-interactions-and-edge-cases" class="level2">
<h2 class="anchored" data-anchor-id="key-interactions-and-edge-cases">Key interactions and edge cases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 53%">
</colgroup>
<thead>
<tr class="header">
<th>Interaction</th>
<th>Ruling detail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>The gift resolves before the spell</td>
<td>A promised gift happens first, so the opponent draws (or makes the token) before the spell’s main effect. Parting Gust’s exile and Consumed by Greed’s edict still happen after the gift draw, and the draw can never take the target away because the gift is not a spell the opponent controls</td>
</tr>
<tr class="even">
<td>Gift is optional and the word means exactly what it says</td>
<td>Gift a card means the opponent draws a card. Gift a tapped Fish, Gift a Food and Gift a Treasure create those tokens for them. Of the seven Gift spells in the deck only Consumed by Greed, Dewdrop Cure and Coiling Rebirth promise a card, so only those three feed Razorkin Needlehead and Scrawling Crawler</td>
</tr>
<tr class="odd">
<td>Needlehead triggers on any draw</td>
<td>Razorkin Needlehead does not care whose turn it is or why the card was drawn — the opponent’s own draw step counts, so the engine deals damage every turn even when the deck casts nothing</td>
</tr>
<tr class="even">
<td>Gleaming Splendor counts draws, not turns</td>
<td>It triggers on the opponent’s second card drawn in a single turn. A Scrawling Crawler upkeep draw plus a promised Consumed by Greed on the same turn is exactly two, which is a Treasure. Two Splendors make two Treasures</td>
</tr>
<tr class="odd">
<td>Melancholic Poet’s repartee</td>
<td>It needs an instant or sorcery that targets a creature, and it triggers on the cast, not the resolution, so a Gift spell cast into a counterspell still drains 1 and gains us 1</td>
</tr>
<tr class="even">
<td>Marauding Blight-Priest plus Bloodthirsty Conqueror</td>
<td>Both triggers are mandatory and neither is a may, so once one point of life is lost by an opponent the loop cannot be stopped. The loop needs both permanents in play; it does not need a Gift spell or an attack to start, and Scrawling Crawler’s upkeep trigger is enough to begin it</td>
</tr>
<tr class="odd">
<td>Nocturnal Hunger without the gift</td>
<td>Destroying a creature without promising the Food costs us 2 life. In races, that is sometimes correct — but the Food costs nothing and only ever gains the opponent 3 life, so promise it</td>
</tr>
<tr class="even">
<td>Parting Gust on our own creatures</td>
<td>With no gift promised, the exiled creature returns at the beginning of the next end step with a +1/+1 counter, which is a way to reset a Razorkin Needlehead that has been hit by a -3/-3 effect or to re-trigger nothing at all. Its real value against our own board is protection from a sorcery-speed wipe</td>
</tr>
<tr class="odd">
<td>Coiling Rebirth’s copy</td>
<td>The 1/1 token copy only appears if the gift was promised and the returned creature is not legendary, which is why the deck runs no legends. Copying a Scrawling Crawler doubles the upkeep draw and both drain triggers</td>
</tr>
<tr class="even">
<td>Restless Fortress activation timing</td>
<td>It is an activated ability, so it can be used after blockers are declared. The 2 life loss is the defending player’s, and the 2 life gained is ours, which is one Blight-Priest trigger whether it connects or not</td>
</tr>
<tr class="odd">
<td>Soulstone Sanctuary’s mana</td>
<td>It taps for colorless. Treat it as a spell land, not a source for a colored spell, and count it only when the deck has four lands and spare mana</td>
</tr>
</tbody>
</table>
</section>
<section id="matchups" class="level2">
<h2 class="anchored" data-anchor-id="matchups">Matchups</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 62%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Opponent</th>
<th>Plan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aggro, including fliers and lifegain counters</td>
<td>Race the drain rather than the board. Nocturnal Hunger and Parting Gust with the promised gift kill the biggest threat outright, Sanguine Syphoner blocks and drains, and the deck’s damage comes from their own draw steps, so it wins with almost no attackers. Bloodthirsty Conqueror is the card that ends these games: every point they take is a point we gain</td>
</tr>
<tr class="even">
<td>Midrange</td>
<td>The strong matchup. Every removal spell two-for-ones against a curve of expensive threats because the gift’s only drawback is a card the opponent draws into a Needlehead ping, and Consumed by Greed forces the sacrifice of their largest creature. Board the drain plan first, keep the loop as the closer</td>
</tr>
<tr class="odd">
<td>Control</td>
<td>The weak matchup. Wipes do remove the engine, so keep Dewdrop Cure for after the first wipe and do not over-commit the enchantments: one Gleaming Splendor plus one Needlehead is enough pressure to force a wipe, and Scrawling Crawler refills the hand afterwards. The loop is the way through countermagic, because it needs only two permanents already in play</td>
</tr>
<tr class="even">
<td>Combo</td>
<td>Faster combo decks are the real problem, because this deck’s clock is turn five or six. The interaction is Parting Gust and Nocturnal Hunger, both of which should be held for the turn the opponent commits, plus Blooming Blast’s 3 damage to a controller’s face as reach. Melancholic Poet drains while the removal is spent, which is what closes these games</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="deck-list-arena-import" class="level1">
<h1>Deck list (Arena import)</h1>
<pre class="text"><code>Gift Economy
Deck
4 Razorkin Needlehead
3 Scrawling Crawler
2 Melancholic Poet
2 Sanguine Syphoner
2 Marauding Blight-Priest
1 Bloodthirsty Conqueror
3 Gleaming Splendor
4 Parting Gust
3 Nocturnal Hunger
3 Blooming Blast
3 Consumed by Greed
2 Dewdrop Cure
2 Sazacap's Brew
2 Coiling Rebirth
2 Temple of Malice
2 Temple of Silence
2 Bleachbone Verge
2 Restless Fortress
1 Soulstone Sanctuary
5 Plains
5 Swamp
5 Mountain</code></pre>


</section>

</main> <!-- /main -->
<script data-goatcounter="https://th3pajay.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>From th3pajay — a new Standard deck guide every morning</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/th3pajay/mtga-decks">Source on GitHub</a></p>
</div>
  </div>
</footer>




</body></html>