<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-06">

<title>Cold Case Haunting – MTG Decks — Daily Standard Guides</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a8dd2cfac03084eab458e3b1c626e1f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MTG Decks — Daily Standard Guides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a></li>
  <li><a href="#gameplay-strategy" id="toc-gameplay-strategy" class="nav-link" data-scroll-target="#gameplay-strategy">Gameplay strategy</a></li>
  <li><a href="#iterations" id="toc-iterations" class="nav-link" data-scroll-target="#iterations">Iterations</a></li>
  <li><a href="#deck-list-arena-import" id="toc-deck-list-arena-import" class="nav-link" data-scroll-target="#deck-list-arena-import">Deck list (Arena import)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Cold Case Haunting</h1>
<p class="subtitle lead">WUBRG (five-color) | Eerie x Clue</p>
  <div class="quarto-categories">
    <div class="quarto-category">combo</div>
    <div class="quarto-category">Eerie</div>
    <div class="quarto-category">Clue</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 6, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="at-a-glance" class="level2">
<h2 class="anchored" data-anchor-id="at-a-glance">At a glance</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td>Format</td>
<td>Standard</td>
</tr>
<tr class="even">
<td>Colors</td>
<td>WUBRG (five-color; Esper-weighted manabase with red and green splashes)</td>
</tr>
<tr class="odd">
<td>Archetype</td>
<td>Enchantment-storm combo / value</td>
</tr>
<tr class="even">
<td>Size</td>
<td>60 cards (33 spells, 27 lands)</td>
</tr>
<tr class="odd">
<td>Primary win</td>
<td>Eerie chain: every enchantment that enters drains (Balemurk Leech), draws (Entity Tracker), and makes flyers (Ghostly Dancers, Gremlin Tamer)</td>
</tr>
<tr class="even">
<td>Secondary win</td>
<td>Poison: Persuasive Interrogators turns Clue sacrifices into 2 poison counters each (10 poison wins)</td>
</tr>
</tbody>
</table>
</section>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>“Cold Case Haunting” fuses two Standard mechanics into one engine. <strong>Eerie</strong> (Duskmourn) rewards every enchantment that enters under your control; <strong>Clue</strong> (Murders at Karlov Manor and friends) rewards making, cracking, and sacrificing artifact tokens. The bridge cards do both at once: Case of the Filched Falcon is an enchantment that makes a Clue on entry, Curious Inquiry is an Aura that investigates on combat damage, and Teysa, Opulent Oligarch converts opponent life loss into Clues and Clues into flying Spirits.</p>
<p>The game plan is an enchantment snowball. Play eerie creatures early, then chain cheap enchantments (Cases, Auras, Rooms, enchantment creatures) so each entry triggers every eerie payoff. Clues smooth the draws, keep the chain going, and feed the alternate poison kill. Rooms are the premium fuel because a single Room can produce two or three eerie events: entering, making a Glimmer enchantment-creature token, and unlocking its second door.</p>
<p>The deck plays the full rolled color set WUBRG. Fetch lands and They Went This Way (itself a Clue maker) fix the five-color manabase; red arrives via Infernal Phantom, an eerie payoff that turns into reach.</p>
</section>
<section id="approach" class="level2">
<h2 class="anchored" data-anchor-id="approach">Approach</h2>
<section id="game-plan-by-phase" class="level3">
<h3 class="anchored" data-anchor-id="game-plan-by-phase">Game plan by phase</h3>
<ol type="1">
<li><strong>Setup (turns 1-3).</strong> Deploy eerie payoffs: Balemurk Leech, Entity Tracker, Gremlin Tamer, Teysa. Cast Case of the Filched Falcon for an early Clue and its eerie trigger. Curious Inquiry on a flier starts the Clue economy.</li>
<li><strong>Engine (turns 4-5).</strong> Land Ghostly Dancers or Fear of Infinity. Start chaining enchantments: each one makes a 3/1 Spirit (Dancers), drains 1 per Leech, draws a card per Tracker, and makes a Gremlin per Tamer.</li>
<li><strong>Combo turn.</strong> With two or more eerie payoffs in play, cast several enchantments in one turn. Grand Entryway counts twice on its own (entry plus its Glimmer token); unlocking Elegant Rotunda adds a third event plus +1/+1 counters. Crack Clues between spells to keep the chain fueled.</li>
<li><strong>Finish.</strong> Drain plus a flying swarm closes the game. If the opponent races ahead on life, pivot to poison: Persuasive Interrogators plus five Clue sacrifices ends the game regardless of life totals.</li>
</ol>
</section>
<section id="card-roles" class="level3">
<h3 class="anchored" data-anchor-id="card-roles">Card roles</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Card</th>
<th>Cost</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Balemurk Leech</td>
<td>{1}{B}</td>
<td>Core eerie payoff; each enchantment entry deals 1 damage per Leech</td>
</tr>
<tr class="even">
<td>Entity Tracker</td>
<td>{2}{U}</td>
<td>Flash eerie draw engine</td>
</tr>
<tr class="odd">
<td>Ghostly Dancers</td>
<td>{3}{W}{W}</td>
<td>Makes a 3/1 flying Spirit per enchantment entry; recurs enchantments from the graveyard</td>
</tr>
<tr class="even">
<td>Fear of Infinity</td>
<td>{1}{U}{B}</td>
<td>Enchantment creature; eerie returns it from the graveyard to hand, so it keeps re-entering</td>
</tr>
<tr class="odd">
<td>Gremlin Tamer</td>
<td>{W}{U}</td>
<td>1/1 Gremlin per enchantment entry</td>
</tr>
<tr class="even">
<td>Teysa, Opulent Oligarch</td>
<td>{1}{W}{B}</td>
<td>End-step investigate after opponent life loss; Clue dying makes a 1/1 flying Spirit</td>
</tr>
<tr class="odd">
<td>Infernal Phantom</td>
<td>{3}{R}</td>
<td>Eerie gives +2/+0; dying deals damage equal to its power</td>
</tr>
<tr class="even">
<td>Persuasive Interrogators</td>
<td>{4}{B}{B}</td>
<td>Alt-win; every Clue sacrificed gives 2 poison</td>
</tr>
<tr class="odd">
<td>Case of the Filched Falcon</td>
<td>{U}</td>
<td>Fusion card: enchantment entry plus a Clue; solved, it animates an artifact into a flying Bird</td>
</tr>
<tr class="even">
<td>Curious Inquiry</td>
<td>{U}</td>
<td>Aura that investigates on combat damage</td>
</tr>
<tr class="odd">
<td>Grand Entryway // Elegant Rotunda</td>
<td>{1}{W}</td>
<td>Room: entry unlocks a door (1/1 Glimmer enchantment token = extra eerie event); unlock the other half later for counters and a full-unlock eerie trigger</td>
</tr>
<tr class="even">
<td>They Went This Way</td>
<td>{2}{G}</td>
<td>Fetches any basic (fixing) and makes a Clue</td>
</tr>
<tr class="odd">
<td>No Witnesses</td>
<td>{2}{W}{W}</td>
<td>Wipe that investigates if you control the most creatures</td>
</tr>
</tbody>
</table>
</section>
<section id="lands-as-engines" class="level3">
<h3 class="anchored" data-anchor-id="lands-as-engines">Lands as engines</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Land</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rogue’s Passage</td>
<td>Win-condition land: makes the solved Falcon Bird (a 4/4 flying Bird made from a Clue) or another large flier unblockable to close the game</td>
</tr>
<tr class="even">
<td>Fountainport</td>
<td>Sacrifice a token such as a Clue to draw; also makes Fish and Treasure tokens for the Falcon solve count</td>
</tr>
<tr class="odd">
<td>Evolving Wilds / Terramorphic Expanse</td>
<td>Fetch any of the five basics for the WUBRG manabase</td>
</tr>
</tbody>
</table>
</section>
<section id="curve-and-mana" class="level3">
<h3 class="anchored" data-anchor-id="curve-and-mana">Curve and mana</h3>
<p>27 lands: 23 basics across all five colors (7 Island, 7 Plains, 5 Swamp, 2 Forest, 2 Mountain) plus Rogue’s Passage, Fountainport, and two fetch lands. Average mana value is about 2.9. Early spells are single-pip and blue-white heavy; the red and green cards arrive from turn 3 onward, enabled by fetch lands and They Went This Way.</p>
</section>
</section>
<section id="gameplay-strategy" class="level2">
<h2 class="anchored" data-anchor-id="gameplay-strategy">Gameplay strategy</h2>
<section id="early-game" class="level3">
<h3 class="anchored" data-anchor-id="early-game">Early game</h3>
<p>Prioritize an eerie creature over a lone enchantment: payoffs first, fuel second. Leech on turn 2 then a Falcon or Inquiry on turn 3 already drains for 1 and draws a card. Teysa rewards any damage Leech or the Falcon Bird deals. Hold fetch lands until you know which color the hand needs.</p>
</section>
<section id="mid-game" class="level3">
<h3 class="anchored" data-anchor-id="mid-game">Mid game</h3>
<p>Get a second eerie payoff down before chaining multiple enchantments in one turn. Fear of Infinity is best in the graveyard: every enchantment entry returns it to hand, so recasting it is another enchantment entry plus a 2/2 flying lifelink attacker. Ghostly Dancers doubles as recursion, pulling back a Falcon or Inquiry to cast again.</p>
</section>
<section id="the-combo-turn" class="level3">
<h3 class="anchored" data-anchor-id="the-combo-turn">The combo turn</h3>
<p>A typical kill turn with two Leeches, one Dancers, and one Tracker: cast Grand Entryway (drain 2, draw 1, Spirit, Glimmer), cast Case of the Filched Falcon (drain 2, draw 1, Spirit, Clue), unlock Elegant Rotunda (drain 2, draw 1, Spirit, counters), then crack the Clue to draw into more enchantments. Four to five entries in a turn is 8 to 10 damage from Leeches alone, plus a growing flying army. Cracked Clues also trigger Teysa Spirits and Interrogators poison.</p>
</section>
<section id="win-condition-2-poison" class="level3">
<h3 class="anchored" data-anchor-id="win-condition-2-poison">Win condition 2: poison</h3>
<p>Persuasive Interrogators turns the Clue economy into an alternative kill that ignores life totals and lifegain. Each Clue sacrificed (for {1} via the normal draw activation, or through Fountainport) deals 2 poison; five sacrifices wins. Keep Clues alive while Interrogators resolves rather than cracking them for cards.</p>
</section>
<section id="mulligan-guide" class="level3">
<h3 class="anchored" data-anchor-id="mulligan-guide">Mulligan guide</h3>
<p>Keep hands with two to three lands and an early play (Leech, Gremlin Tamer, Falcon, Inquiry, or Tracker). A hand with Ghostly Dancers or Teysa but no early eerie payoff is slow; mulligan hands that need three colors by turn 3 unless a fetch land is present. Seven-card hands with four or more lands and no spell are playable but lean to mulligan at five lands.</p>
</section>
<section id="key-interactions-and-edge-cases" class="level3">
<h3 class="anchored" data-anchor-id="key-interactions-and-edge-cases">Key interactions and edge cases</h3>
<ul>
<li>Eerie triggers on any enchantment entering under your control, including tokens: Grand Entryway’s Glimmer tokens trigger eerie on their own entry.</li>
<li>A Room counts as a second eerie source when its last locked door is unlocked: casting the Room is one enchantment entry, unlocking the other door is a separate eerie event.</li>
<li>Fear of Infinity returns to hand only from the graveyard. If it is on the battlefield it stays there; it must die or be discarded first.</li>
<li>“When a Clue you control is put into a graveyard from the battlefield” (Teysa) includes cracking Clues for cards, not sacrificing via costs that exile them.</li>
<li>Case of the Filched Falcon solves once you control three artifacts; Clues and Treasure tokens count. The solved Falcon can animate a Clue token into a 4/4 flying Bird, which Rogue’s Passage then sends through unblocked.</li>
<li>No Witnesses destroys your own creatures too. Play it after your Clues and before committing a second wave, or when the board state favors resetting.</li>
<li>Infernal Phantom wants enchantment density: each entry makes it a bigger threat, and even a chump block turns into direct damage.</li>
</ul>
</section>
<section id="matchups" class="level3">
<h3 class="anchored" data-anchor-id="matchups">Matchups</h3>
<ul>
<li><strong>Aggro swarms:</strong> No Witnesses resets the ground; Leech and Teysa keep the life total safe while Gremlin Tamer blocks. The flying spirits race well.</li>
<li><strong>Control:</strong> Prioritize Entity Tracker and Clue draw to out-card the opponent; Grand Entryway rooms and enchantment recursion are resilient to sorcery-speed removal. Avoid overcommitting into a wipe.</li>
<li><strong>Lifegain:</strong> pivot to the poison route; do not race the life total.</li>
<li><strong>Big mana:</strong> pressure with the enchantment chain and finish with Rogue’s Passage on a solved Falcon Bird before the opponent’s haymakers resolve.</li>
</ul>
</section>
</section>
<section id="iterations" class="level2">
<h2 class="anchored" data-anchor-id="iterations">Iterations</h2>
<p>v1 ran WUBG (no red); v2 completed the rolled WUBRG identity.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>Change</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v1 -&gt; v2</td>
<td>-2 Unwilling Vessel, +2 Infernal Phantom; manabase -1 Swamp, +2 Mountain (27 lands kept)</td>
<td>sim 53.7% -&gt; 53.3%, synergy 73.2 -&gt; 74.5, goldfish T4 0.766 -&gt; 0.750, P(4 lands T4) 0.776 -&gt; 0.743</td>
</tr>
</tbody>
</table>
<p>All gates pass on v2: 60 cards, Standard legal, no rotating cards, sim avg 53.3%, synergy 74.5, goldfish T4 0.750, P(4 lands by T4) 0.743.</p>
</section>
<section id="deck-list-arena-import" class="level2">
<h2 class="anchored" data-anchor-id="deck-list-arena-import">Deck list (Arena import)</h2>
<pre><code>Cold Case Haunting
Deck
4 Balemurk Leech
4 Case of the Filched Falcon
3 Entity Tracker
3 Fear of Infinity
3 Ghostly Dancers
2 Gremlin Tamer
2 Teysa, Opulent Oligarch
2 Infernal Phantom
2 Persuasive Interrogators
2 Curious Inquiry
2 Grand Entryway
2 They Went This Way
2 No Witnesses
1 Rogue's Passage
1 Fountainport
1 Evolving Wilds
1 Terramorphic Expanse
7 Island
7 Plains
5 Swamp
2 Forest
2 Mountain</code></pre>


</section>

</main> <!-- /main -->
<script data-goatcounter="https://th3pajay.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>From th3pajay — a new Standard deck guide every morning</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/th3pajay/mtga-decks">Source on GitHub</a></p>
</div>
  </div>
</footer>




</body></html>