<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-30">

<title>Exhaust Manifold – MTG Decks — Daily Standard Guides</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a8dd2cfac03084eab458e3b1c626e1f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MTG Decks — Daily Standard Guides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a>
  <ul class="collapse">
  <li><a href="#game-plan-phases" id="toc-game-plan-phases" class="nav-link" data-scroll-target="#game-plan-phases">Game plan phases</a></li>
  <li><a href="#card-roles" id="toc-card-roles" class="nav-link" data-scroll-target="#card-roles">Card roles</a></li>
  <li><a href="#lands-as-engines" id="toc-lands-as-engines" class="nav-link" data-scroll-target="#lands-as-engines">Lands as engines</a></li>
  <li><a href="#curve-and-mana" id="toc-curve-and-mana" class="nav-link" data-scroll-target="#curve-and-mana">Curve and mana</a></li>
  </ul></li>
  <li><a href="#gameplay-strategy" id="toc-gameplay-strategy" class="nav-link" data-scroll-target="#gameplay-strategy">Gameplay strategy</a>
  <ul class="collapse">
  <li><a href="#early-game" id="toc-early-game" class="nav-link" data-scroll-target="#early-game">Early game</a></li>
  <li><a href="#mid-game" id="toc-mid-game" class="nav-link" data-scroll-target="#mid-game">Mid game</a></li>
  <li><a href="#the-combo-turn" id="toc-the-combo-turn" class="nav-link" data-scroll-target="#the-combo-turn">The combo turn</a></li>
  <li><a href="#win-condition-2" id="toc-win-condition-2" class="nav-link" data-scroll-target="#win-condition-2">Win condition 2</a></li>
  <li><a href="#mulligan-guide" id="toc-mulligan-guide" class="nav-link" data-scroll-target="#mulligan-guide">Mulligan guide</a></li>
  <li><a href="#key-interactions-and-edge-cases" id="toc-key-interactions-and-edge-cases" class="nav-link" data-scroll-target="#key-interactions-and-edge-cases">Key interactions and edge cases</a></li>
  <li><a href="#matchups" id="toc-matchups" class="nav-link" data-scroll-target="#matchups">Matchups</a></li>
  </ul></li>
  <li><a href="#iterations" id="toc-iterations" class="nav-link" data-scroll-target="#iterations">Iterations</a></li>
  <li><a href="#deck-list-arena-import" id="toc-deck-list-arena-import" class="nav-link" data-scroll-target="#deck-list-arena-import">Deck list (Arena import)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exhaust Manifold</h1>
<p class="subtitle lead">Glint-Eye (U/B/R/G) Tap-Out Grind — Exhaust engines, a rolling Mill clock and Teamwork tap costs</p>
  <div class="quarto-categories">
    <div class="quarto-category">combo</div>
    <div class="quarto-category">mill</div>
    <div class="quarto-category">teamwork</div>
    <div class="quarto-category">exhaust</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 30, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="at-a-glance" class="level1">
<h1>At a glance</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 61%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Format</td>
<td>Standard (MTGA)</td>
</tr>
<tr class="even">
<td>Colors</td>
<td>Blue / Black / Red / Green</td>
</tr>
<tr class="odd">
<td>Archetype</td>
<td>Tap-out aggro-combo (31 of 37 non-land slots are creatures, average CMC 2.1)</td>
</tr>
<tr class="even">
<td>Size</td>
<td>60 cards — 37 non-land, 23 lands</td>
</tr>
<tr class="odd">
<td>Core mechanics</td>
<td>Exhaust, fed by Mill and paid for with Teamwork</td>
</tr>
<tr class="even">
<td>Primary win</td>
<td>Mill-out: The Water Crystal turns every opponent mill into plus four, and Riverchurn Monument’s exhaust mills a player for the size of their own graveyard</td>
</tr>
<tr class="odd">
<td>Secondary win</td>
<td>A wide board of exhaust counters, made lethal by Sita Varma’s power equalisation and pushed through by Rogue’s Passage</td>
</tr>
<tr class="even">
<td>Win-condition land</td>
<td>Restless Reef — a 4/4 deathtouch Shark that mills four on every attack</td>
</tr>
<tr class="odd">
<td>Score</td>
<td>overall 90.77 (cohesion 75.6, synergy 75.6, sim 58.7 percent)</td>
</tr>
</tbody>
</table>
</section>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>Exhaust Manifold is a four-colour tap-out deck built on one rule: every card in it wants to be tapped, and every tap is worth a card, a counter, or a chunk of the opponent’s library. Exhaust abilities are the engine — each can be activated only once, so a deck full of them trades burst for reach, and Elvish Refueler plus Afterburner Expert turn that once-only rule into a repeating loop.</p>
<p>Mill is the clock the engine is bolted to. Scarblade Scout mills two on entry, Master’s Councillors mills three every time you draw your second card in a turn, Veteran Ice Climber mills its own power on every attack, and Restless Reef mills four whenever it attacks as a 4/4 deathtouch Shark. The Water Crystal makes all of that bigger: if an opponent would mill one or more cards, they mill that many plus four instead, so a two-card Scout entry is six cards and a single Reef attack is eight. Riverchurn Monument’s exhaust then mills a player for cards equal to the number of cards already in their graveyard, which is why the deck wins the long game against anything that fills its own graveyard.</p>
<p>Teamwork is the third leg, and it is what makes the tapping pay. Too Evil to Stay Dead, Go Nuts! and Cruel Alliance all cost “tap any number of creatures with total power N or more” if you want the bonus — and tapping the team is not a cost for this deck so much as a second activation. Volatile Wanderglyph loots whenever it becomes tapped, Master’s Councillors turns your second draw into a mill trigger, and the graveyard those loots fill is exactly what Afterburner Expert and Too Evil to Stay Dead want to see. Cast Too Evil to Stay Dead with teamwork and it returns any creature card, at any mana value, straight to the battlefield.</p>
</section>
<section id="approach" class="level1">
<h1>Approach</h1>
<section id="game-plan-phases" class="level2">
<h2 class="anchored" data-anchor-id="game-plan-phases">Game plan phases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>What happens</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Turns 1-2</td>
<td>Open on Greasewrench Goblin or a two-mana body: Volatile Wanderglyph, Greenbelt Guardian, Prowcatcher Specialist, Scarblade Scout or Master’s Councillors. Shocklands come in untapped for 2 life so the second turn is never off-curve</td>
</tr>
<tr class="even">
<td>Turns 2-4</td>
<td>Two drops come down two at a time in the best draws. Scarblade Scouts start milling, Prowcatchers chip in for 2 with haste, and Riverchurn Monument starts dribbling two cards off both libraries</td>
</tr>
<tr class="odd">
<td>Turns 3-5</td>
<td>The engine turns on: Greasewrench Goblin and Greenbelt Guardian exhaust for cards and counters, afterburner Expert sits in the graveyard waiting, and The Water Crystal upgrades every mill by four</td>
</tr>
<tr class="even">
<td>Turns 4-6</td>
<td>Master’s Councillors and Riverchurn Monument grind the opponent’s library while the team attacks. Sita Varma and Redshift give the deck its big turns</td>
</tr>
<tr class="odd">
<td>Turn 6+</td>
<td>The mill lock: Riverchurn Monument’s exhaust, chained by Elvish Refueler, strips the opponent’s library; Rogue’s Passage makes the pumped team unblockable for the damage win</td>
</tr>
</tbody>
</table>
</section>
<section id="card-roles" class="level2">
<h2 class="anchored" data-anchor-id="card-roles">Card roles</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Card</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Volatile Wanderglyph</td>
<td>{1}{R} 2/2 artifact Golem — tap engine: whenever it becomes tapped you may discard a card, then draw; the discard is graveyard fuel for Afterburner Expert</td>
</tr>
<tr class="even">
<td>Greenbelt Guardian</td>
<td>{1}{G} 2/2 Elf Ranger — pump and counter payoff: {G} gives trample, exhaust {3}{G} puts three plus-one counters on it</td>
</tr>
<tr class="odd">
<td>Prowcatcher Specialist</td>
<td>{1}{R} 2/1 Goblin Warrior, haste — the turn-one clock: exhaust {3}{R} adds two plus-one counters</td>
</tr>
<tr class="even">
<td>Scarblade Scout</td>
<td>{1}{B} 2/2 Elf Scout, lifelink — the cheapest mill: two cards off your own library on entry, and lifelink races aggro</td>
</tr>
<tr class="odd">
<td>Master’s Councillors</td>
<td>{1}{U} 1/3 Human Advisor, vigilance — second-draw mill three and it grows plus two plus zero for every graveyard holding seven or more cards</td>
</tr>
<tr class="even">
<td>Sita Varma, Masked Racer</td>
<td>{G}{U} 2/3 legendary Human Rogue — the alpha strike: exhaust {X}{G}{G}{U} adds X counters, then sets every other creature’s base power and toughness equal to hers</td>
</tr>
<tr class="odd">
<td>Redshift, Rocketeer Chief</td>
<td>{R}{G} 2/3 legendary Goblin Pilot, vigilance — mana for abilities (tap for one mana per point of power) and a twelve-mana exhaust that dumps your hand onto the battlefield</td>
</tr>
<tr class="even">
<td>Greasewrench Goblin</td>
<td>{R} 2/1 Goblin Artificer — the cheapest exhaust: {2}{R} discards up to two, draws that many, and adds a counter</td>
</tr>
<tr class="odd">
<td>Afterburner Expert</td>
<td>{2}{G} 4/2 Goblin Artificer — the recursion engine: exhaust {2}{G}{G} for two counters, and every exhaust activation you make returns it from the graveyard to the battlefield</td>
</tr>
<tr class="even">
<td>Elvish Refueler</td>
<td>{2}{G} 2/3 Elf Druid — the loop: during your turn, if you have not activated an exhaust ability yet, you may activate exhaust abilities as though they had never been used</td>
</tr>
<tr class="odd">
<td>Veteran Ice Climber</td>
<td>{1}{U} 1/3 Human Scout, vigilance — unblockable attacker that mills cards equal to its power, which Sita Varma can make very large</td>
</tr>
<tr class="even">
<td>Riverchurn Monument</td>
<td>{1}{U} artifact — repeatable two-card mill for both players, and the exhaust kill: every targeted player mills cards equal to the number already in their graveyard</td>
</tr>
<tr class="odd">
<td>The Water Crystal</td>
<td>{2}{U}{U} legendary artifact — mill amplifier (every opponent mill is plus four), blue spells cost one less, and a repeatable mill for cards equal to your hand size</td>
</tr>
<tr class="even">
<td>Too Evil to Stay Dead</td>
<td>{2}{B} sorcery, Teamwork 4 — returns a creature card from your graveyard; cast with teamwork and the mana value limit disappears</td>
</tr>
<tr class="odd">
<td>Go Nuts!</td>
<td>{G} sorcery, Teamwork 3 — a counter plus a fight for one mana, both modes when paid with teamwork</td>
</tr>
<tr class="even">
<td>Cruel Alliance</td>
<td>{2}{B} sorcery, Teamwork 2 — exiles a creature with mana value three or less, or any creature plus three life with teamwork</td>
</tr>
</tbody>
</table>
</section>
<section id="lands-as-engines" class="level2">
<h2 class="anchored" data-anchor-id="lands-as-engines">Lands as engines</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Land</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Restless Reef</td>
<td>The win-condition land. A 4/4 deathtouch Shark for {2}{U}{B} that mills four on every attack — eight with The Water Crystal out — and blocks anything on the ground</td>
</tr>
<tr class="even">
<td>Rogue’s Passage</td>
<td>Turns the largest attacker (usually Sita Varma or a triple-counter Greenbelt Guardian) unblockable for the lethal swing</td>
</tr>
<tr class="odd">
<td>Watery Grave / Breeding Pool / Overgrown Tomb</td>
<td>Blue-black, green-blue and black-green: the three pairs the deck needs most, and the reason the four-colour base works</td>
</tr>
<tr class="even">
<td>Steam Vents / Stomping Ground / Blood Crypt</td>
<td>Red-blue, red-green and black-red complete the colour wheel so every two-colour card in the deck is castable by turn three</td>
</tr>
<tr class="odd">
<td>Island / Forest</td>
<td>The two basics, kept in for Restless Reef’s and the deck’s colour spread when a shockland would rather come in tapped</td>
</tr>
</tbody>
</table>
</section>
<section id="curve-and-mana" class="level2">
<h2 class="anchored" data-anchor-id="curve-and-mana">Curve and mana</h2>
<p>The 37 non-land cards are three one-drops, twenty-eight two-drops, five three-drops and one four-drop, for an average CMC of 2.1. Twenty-seven of the thirty-one creatures cost exactly two mana, which is the point: the deck wants to spend its early turns making two threats, and The Water Crystal is the only card that costs more than three.</p>
<p>The mana base is eighteen shocklands, two Restless Reef and Rogue’s Passage plus one Island and one Forest. Twenty-two of the twenty-three lands produce at least one of the four colours and every colour has at least eight sources: eleven blue, eleven black, ten green, eight red. The shocks are the fix: paying 2 life to bring one in untapped means a hand with Breeding Pool and Blood Crypt casts any green, blue, black or red card on turn two. The cost is real against aggro — expect to pay four to eight life over a game — but Master’s Councillors and Scarblade Scout’s lifelink usually buy it back.</p>
</section>
</section>
<section id="gameplay-strategy" class="level1">
<h1>Gameplay strategy</h1>
<section id="early-game" class="level2">
<h2 class="anchored" data-anchor-id="early-game">Early game</h2>
<p>Turns one to three are two-drop turns: the deck has no one-drop plan beyond Greasewrench Goblin, and every other creature costs two. Prioritise by what the opponent is doing. Against aggro, Scarblade Scout first (lifelink plus mill) so the ground holds. Against control, Volatile Wanderglyph and Prowcatcher Specialist first, because a two-power clock backed by haste is how you punish a slow start. Riverchurn Monument can come down on turn two over a creature if the hand is removal-light.</p>
<p>Play shocklands untapped for the first four or five turns. The deck’s own lifelink and Master’s Councillors’ growth make the life payment an investment; a two-colour hand that comes in tapped is how this deck loses a turn it cannot spare.</p>
</section>
<section id="mid-game" class="level2">
<h2 class="anchored" data-anchor-id="mid-game">Mid game</h2>
<p>Turns four to six are when the engine assembles. The Water Crystal is the highest-impact card in the deck: with it out, Scarblade Scout’s entry mills six, Master’s Councillors’ second-draw trigger mills seven, Restless Reef’s attack mills eight and Riverchurn Monument’s exhaust tacks four onto every target. Play it before spending any exhaust abilities.</p>
<p>The tap triggers are the deck’s card advantage. Volatile Wanderglyph turns every Teamwork cost into a free loot, and the discard feeds Afterburner Expert into the graveyard. Greasewrench Goblin’s exhaust is a second draw, which turns Master’s Councillors into a mill engine on its own: exhaust the Goblin (discard, draw two), and the second card drawn fires Councillors’ trigger.</p>
<p>Do not attack into open blocks with the small bodies once the mill clock is online. The deck wins with its library plan far more often than it wins with damage, and every creature that dies is one fewer body to pay Teamwork costs with.</p>
</section>
<section id="the-combo-turn" class="level2">
<h2 class="anchored" data-anchor-id="the-combo-turn">The combo turn</h2>
<p>The mill kill is a chained exhaust, not an infinite loop:</p>
<ol type="1">
<li>Get The Water Crystal onto the battlefield, then let Riverchurn Monument’s {1}, {T} ability put two cards into every graveyard until each player has seven or more.</li>
<li>Activate Riverchurn Monument’s exhaust ({2}{U}{U}, {T}): every targeted player mills cards equal to the number already in their graveyard, plus four from The Water Crystal. A graveyard of ten becomes fourteen.</li>
<li>Next turn, activate that same exhaust again while Elvish Refueler is untapped and nothing else has been exhausted that turn: Refueler lets you activate exhaust abilities as though they had never been used, so the sixteen-card graveyard becomes twenty.</li>
<li>Each turn the number roughly doubles, and The Water Crystal’s own tap ability adds hand-size-plus-four per turn in between. Against a deck that fills its own graveyard, this closes out the game in three turns.</li>
</ol>
<p>A representative turn: The Water Crystal and Elvish Refueler out, four cards in hand. Tap Crystal for eight to the opponent, exhaust Riverchurn Monument for their graveyard plus four, attack with Restless Reef for another eight. Thirty-plus cards off a library in one turn.</p>
</section>
<section id="win-condition-2" class="level2">
<h2 class="anchored" data-anchor-id="win-condition-2">Win condition 2</h2>
<p>When milling is too slow or a single large threat has to die, the deck attacks. Prowcatcher Specialist with two counters is a 4/1, Greenbelt Guardian with three is a 5/5 trampler, and Sita Varma’s exhaust is the finisher: with four mana invested, X equals four counters and every other creature’s base power and toughness becomes five or more for the turn. Attack with everything, hold Rogue’s Passage’s {4}, {T} activation for the biggest creature, and the board that was milling for three a turn suddenly swings for twenty.</p>
<p>Afterburner Expert is the second route: because it returns from the graveyard whenever you activate an exhaust ability, a 4/2 that dies in combat comes back for free the turn you activate Greasewrench Goblin’s or Greenbelt Guardian’s exhaust, and Too Evil to Stay Dead with teamwork brings back anything else.</p>
</section>
<section id="mulligan-guide" class="level2">
<h2 class="anchored" data-anchor-id="mulligan-guide">Mulligan guide</h2>
<p>Keep any hand with two to four lands, at least two two-drops, and at least one of each colour pair you need for the cards in hand. A hand with Riverchurn Monument plus The Water Crystal is an automatic keep despite having little board presence: that pair is the game plan. Ship hands that need two specific colours and have only shocklands of a third, and ship hands with no creatures — the deck cannot pay Teamwork costs without a board, and its mill engine needs a blocker to survive to turn five.</p>
</section>
<section id="key-interactions-and-edge-cases" class="level2">
<h2 class="anchored" data-anchor-id="key-interactions-and-edge-cases">Key interactions and edge cases</h2>
<ul>
<li>The Water Crystal’s plus four applies to every opponent mill, including its own tap ability: with five cards in hand that ability mills nine, not five.</li>
<li>Elvish Refueler’s permission works only while you have not activated an exhaust ability this turn, so sequence it first: re-use Riverchurn Monument’s exhaust before touching Greasewrench Goblin or Greenbelt Guardian.</li>
<li>Every exhaust activation returns Afterburner Expert from the graveyard to the battlefield, not just your own exhaust abilities’ costs — any activation triggers it, and it can only be answered by exile.</li>
<li>Sita Varma’s exhaust sets base power and toughness, not counters: Veteran Ice Climber becomes a large unblockable creature that mills its new power when it attacks.</li>
<li>Master’s Councillors counts every graveyard with seven or more cards, including yours: after a couple of Riverchurn Monument activations it is a 5/3 for two.</li>
<li>Volatile Wanderglyph’s loot is optional when you tap it for Teamwork, and mandatory only in the sense that you want it: discard a land when you are flooded, a creature when Afterburner Expert is in the graveyard.</li>
<li>Too Evil to Stay Dead’s teamwork mode removes the mana value limit entirely — that is how a milled Sita Varma or Afterburner Expert comes back for three mana.</li>
<li>Restless Reef enters tapped, so plan the land drop a turn before you need the Shark; the mill trigger fires on attack, not on activation.</li>
<li>Rogue’s Passage produces colourless mana: it does not help cast anything, so it is a spell-land, not a mana source.</li>
</ul>
</section>
<section id="matchups" class="level2">
<h2 class="anchored" data-anchor-id="matchups">Matchups</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 62%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Opponent</th>
<th>Plan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aggro</td>
<td>Scarblade Scout’s lifelink and Restless Reef’s deathtouch hold the ground while you race with the mill clock; Cruel Alliance answers their turn-two threat</td>
</tr>
<tr class="even">
<td>Midrange</td>
<td>Mill beats card quality. Their big creatures do not matter if they never draw them, and The Water Crystal doubles every trigger</td>
</tr>
<tr class="odd">
<td>Control</td>
<td>Keep a two-power clock and exhaust in bursts; Afterburner Expert’s recursion is the engine they cannot answer with removal, only with exile</td>
</tr>
<tr class="even">
<td>Combo</td>
<td>The deck has no counterspells, so the plan is speed: two-drop into two-drop into Crystal plus Riverchurn, and Go Nuts! is the only interaction that buys a turn</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="iterations" class="level1">
<h1>Iterations</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 22%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>Change</th>
<th>sim</th>
<th>synergy</th>
<th>goldfish T4</th>
<th>P(4 lands T4)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v1</td>
<td>First 60: the same three mechanics on a basics-and-fetch four-colour manabase, with Silvergill Peddler, Keen Buccaneer, Venomized Cat, Enduring Vitality, Adrenaline Jockey and Boom Scholar carrying the theme</td>
<td>48.0 FAIL</td>
<td>74.2</td>
<td>0.577</td>
<td>0.565</td>
</tr>
<tr class="even">
<td>v2</td>
<td>Manabase rebuilt as UBRG shocklands and the creature slots rebuilt around two-mana two-power bodies: 4 Evolving Wilds, 2 Terramorphic Expanse, 5 Mountain, 3 Island, 2 Swamp, 2 Forest out for 4 Watery Grave, 3 Breeding Pool, 3 Steam Vents, 3 Overgrown Tomb, 3 Stomping Ground, 2 Blood Crypt; Silvergill Peddler 2, Keen Buccaneer 2, Venomized Cat 3, Enduring Vitality 2, Adrenaline Jockey 3, Boom Scholar 1, Repulsor Blast 1 and 2 Veteran Ice Climber out for 4 Greenbelt Guardian, 4 Scarblade Scout, 3 Master’s Councillors, 2 Sita Varma, 2 Redshift and 1 more Prowcatcher Specialist</td>
<td>58.7 PASS</td>
<td>75.6</td>
<td>0.585</td>
<td>0.570</td>
</tr>
</tbody>
</table>
<p>The failing metric in v1 was the simulated win rate, and the cause was mana, not synergy: a four-colour manabase built from basics and Evolving Wilds cannot cast a deck that wants two different colours on turn two, and the creature slots were paying three mana for two-power bodies. The v1 to v2 iteration moved sim 48.0 to 58.7, synergy 74.2 to 75.6, goldfish T4 0.577 to 0.585 and P(4 lands by turn 4) 0.565 to 0.570.</p>
</section>
<section id="deck-list-arena-import" class="level1">
<h1>Deck list (Arena import)</h1>
<pre><code>Exhaust Manifold
Deck
4 Volatile Wanderglyph
4 Greenbelt Guardian
4 Prowcatcher Specialist
4 Scarblade Scout
3 Master's Councillors
2 Sita Varma, Masked Racer
2 Redshift, Rocketeer Chief
2 Greasewrench Goblin
2 Afterburner Expert
2 Elvish Refueler
2 Veteran Ice Climber
1 Riverchurn Monument
1 The Water Crystal
2 Too Evil to Stay Dead
1 Go Nuts!
1 Cruel Alliance
4 Watery Grave
3 Breeding Pool
3 Steam Vents
3 Overgrown Tomb
3 Stomping Ground
2 Blood Crypt
2 Restless Reef
1 Rogue's Passage
1 Island
1 Forest</code></pre>


</section>

</main> <!-- /main -->
<script data-goatcounter="https://th3pajay.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>From th3pajay — a new Standard deck guide every morning</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/th3pajay/mtga-decks">Source on GitHub</a></p>
</div>
  </div>
</footer>




</body></html>