<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-23">

<title>Cinder and Coin – MTG Decks — Daily Standard Guides</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a8dd2cfac03084eab458e3b1c626e1f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MTG Decks — Daily Standard Guides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a>
  <ul class="collapse">
  <li><a href="#game-plan-phases" id="toc-game-plan-phases" class="nav-link" data-scroll-target="#game-plan-phases">Game plan phases</a></li>
  <li><a href="#card-roles" id="toc-card-roles" class="nav-link" data-scroll-target="#card-roles">Card roles</a></li>
  <li><a href="#lands-as-engines" id="toc-lands-as-engines" class="nav-link" data-scroll-target="#lands-as-engines">Lands as engines</a></li>
  <li><a href="#curve-and-mana" id="toc-curve-and-mana" class="nav-link" data-scroll-target="#curve-and-mana">Curve and mana</a></li>
  </ul></li>
  <li><a href="#gameplay-strategy" id="toc-gameplay-strategy" class="nav-link" data-scroll-target="#gameplay-strategy">Gameplay strategy</a>
  <ul class="collapse">
  <li><a href="#early-game" id="toc-early-game" class="nav-link" data-scroll-target="#early-game">Early game</a></li>
  <li><a href="#mid-game" id="toc-mid-game" class="nav-link" data-scroll-target="#mid-game">Mid game</a></li>
  <li><a href="#the-combo-turn" id="toc-the-combo-turn" class="nav-link" data-scroll-target="#the-combo-turn">The combo turn</a></li>
  <li><a href="#win-condition-2" id="toc-win-condition-2" class="nav-link" data-scroll-target="#win-condition-2">Win condition 2</a></li>
  <li><a href="#mulligan-guide" id="toc-mulligan-guide" class="nav-link" data-scroll-target="#mulligan-guide">Mulligan guide</a></li>
  <li><a href="#key-interactions-and-edge-cases" id="toc-key-interactions-and-edge-cases" class="nav-link" data-scroll-target="#key-interactions-and-edge-cases">Key interactions and edge cases</a></li>
  <li><a href="#matchups" id="toc-matchups" class="nav-link" data-scroll-target="#matchups">Matchups</a></li>
  </ul></li>
  <li><a href="#iterations" id="toc-iterations" class="nav-link" data-scroll-target="#iterations">Iterations</a></li>
  <li><a href="#deck-list-arena-import" id="toc-deck-list-arena-import" class="nav-link" data-scroll-target="#deck-list-arena-import">Deck list (Arena import)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Cinder and Coin</h1>
<p class="subtitle lead">Black / Red / Green Smaug Dragon x Treasure — The Hobbit set identity deck</p>
  <div class="quarto-categories">
    <div class="quarto-category">hobbit</div>
    <div class="quarto-category">smaug</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 23, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="at-a-glance" class="level1">
<h1>At a glance</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 61%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Format</td>
<td>Standard (MTGA)</td>
</tr>
<tr class="even">
<td>Colors</td>
<td>Black / Red / Green</td>
</tr>
<tr class="odd">
<td>Archetype</td>
<td>Smaug Dragon x Treasure hoard engine (avg nonland CMC 2.89)</td>
</tr>
<tr class="even">
<td>Size</td>
<td>60 cards</td>
</tr>
<tr class="odd">
<td>Primary win</td>
<td>Smaug the Magnificent: a Treasure on every upkeep, then an attack trigger that deals damage equal to your Treasure count to any target</td>
</tr>
<tr class="even">
<td>Secondary win</td>
<td>The Misty Mountains Cold turns a four-Treasure hoard into a 6/6 flying Dragon token, and Radagast of Rhosgobel rebates the next Dragon into play</td>
</tr>
<tr class="odd">
<td>Land win con</td>
<td>The Lonely Mountain is a Mountain-typed land — every copy adds a quest counter to Last Light of Durin’s Day, which at six counters puts a Dragon straight onto the battlefield</td>
</tr>
</tbody>
</table>
</section>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>Cinder and Coin is today’s The Hobbit set identity deck, and it takes the Smaug x Treasure axis rather than the storied Dwarves, the amass Goblins, or the Elf legends. The thesis is short: everything in the deck is either gold, a dragon, or a way to move one into the other.</p>
<p>The engine is Treasure, produced five different ways — Smaug the Magnificent’s upkeep trigger, The Misty Mountains Cold’s four saga chapters, Dori’s enter trigger, Bejeweled Warg’s combat damage, and The Sackville-Bagginses’ sacrifice trigger. The payoff is Smaug himself: whenever he attacks he deals damage equal to the number of Treasures you control to any target, on top of a 4/3 flying hasty body. Six Treasures turns one attack into ten damage. The gold also pays for everything, which is the quiet part of the deck: in a three-color list, Treasures are the real mana fixing.</p>
<p>The second kill line is on the board, not in the graveyard. The Misty Mountains Cold sacrifices itself at four or more Treasures into a 6/6 flying Dragon token, and Last Light of Durin’s Day converts a Mountain count into a free Dragon from hand or library. Radagast of Rhosgobel rebates two mana off the first creature spell each turn and gives it flash, so those Dragons arrive early and at instant speed. Every card in the list feeds that loop: no filler, no sideboard cards in the maindeck.</p>
<p>The Hobbit set (hob, 193 cards) landed on Arena on 2026-08-14; the import list below works from that date.</p>
</section>
<section id="approach" class="level1">
<h1>Approach</h1>
<section id="game-plan-phases" class="level2">
<h2 class="anchored" data-anchor-id="game-plan-phases">Game plan phases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>What happens</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Turns 1-2</td>
<td>Hoard start: The Sackville-Bagginses or Bejeweled Warg, plus Stir Up Trouble held up as one-mana removal</td>
</tr>
<tr class="even">
<td>Turns 2-3</td>
<td>Engine online: The Misty Mountains Cold starts stacking Treasures, Dori adds one on entry, Desolation Prowler holds the ground</td>
</tr>
<tr class="odd">
<td>Turns 3-5</td>
<td>The combo turn: Smaug the Magnificent lands on a growing hoard; The Misty Mountains Cold pops into a 6/6 flying Dragon</td>
</tr>
<tr class="even">
<td>Turn 5+</td>
<td>Smaug, Wicked Worm tops the curve; each point of gold spent on a spell draws a card, and each attack burns for the hoard total</td>
</tr>
</tbody>
</table>
</section>
<section id="card-roles" class="level2">
<h2 class="anchored" data-anchor-id="card-roles">Card roles</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Card</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Smaug the Magnificent</td>
<td>The engine and the payoff: a Treasure every upkeep and an attack trigger dealing damage equal to your Treasure count to any target</td>
</tr>
<tr class="even">
<td>The Misty Mountains Cold</td>
<td>Treasure every chapter for four chapters, then sacrifices itself into a 6/6 red flying Dragon token once the hoard hits four</td>
</tr>
<tr class="odd">
<td>Dori, Bearer of Friends</td>
<td>Three-mana legendary Dwarf that tramples in and makes a Treasure on entry</td>
</tr>
<tr class="even">
<td>The Sackville-Bagginses</td>
<td>Turns a spare artifact or creature into a card and a Treasure, and pings the opponent for 1 on every token sacrifice</td>
</tr>
<tr class="odd">
<td>Bejeweled Warg</td>
<td>Two-mana 3/2 trampler; combat damage to a player either grows a Wolf or mints another Treasure</td>
</tr>
<tr class="even">
<td>Smaug, Wicked Worm</td>
<td>Treasure burst on entry (one tapped Treasure per artifact the opponent controls) and a card whenever a spell is cast with Treasure mana</td>
</tr>
<tr class="odd">
<td>Last Light of Durin’s Day</td>
<td>Mountain quest counter; at six Mountains it sacrifices itself to put any Dragon from hand or library onto the battlefield</td>
</tr>
<tr class="even">
<td>Radagast of Rhosgobel</td>
<td>The first creature spell each turn costs two less and can be cast as though it had flash — this is how Smaug arrives early</td>
</tr>
<tr class="odd">
<td>Snowslope Hunter</td>
<td>Three-mana 2/3 that eats a spare Treasure to exile and play the top card of the library, once per turn</td>
</tr>
<tr class="even">
<td>Desolation Prowler</td>
<td>Cheapest body in the deck: a two-mana 2/2 that pays 2 life for +2/+2 each turn</td>
</tr>
<tr class="odd">
<td>Gundabad Opportunist</td>
<td>Four-mana 4/2 that exiles the top card on entry and lets you play it — Treasure mana pays for it</td>
</tr>
<tr class="even">
<td>The Master of Lake-town</td>
<td>Deathtouch 3/2 that mills any player for each point of life they lose, so Smaug’s burn becomes library damage</td>
</tr>
<tr class="odd">
<td>Stir Up Trouble</td>
<td>One-mana removal that is happy to eat a Treasure or a spent token as its additional cost</td>
</tr>
</tbody>
</table>
</section>
<section id="lands-as-engines" class="level2">
<h2 class="anchored" data-anchor-id="lands-as-engines">Lands as engines</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Land</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>The Lonely Mountain</td>
<td>The win-con land: it is a Mountain, so every copy advances Last Light of Durin’s Day’s quest counters; at four mana plus red it also makes 2/2 red Dwarf tokens, one cheaper per Equipment</td>
</tr>
<tr class="even">
<td>Mountain</td>
<td>Primary red source and a quest counter the moment it enters — eight copies is what turns Last Light into a real card</td>
</tr>
<tr class="odd">
<td>Swamp</td>
<td>Black source for Stir Up Trouble, Desolation Prowler, The Master of Lake-town, and Smaug, Wicked Worm</td>
</tr>
<tr class="even">
<td>Forest</td>
<td>Green source for Bejeweled Warg and Radagast of Rhosgobel; six copies because green is a light splash</td>
</tr>
</tbody>
</table>
</section>
<section id="curve-and-mana" class="level2">
<h2 class="anchored" data-anchor-id="curve-and-mana">Curve and mana</h2>
<p>24 lands: 4 The Lonely Mountain, 8 Mountain, 6 Swamp, 6 Forest. Red sources 12, black 6, green 6. Red is the workhorse; black and green are supported but thin, which is why every Treasure token in the deck is also mana fixing — treasure gold is what actually casts Radagast and Wicked Worm on curve.</p>
<p>Nonland curve: 1-drop x2, 2-drop x12, 3-drop x12, 4-drop x8, 5-drop x2. Average nonland CMC 2.89. The deck wants a two-drop on turn 2, a Treasure maker or saga on turn 3, and Smaug the Magnificent on turn 4 with at least two Treasures already banked.</p>
</section>
</section>
<section id="gameplay-strategy" class="level1">
<h1>Gameplay strategy</h1>
<section id="early-game" class="level2">
<h2 class="anchored" data-anchor-id="early-game">Early game</h2>
<p>Turns one and two are about the hoard and the board, in that order. The Sackville-Bagginses is the ideal turn-2 play: sacrifice nothing and it is just a 2/2, but sacrificing a later Treasure draws a card and mints a replacement, and every token sacrifice pings the opponent for 1. Bejeweled Warg is the aggressive alternative — a 3/2 trampler that converts its first connection into a Treasure. Hold Stir Up Trouble as a one-mana answer; the additional cost is any artifact or creature, so a Treasure token doubles as the removal spell’s fuel.</p>
<p>Do not be precious with Desolation Prowler. It is the cheapest way to keep the ground stable while the engine assembles, and 2 life for +2/+2 is a fine rate when the alternative is dying to a 3/3.</p>
</section>
<section id="mid-game" class="level2">
<h2 class="anchored" data-anchor-id="mid-game">Mid game</h2>
<p>The Misty Mountains Cold is the centerpiece of turns three through five. It makes a Treasure on every chapter and, at four or more Treasures, sacrifices itself to create a 6/6 red Dragon token with flying. Dori, Bearer of Friends accelerates the count; Bejeweled Warg and The Sackville-Bagginses add to it. Radagast of Rhosgobel is the mana engine that ties the phase together: the first creature spell you cast each turn costs two less and can be cast as though it had flash, which means Smaug the Magnificent can come down on turn four with mana held up, or at the end of an opponent’s turn once the board is clear.</p>
<p>Snowslope Hunter and Gundabad Opportunist are the card-flow pair. Both exile the top card of your library and let you play it; Snowslope Hunter pays a Treasure, Gundabad Opportunist pays nothing but arrives a turn later. Together they keep the land drops and the removal coming while the hoard grows.</p>
</section>
<section id="the-combo-turn" class="level2">
<h2 class="anchored" data-anchor-id="the-combo-turn">The combo turn</h2>
<ol type="1">
<li>Bank the hoard. Four Treasures is the magic number — at four, The Misty Mountains Cold trades itself for a 6/6 flying Dragon.</li>
<li>Cast Smaug the Magnificent for two red and two generic minus two if Radagast is on the battlefield. He has flying and haste, so he attacks the turn he lands.</li>
<li>Attack. Smaug’s trigger deals damage equal to your Treasure count to any target — the opponent, a planeswalker, or the one blocker that matters — and his 4 combat damage rides along on top.</li>
<li>Repeat. Every upkeep makes another Treasure, so each swing is one point bigger than the last. Four Treasures is 8 damage per turn, six is 10, eight is 12.</li>
</ol>
<p>A typical kill: a Misty Mountains Dragon token plus Smaug attacking on turn five with four Treasures is 6 flying plus 8 to the face with 4 more from Smaug’s own body. Most boards that are not already dead are dead on the next swing.</p>
</section>
<section id="win-condition-2" class="level2">
<h2 class="anchored" data-anchor-id="win-condition-2">Win condition 2</h2>
<p>The Master of Lake-town converts the same attack into library damage: whenever a player loses life, that player mills that many cards. Smaug’s trigger causes loss of life, so a four-Treasure attack mills 8 and then hits for 8. When The Master dies, it draws a card for each graveyard holding seven or more cards, so the mill line refills your own hand as the opponent’s library empties. Last Light of Durin’s Day is the third door: with six quest counters it puts a Dragon directly onto the battlefield for free, and its Mountaincycling for two means the card never rots in hand.</p>
</section>
<section id="mulligan-guide" class="level2">
<h2 class="anchored" data-anchor-id="mulligan-guide">Mulligan guide</h2>
<p>Keep hands with two to three lands and either a Treasure maker (The Sackville-Bagginses, Bejeweled Warg, Dori, The Misty Mountains Cold) or Stir Up Trouble. The best openers are two lands, a two-drop, and a three-drop. Mulligan one-land hands and hands with five or more lands and no engine. Because green and black are light splashes, a hand of red lands plus a Treasure maker is keepable, but a hand that can never cast a two-drop is not.</p>
</section>
<section id="key-interactions-and-edge-cases" class="level2">
<h2 class="anchored" data-anchor-id="key-interactions-and-edge-cases">Key interactions and edge cases</h2>
<ul>
<li>Smaug the Magnificent counts Treasures you control at the moment the trigger resolves, not when you attack — do not sacrifice a Treasure for Stir Up Trouble’s cost before combat if you plan to attack with Smaug.</li>
<li>The Misty Mountains Cold checks four or more Treasures after each chapter, so with Dori and Bejeweled Warg already banked it can pop its Dragon as early as chapter two.</li>
<li>Last Light of Durin’s Day counts Mountains entering, not lands. The Lonely Mountain is a Mountain; Swamp and Forest are not. Search Mountains specifically if you are racing the six counters.</li>
<li>Smaug, Wicked Worm counts artifacts the opponent controls at entry, so it is weakest against creature decks and enormous against artifact and Equipment decks. Its second ability triggers on any spell cast with Treasure mana, which includes spells paid for by the Treasures it just made.</li>
<li>Snowslope Hunter’s ability is once per turn and only during your turn, and it can eat the Warg’s Treasure or a spent token — it is a Treasure outlet, not a Treasure tax.</li>
<li>Radagast of Rhosgobel’s rebate applies to the first creature spell each turn, so sequence a cheap creature first only if you do not want the discount on a Dragon. It grants flash to the spell it discounts.</li>
<li>The Lonely Mountain enters tapped unless you control an Equipment. This list plays no Equipment, so treat it as an untapped-red-land on turn one or a tapped red source later, and do not count on the Dwarf token ability as a plan.</li>
</ul>
</section>
<section id="matchups" class="level2">
<h2 class="anchored" data-anchor-id="matchups">Matchups</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 62%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Opponent</th>
<th>Plan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aggro</td>
<td>Desolation Prowler and Stir Up Trouble trade up; The Sackville-Bagginses chump-blocks into a card; race with Smaug’s burn once the hoard hits four</td>
</tr>
<tr class="even">
<td>Midrange</td>
<td>Go over the top: a 6/6 flying Dragon token plus a hasted Smaug outclasses most ground boards, and Wicked Worm punishes artifact payoffs</td>
</tr>
<tr class="odd">
<td>Control</td>
<td>Bank Treasures instead of overextending; hold Smaug until they tap out, and use Radagast’s flash to deploy him at end of turn; Last Light of Durin’s Day cheats a Dragon past countermagic</td>
</tr>
<tr class="even">
<td>Combo</td>
<td>The clock is Smaug plus the hoard; The Master of Lake-town mills their library while they dig, and Snowslope Hunter keeps your hand full of answers</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="iterations" class="level1">
<h1>Iterations</h1>
<p>The list below is the output of the viability battery, not a first draft. One round was needed.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 27%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>Change</th>
<th>Metric delta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v1 to v2</td>
<td>-2 Smaug, the Great Calamity, -1 Gundabad Opportunist, -1 The Master of Lake-town, +4 lands (2 Mountain, 1 Swamp, 1 Forest) — the first build failed on land count and curve, and the seven-mana Dragon was the least efficient way to grow the hoard</td>
<td>T4 0.447 goes to 0.625, P(4 lands) 0.440 goes to 0.624, sim 49.7 goes to 53.7</td>
</tr>
</tbody>
</table>
<p>Final battery: 60 cards, Standard legal, zero rotating cards, sim 53.7 percent, synergy 72.4, T4 consistency 0.625, P(4 lands by turn 4) 0.624.</p>
</section>
<section id="deck-list-arena-import" class="level1">
<h1>Deck list (Arena import)</h1>
<pre><code>Cinder and Coin
Deck
3 Smaug the Magnificent
4 The Misty Mountains Cold
3 Dori, Bearer of Friends
3 The Sackville-Bagginses
3 Bejeweled Warg
2 Smaug, Wicked Worm
2 Last Light of Durin's Day
2 Stir Up Trouble
3 Radagast of Rhosgobel
3 Snowslope Hunter
4 Desolation Prowler
2 The Master of Lake-town
2 Gundabad Opportunist
4 The Lonely Mountain
8 Mountain
6 Swamp
6 Forest</code></pre>


</section>

</main> <!-- /main -->
<script data-goatcounter="https://th3pajay.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>From th3pajay — a new Standard deck guide every morning</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/th3pajay/mtga-decks">Source on GitHub</a></p>
</div>
  </div>
</footer>




</body></html>