<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-29">

<title>Overtake at Midnight – MTG Decks — Daily Standard Guides</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a8dd2cfac03084eab458e3b1c626e1f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MTG Decks — Daily Standard Guides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a>
  <ul class="collapse">
  <li><a href="#game-plan-phases" id="toc-game-plan-phases" class="nav-link" data-scroll-target="#game-plan-phases">Game plan phases</a></li>
  <li><a href="#card-roles" id="toc-card-roles" class="nav-link" data-scroll-target="#card-roles">Card roles</a></li>
  <li><a href="#lands-as-engines" id="toc-lands-as-engines" class="nav-link" data-scroll-target="#lands-as-engines">Lands as engines</a></li>
  <li><a href="#curve-and-mana" id="toc-curve-and-mana" class="nav-link" data-scroll-target="#curve-and-mana">Curve and mana</a></li>
  </ul></li>
  <li><a href="#gameplay-strategy" id="toc-gameplay-strategy" class="nav-link" data-scroll-target="#gameplay-strategy">Gameplay strategy</a>
  <ul class="collapse">
  <li><a href="#early-game" id="toc-early-game" class="nav-link" data-scroll-target="#early-game">Early game</a></li>
  <li><a href="#mid-game" id="toc-mid-game" class="nav-link" data-scroll-target="#mid-game">Mid game</a></li>
  <li><a href="#the-combo-turn" id="toc-the-combo-turn" class="nav-link" data-scroll-target="#the-combo-turn">The combo turn</a></li>
  <li><a href="#win-condition-2" id="toc-win-condition-2" class="nav-link" data-scroll-target="#win-condition-2">Win condition 2</a></li>
  <li><a href="#mulligan-guide" id="toc-mulligan-guide" class="nav-link" data-scroll-target="#mulligan-guide">Mulligan guide</a></li>
  <li><a href="#key-interactions-and-edge-cases" id="toc-key-interactions-and-edge-cases" class="nav-link" data-scroll-target="#key-interactions-and-edge-cases">Key interactions and edge cases</a></li>
  <li><a href="#matchups" id="toc-matchups" class="nav-link" data-scroll-target="#matchups">Matchups</a></li>
  </ul></li>
  <li><a href="#iterations" id="toc-iterations" class="nav-link" data-scroll-target="#iterations">Iterations</a></li>
  <li><a href="#deck-list-arena-import" id="toc-deck-list-arena-import" class="nav-link" data-scroll-target="#deck-list-arena-import">Deck list (Arena import)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Overtake at Midnight</h1>
<p class="subtitle lead">Four-color (W/U/B/R) Speed — Start your engines! aggro with a sacrifice drain loop</p>
  <div class="quarto-categories">
    <div class="quarto-category">combo</div>
    <div class="quarto-category">start-your-engines</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 29, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="at-a-glance" class="level1">
<h1>At a glance</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 61%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Format</td>
<td>Standard (MTGA)</td>
</tr>
<tr class="even">
<td>Colors</td>
<td>White / Blue / Black / Red</td>
</tr>
<tr class="odd">
<td>Archetype</td>
<td>Speed aggro-combo (avg CMC 2.28, 83 percent creatures)</td>
</tr>
<tr class="even">
<td>Core mechanic</td>
<td>Start your engines! (speed 1 to 4, max speed payoffs)</td>
</tr>
<tr class="odd">
<td>Primary win</td>
<td>Max-speed evasive kill: Hazoret, The Speed Demon and Streaking Oilgorger attack for lethal while Far Fortune adds a point to every source</td>
</tr>
<tr class="even">
<td>Secondary win</td>
<td>Death-drain loop: Embalmed Ascendant drains each opponent on every creature death, fed by Zahur, Gas Guzzler, Hour of Victory and Nesting Bot</td>
</tr>
<tr class="odd">
<td>Land as win condition</td>
<td>Restless Reef attacks as a 4/4 deathtouch Shark and mills four a turn; Amonkhet Raceway and Muraganda Raceway turn on at max speed</td>
</tr>
<tr class="even">
<td>Score</td>
<td>71.14 overall (synergy 73.4, aggro/midrange)</td>
</tr>
</tbody>
</table>
</section>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>Overtake at Midnight is a four-colour speed deck. Every permanent in it either grants the Start your engines! mechanic or profits from being at speed 4, so the deck does not need a specific two-card combo to function: it needs a body on turn one and one point of damage per turn, and the whole list turns on at once.</p>
<p>Speed is the engine. When any Start your engines! permanent is on the battlefield, your speed starts at 1 and rises by one on each of your turns in which an opponent loses life, up to a maximum of 4. One point of damage a turn is therefore enough to reach max speed by turn four, which is why eleven one-drops and a full set of Gas Guzzler make up the bottom of the curve. From turn four onward every card in the deck has a second mode: Burnout Bashtronaut gains double strike, Hazoret stops being a wall and starts attacking for five, The Speed Demon draws four cards a turn, Embalmed Ascendant drains on every death, and the two Raceway lands and Restless Reef take over the late game.</p>
<p>The second engine is a sacrifice loop. Nesting Bot, Hour of Victory and Embalmed Ascendant all produce bodies, Zahur, Glory’s Past converts any spare creature into a surveil, and Gas Guzzler converts one into a card. At max speed each of those deaths is a point of damage to each opponent from Embalmed Ascendant and, with Zahur in play, replaces the sacrificed body with a tapped 2/2 Zombie. That loop is also the deck’s answer to a stalled board: it kills without attacking.</p>
</section>
<section id="approach" class="level1">
<h1>Approach</h1>
<section id="game-plan-phases" class="level2">
<h2 class="anchored" data-anchor-id="game-plan-phases">Game plan phases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>What happens</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Turn 1</td>
<td>Gas Guzzler, Nesting Bot or Burnout Bashtronaut. Speed is 1 and the clock has started; Nesting Bot is the best of the three because it leaves a Servo behind when it dies</td>
</tr>
<tr class="even">
<td>Turns 2-3</td>
<td>Gastal Thrillseeker (one damage on entry, which is a free speed step), Endrider Catalyzer, Zahur or Slick Imitator. Keep attacking with whatever can get through: one point of damage is all the turn needs</td>
</tr>
<tr class="odd">
<td>Turns 3-4</td>
<td>Speed hits 4. Embalmed Ascendant and Perilous Snare come down, Hazoret starts attacking for five, Burnout Bashtronaut becomes a double striker and Far Fortune doubles the whole board’s damage</td>
</tr>
<tr class="even">
<td>Turns 5+</td>
<td>The Speed Demon and Streaking Oilgorger close the game; the sacrifice loop (Zahur plus Embalmed Ascendant plus Gas Guzzler) drains opponents who refuse to block, and Hour of Victory tutors for the missing payoff</td>
</tr>
<tr class="odd">
<td>Stalled board</td>
<td>Stop attacking into bigger blockers and switch to the loop: sacrifice a token a turn to Zahur (surveil, then a fresh Zombie) and Gas Guzzler (a card), draining each opponent once per death</td>
</tr>
</tbody>
</table>
</section>
<section id="card-roles" class="level2">
<h2 class="anchored" data-anchor-id="card-roles">Card roles</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 81%">
</colgroup>
<thead>
<tr class="header">
<th>Card</th>
<th>Role (with its key text)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gas Guzzler</td>
<td>{B} 2/1 enabler and card advantage; enters tapped, and at max speed {B} plus sacrificing another creature or Vehicle draws a card</td>
</tr>
<tr class="even">
<td>Nesting Bot</td>
<td>{W} 1/1 artifact body; when it dies it leaves a 1/1 colorless Servo artifact token, and at max speed it is a 2/1</td>
</tr>
<tr class="odd">
<td>Burnout Bashtronaut</td>
<td>{R} 1/1 menace with a {2} pump, and the deck’s cheapest attacker once max speed gives it double strike</td>
</tr>
<tr class="even">
<td>Endrider Catalyzer</td>
<td>{1}{R} 3/1 pressure that also guarantees the first speed step on turn two; at max speed it taps for {R}{R}</td>
</tr>
<tr class="odd">
<td>Gastal Thrillseeker</td>
<td>{B}{R} 2/3 that deals 1 damage to a target opponent and gains 1 life on entry, so the speed step never depends on combat; at max speed it has deathtouch and haste</td>
</tr>
<tr class="even">
<td>Slick Imitator</td>
<td>{1}{U} 1/3, the blue splash; at max speed {1} and sacrificing it copies target spell you control, and a copy of a permanent spell becomes a token</td>
</tr>
<tr class="odd">
<td>Zahur, Glory’s Past</td>
<td>{W}{B} 3/2 legendary; sacrifice another creature to surveil 1 once each turn, and at max speed every nontoken creature death makes a tapped 2/2 black Zombie</td>
</tr>
<tr class="even">
<td>Embalmed Ascendant</td>
<td>{1}{W}{B} 1/2 that arrives with a 2/2 black Zombie; at max speed every creature you control dying drains each opponent for 1 and gains you 1</td>
</tr>
<tr class="odd">
<td>Far Fortune, End Boss</td>
<td>{2}{B}{R} 4/5 legendary; attacking deals 1 damage to each opponent, and at max speed all damage from your sources to opponents and their permanents is increased by 1</td>
</tr>
<tr class="even">
<td>Hazoret, Godseeker</td>
<td>{1}{R} 5/3 indestructible haste; {1} and {T} make a creature with power 2 or less unblockable, but she can only attack or block once you have max speed</td>
</tr>
<tr class="odd">
<td>The Speed Demon</td>
<td>{3}{B}{B} 5/5 flying trample legend and the main clock; at end of turn you draw X and lose X life, where X is your speed</td>
</tr>
<tr class="even">
<td>Streaking Oilgorger</td>
<td>{4}{B} 3/3 flying haste that races anything and, at max speed, gains lifelink</td>
</tr>
<tr class="odd">
<td>Perilous Snare</td>
<td>{2}{W} exiles a nonland permanent on entry until it leaves the battlefield, and at max speed taps to put a +1/+1 counter on a creature at sorcery speed</td>
</tr>
<tr class="even">
<td>Hour of Victory</td>
<td>{2}{B} makes a 2/2 black Zombie on entry, and at max speed {1}{B} plus sacrificing it searches your library for any card</td>
</tr>
<tr class="odd">
<td>Starting Column</td>
<td>{3} tap for one mana of any colour, which is the deck’s only true four-colour fixer; at max speed sacrificing it draws two cards and discards one</td>
</tr>
</tbody>
</table>
</section>
<section id="lands-as-engines" class="level2">
<h2 class="anchored" data-anchor-id="lands-as-engines">Lands as engines</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Land</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Restless Reef</td>
<td>Win-condition land. Enters tapped, taps for {U} or {B}, and for {2}{U}{B} becomes a 4/4 blue-black Shark with deathtouch that mills four cards whenever it attacks. It triggers Far Fortune’s attack damage and wins games on its own when the ground is locked</td>
</tr>
<tr class="even">
<td>Amonkhet Raceway</td>
<td>Start your engines! on a land, and at max speed {T} grants haste, which lets Hazoret, The Speed Demon or the Reef attack the turn it arrives</td>
</tr>
<tr class="odd">
<td>Muraganda Raceway</td>
<td>Start your engines! and a {C} source; at max speed it makes {C}{C}, paying for Starting Column looting and artifact activations</td>
</tr>
<tr class="even">
<td>Swamp / Mountain / Plains / Island</td>
<td>Basic base: 6 / 5 / 4 / 3. Black is primary, red secondary, white and blue are one-pip splashes</td>
</tr>
</tbody>
</table>
</section>
<section id="curve-and-mana" class="level2">
<h2 class="anchored" data-anchor-id="curve-and-mana">Curve and mana</h2>
<p>The deck is 24 lands, 30 creatures and 6 non-creature permanents. The curve is 11 one-drops, 12 two-drops, 8 three-drops, 2 four-drops and 3 five-drops, for an average CMC of 2.28, so a land-light hand still functions and the deck keeps deploying threats while it raises speed.</p>
<p>Coloured sources: eight black (6 Swamp, 2 Restless Reef), five red, five blue (3 Island, 2 Restless Reef) and four white, plus two Starting Column that tap for any colour. Black and red are the bones of the deck (Gas Guzzler, Gastal Thrillseeker, Burnout Bashtronaut, Far Fortune, The Speed Demon), white is a four-card splash for Embalmed Ascendant, Zahur, Nesting Bot and Perilous Snare, and blue is a two-card splash for Slick Imitator. Only Restless Reef enters tapped, so the deck plays an untapped land on turns one and two almost every game.</p>
</section>
</section>
<section id="gameplay-strategy" class="level1">
<h1>Gameplay strategy</h1>
<section id="early-game" class="level2">
<h2 class="anchored" data-anchor-id="early-game">Early game</h2>
<p>Play a one-drop before anything else, even if it is only a Nesting Bot. The deck’s whole plan is to have an opponent lose life on each of your turns from turn two onward, and every Start your engines! permanent only pays off once speed reaches 4. Gastal Thrillseeker is the turn-two play that guarantees the step: its entry trigger deals one damage to a target opponent whether or not your attack connects. Endrider Catalyzer and Zahur apply real pressure while doing the same job.</p>
</section>
<section id="mid-game" class="level2">
<h2 class="anchored" data-anchor-id="mid-game">Mid game</h2>
<p>Turns three to five are about flipping the switches. Once speed is 4, the cards change meaning: Burnout Bashtronaut attacks as a 1/1 double striker with menace for one mana, Hazoret leaves the defence and starts attacking for five, Embalmed Ascendant turns every future trade into a point of drain, and Perilous Snare starts handing out counters while it holds a permanent exiled. Hold Perilous Snare or Embalmed Ascendant for the opponent’s turn-three threat rather than running out your own four-drop into nothing.</p>
</section>
<section id="the-combo-turn" class="level2">
<h2 class="anchored" data-anchor-id="the-combo-turn">The combo turn</h2>
<p>Max speed is a permanent state once reached, so the “combo” is what the deck does with it every turn afterwards:</p>
<ol type="1">
<li>Speed 4 means Far Fortune’s max-speed clause adds one damage to every source you control, including the one point from Far Fortune’s own attack trigger and Embalmed Ascendant’s drain.</li>
<li>Burnout Bashtronaut plus Hazoret plus The Speed Demon attack for 2, 5 and 5 with evasion and trample, where the 2 is a double striker and the Demon draws four cards at end of step.</li>
<li>Streaking Oilgorger’s lifelink and Embalmed Ascendant’s drain pay the life The Speed Demon costs, so the draw engine is free.</li>
</ol>
<p>An attack step with Far Fortune, Hazoret and The Speed Demon on a clear board is 14 damage before blocks, and every point is increased by Far Fortune’s clause. Hour of Victory’s max-speed mode tutors for whichever of those pieces is missing.</p>
</section>
<section id="win-condition-2" class="level2">
<h2 class="anchored" data-anchor-id="win-condition-2">Win condition 2</h2>
<p>When the board stalls, the deck stops attacking and starts sacrificing. Embalmed Ascendant at max speed drains each opponent for one on every creature death, and the deck manufactures deaths cheaply: Nesting Bot leaves a Servo when it dies, Hour of Victory and Embalmed Ascendant both arrive with a 2/2 Zombie, and Embalmed Ascendant’s own clause replaces creatures with Zombies when Zahur is in play. Zahur, Glory’s Past sacrifices a creature a turn to surveil, Gas Guzzler sacrifices one to draw a card, and Slick Imitator sacrifices itself to copy a spell. Each of those sacrifices is a drain trigger with Far Fortune on the board, and the Zombie tokens rebuild the board for the next one. The loop needs no attack step, which is how the deck beats a wall of blockers or a lifelink race.</p>
<p>Restless Reef is part of that plan rather than a footnote: for {2}{U}{B} it attacks as a 4/4 deathtouch creature, which is a body the opponent must block, it mills four cards whenever it attacks, and it turns on Far Fortune’s attack trigger and Embalmed Ascendant’s drain on turns when you otherwise cannot attack.</p>
</section>
<section id="mulligan-guide" class="level2">
<h2 class="anchored" data-anchor-id="mulligan-guide">Mulligan guide</h2>
<p>Keep any hand with two or three lands, a black or red source, and at least one one-drop or Gastal Thrillseeker. A hand with two lands, Gas Guzzler, Nesting Bot and a two-drop is a clear keep on the play: the deck only needs to reach three mana to play most of its cards, and speed climbs on its own. Ship hands whose only cheap cards are Hazoret or a Raceway, ship hands with neither black nor red mana (the deck cannot apply pressure without them), and ship four-land hands with no one-drops. Never keep a hand that cannot deal a point of damage by turn three.</p>
</section>
<section id="key-interactions-and-edge-cases" class="level2">
<h2 class="anchored" data-anchor-id="key-interactions-and-edge-cases">Key interactions and edge cases</h2>
<ul>
<li>Speed rises only once per turn no matter how much damage is dealt, so split your damage rather than overcommitting: one point on turn two is as good as ten.</li>
<li>Hazoret can neither attack nor block until you have max speed. Cast her early as a 5/3 indestructible blocker, then flip her into the attacker once speed is 4.</li>
<li>Far Fortune’s max-speed clause modifies damage from any source you control, including Burnout Bashtronaut’s pump, Embalmed Ascendant’s drain, Perilous Snare’s counters, Gastal Thrillseeker’s entry ping and Restless Reef’s combat damage.</li>
<li>Embalmed Ascendant’s drain triggers on every creature you control dying, tokens included, so sacrificing a Servo from Nesting Bot or a 2/2 Zombie is a real point of damage.</li>
<li>Zahur’s sacrifice ability is once each turn and only sacrifices another creature; use it on a token, and at max speed the death immediately makes a tapped 2/2 Zombie if the sacrificed creature was a nontoken.</li>
<li>Gas Guzzler can sacrifice a Vehicle as well as a creature, and its ability is the only card draw in the deck that costs nothing but a body.</li>
<li>Slick Imitator’s copy becomes a token if it copies a permanent spell: copying Perilous Snare exiles a second permanent, copying Hour of Victory makes another Zombie and a second tutor outlet, and copying a non-legendary creature such as Gastal Thrillseeker or Streaking Oilgorger adds a real body. Do not copy Far Fortune, Hazoret or The Speed Demon, because the legend rule kills the token.</li>
<li>The Speed Demon’s end step draws X and loses X where X is your speed, so at max speed it is four cards and four life each turn. Pair it with Streaking Oilgorger’s lifelink or hold it until Embalmed Ascendant is draining.</li>
<li>Starting Column is the deck’s only true four-colour fixer. Lead with it when your hand holds white and blue cards, and cash it in for the loot once speed is 4 and the colours are online.</li>
<li>Amonkhet Raceway’s haste mode is instant-speed-ish pressure: a hasty Hazoret or Restless Reef out of nowhere is often the last two points.</li>
<li>Muraganda Raceway produces only {C}, so it pays for Starting Column and artifact activations, never for your black, red, white or blue spells.</li>
</ul>
</section>
<section id="matchups" class="level2">
<h2 class="anchored" data-anchor-id="matchups">Matchups</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 62%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Opponent</th>
<th>Plan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aggro</td>
<td>Race with evasion: Hazoret is an indestructible blocker before max speed, Streaking Oilgorger’s lifelink stabilises, and Far Fortune’s attack ping means you win any pure damage race once speed is 4</td>
</tr>
<tr class="even">
<td>Midrange</td>
<td>Do not trade bodies one for one; let Perilous Snare exile their best permanent and use the sacrifice loop with Embalmed Ascendant and Zahur to drain past their blockers</td>
</tr>
<tr class="odd">
<td>Control</td>
<td>Deploy two threats a turn early, keep Gas Guzzler and Hour of Victory as post-sweeper rebuilding, and hold The Speed Demon until you can attack with it. Slick Imitator on a creature spell beats a single removal spell</td>
</tr>
<tr class="even">
<td>Combo</td>
<td>Hazoret plus Far Fortune is a fast clock and Perilous Snare exiles their key permanent. Hour of Victory’s max-speed tutor finds the piece you need, and Embalmed Ascendant’s drain ends games without attacking</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="iterations" class="level1">
<h1>Iterations</h1>
<p>The first viability pass passed every gate, so the final list is v1. Two lower-curve refinements were tested against the same battery and both scored worse, so the original list was kept.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 20%">
<col style="width: 18%">
<col style="width: 26%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>Change</th>
<th>sim win rate</th>
<th>goldfish T4</th>
<th>P(4 lands by T4)</th>
<th>synergy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v1</td>
<td>initial list (final)</td>
<td>54.0</td>
<td>0.621</td>
<td>0.638</td>
<td>73.4</td>
</tr>
<tr class="even">
<td>v1 to v2</td>
<td>-1 Gas Guzzler, -1 Nesting Bot, +2 Outpace Oblivion (reach over bodies)</td>
<td>52.3</td>
<td>0.631</td>
<td>0.621</td>
<td>73.2</td>
</tr>
<tr class="odd">
<td>v1 to v3</td>
<td>-1 Nesting Bot, +1 Far Fortune, End Boss (third copy of the multiplier)</td>
<td>48.7</td>
<td>0.627</td>
<td>0.624</td>
<td>73.4</td>
</tr>
</tbody>
</table>
<p>v1 to v2: sim 54.0 to 52.3, synergy 73.4 to 73.2 — reverted. v1 to v3: sim 54.0 to 48.7 on an identical manabase — reverted, the extra legendary copy cost more consistency than it added damage. All gates pass on v1: sim 54.0 (gate 52), synergy 73.4 (gate 70), goldfish T4 0.621 (gate 0.55), P(4 lands by T4) 0.638 (gate 0.55).</p>
</section>
<section id="deck-list-arena-import" class="level1">
<h1>Deck list (Arena import)</h1>
<pre><code>Overtake at Midnight
Deck
4 Gas Guzzler
4 Nesting Bot
3 Burnout Bashtronaut
3 Endrider Catalyzer
3 Gastal Thrillseeker
2 Slick Imitator
2 Zahur, Glory's Past
2 Embalmed Ascendant
2 Far Fortune, End Boss
2 Hazoret, Godseeker
2 The Speed Demon
1 Streaking Oilgorger
2 Perilous Snare
2 Hour of Victory
2 Starting Column
6 Swamp
5 Mountain
4 Plains
3 Island
2 Restless Reef
2 Amonkhet Raceway
2 Muraganda Raceway</code></pre>


</section>

</main> <!-- /main -->
<script data-goatcounter="https://th3pajay.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>From th3pajay — a new Standard deck guide every morning</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/th3pajay/mtga-decks">Source on GitHub</a></p>
</div>
  </div>
</footer>




</body></html>