<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-03">

<title>Requiem Mass – MTG Decks — Daily Standard Guides</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a8dd2cfac03084eab458e3b1c626e1f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MTG Decks — Daily Standard Guides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a>
  <ul class="collapse">
  <li><a href="#game-plan-in-three-phases" id="toc-game-plan-in-three-phases" class="nav-link" data-scroll-target="#game-plan-in-three-phases">Game plan in three phases</a></li>
  <li><a href="#card-roles" id="toc-card-roles" class="nav-link" data-scroll-target="#card-roles">Card roles</a></li>
  <li><a href="#lands-as-engines" id="toc-lands-as-engines" class="nav-link" data-scroll-target="#lands-as-engines">Lands as engines</a></li>
  <li><a href="#curve-and-mana" id="toc-curve-and-mana" class="nav-link" data-scroll-target="#curve-and-mana">Curve and mana</a></li>
  </ul></li>
  <li><a href="#gameplay-strategy" id="toc-gameplay-strategy" class="nav-link" data-scroll-target="#gameplay-strategy">Gameplay strategy</a>
  <ul class="collapse">
  <li><a href="#early-game-turns-1-3" id="toc-early-game-turns-1-3" class="nav-link" data-scroll-target="#early-game-turns-1-3">Early game (turns 1-3)</a></li>
  <li><a href="#mid-game-turns-4-6" id="toc-mid-game-turns-4-6" class="nav-link" data-scroll-target="#mid-game-turns-4-6">Mid game (turns 4-6)</a></li>
  <li><a href="#the-combo-turn" id="toc-the-combo-turn" class="nav-link" data-scroll-target="#the-combo-turn">The combo turn</a></li>
  <li><a href="#win-condition-2-vein-ripper-drain" id="toc-win-condition-2-vein-ripper-drain" class="nav-link" data-scroll-target="#win-condition-2-vein-ripper-drain">Win condition 2: Vein Ripper drain</a></li>
  <li><a href="#mulligan-guide" id="toc-mulligan-guide" class="nav-link" data-scroll-target="#mulligan-guide">Mulligan guide</a></li>
  <li><a href="#key-interactions-and-edge-cases" id="toc-key-interactions-and-edge-cases" class="nav-link" data-scroll-target="#key-interactions-and-edge-cases">Key interactions and edge cases</a></li>
  <li><a href="#matchups" id="toc-matchups" class="nav-link" data-scroll-target="#matchups">Matchups</a></li>
  </ul></li>
  <li><a href="#iterations" id="toc-iterations" class="nav-link" data-scroll-target="#iterations">Iterations</a></li>
  <li><a href="#deck-list-arena-import" id="toc-deck-list-arena-import" class="nav-link" data-scroll-target="#deck-list-arena-import">Deck list (Arena import)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Requiem Mass</h1>
<p class="subtitle lead">Orzhov Endure x Sacrifice — every death makes the choir louder</p>
  <div class="quarto-categories">
    <div class="quarto-category">combo</div>
    <div class="quarto-category">endure</div>
    <div class="quarto-category">sacrifice</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 3, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="at-a-glance" class="level1">
<h1>At a glance</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Format</td>
<td>Standard</td>
</tr>
<tr class="even">
<td>Colors</td>
<td>White Black (Orzhov)</td>
</tr>
<tr class="odd">
<td>Archetype</td>
<td>Aristocrats midrange (sacrifice engine)</td>
</tr>
<tr class="even">
<td>Size</td>
<td>60 cards, 24 lands</td>
</tr>
<tr class="odd">
<td>Rolled mechanics</td>
<td>Endure x Sacrifice</td>
</tr>
<tr class="even">
<td>Core engine</td>
<td>Death triggers + sacrifice outlets turn every body into a Spirit, a counter, or a card</td>
</tr>
<tr class="odd">
<td>Primary win</td>
<td>Voltron: Anafenza, Unyielding Lineage or Hei Bai, Spirit of Balance grows huge off sacrifices, then swings through with Rogue’s Passage</td>
</tr>
<tr class="even">
<td>Secondary win</td>
<td>Vein Ripper drain: every creature death deals 2, and the deck can sacrifice multiple times per turn</td>
</tr>
<tr class="odd">
<td>Nonland curve</td>
<td>6 one-drops, 13 twos, 15 threes, 2 sixes (avg CMC ~2.5)</td>
</tr>
</tbody>
</table>
</section>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>Requiem Mass is an Orzhov aristocrats deck built around the fusion of two Tarkir-era mechanics. <strong>Endure</strong> puts a +1/+1 counter on a creature or creates an N/N white Spirit token whenever it triggers. <strong>Sacrifice</strong> asks for bodies and pays out in cards, life, and damage. The bridge between the two is death itself: nearly every card in the deck either produces a token to feed an outlet, or cares about a creature dying.</p>
<p>The engine hinges on <code>Anafenza, Unyielding Lineage</code>. Whenever another nontoken creature you control dies, she endures 2 — put two +1/+1 counters on her or create a 2/2 Spirit. That means every sacrifice of a real creature doubles as permanent growth for your best attacker. <code>Bartolomé del Presidio</code> is the free sacrifice outlet that turns those same deaths into counters on itself, <code>Vampiric Rites</code> and <code>Baron Bertram Graywater</code> convert fodder into cards, and <code>Vein Ripper</code> charges 2 life per death from the opponent. Tokens created by endure creatures (Spirits from <code>Fortress Kin-Guard</code>, <code>Descendant of Storms</code>, and <code>Krumar Initiate</code>) are the fuel: they are expendable, so the engine never runs out of bodies.</p>
<p>The deck is a midrange value machine that plays like an aggro deck early — 1/2 and 2/1 endure creatures apply pressure while stockpiling tokens — then turns a mid-game turn with two or three sacrifices into a giant, unblockable threat or a burst of drain.</p>
</section>
<section id="approach" class="level1">
<h1>Approach</h1>
<section id="game-plan-in-three-phases" class="level2">
<h2 class="anchored" data-anchor-id="game-plan-in-three-phases">Game plan in three phases</h2>
<ol type="1">
<li><strong>Build the choir (turns 1-3).</strong> Deploy endure creatures and choose “create Spirit” on their triggers. <code>Descendant of Storms</code> attacks and makes a 1/1 Spirit for {1}{W}. <code>Fortress Kin-Guard</code> endures on entry. <code>Krumar Initiate</code> sits ready as a repeatable spirit factory.</li>
<li><strong>Direct the requiem (turns 3-5).</strong> Resolve <code>Anafenza, Unyielding Lineage</code> and a sacrifice outlet. Start sacrificing: nontoken creatures grow Anafenza by +2/+2 (or add a 2/2 Spirit), tokens keep the draw engines fed, and <code>Vein Ripper</code> bleeds the opponent for 2 life per death.</li>
<li><strong>Close the service.</strong> Attack with a 10/10-plus Anafenza or <code>Hei Bai, Spirit of Balance</code> through <code>Rogue's Passage</code>, or drain out with repeated sacrifices and <code>Treacherous Greed</code>.</li>
</ol>
</section>
<section id="card-roles" class="level2">
<h2 class="anchored" data-anchor-id="card-roles">Card roles</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Role</th>
<th>Cards</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Endure engine</td>
<td>Anafenza, Unyielding Lineage; Fortress Kin-Guard; Descendant of Storms; Krumar Initiate</td>
</tr>
<tr class="even">
<td>Sacrifice outlets</td>
<td>Bartolomé del Presidio; Vampiric Rites; Baron Bertram Graywater; Hei Bai, Spirit of Balance</td>
</tr>
<tr class="odd">
<td>Sacrifice payoffs</td>
<td>Vein Ripper; Sandbender Scavengers; Treacherous Greed; Ruthless Lawbringer; Social Snub</td>
</tr>
<tr class="even">
<td>Death recursion</td>
<td>Sandbender Scavengers (reanimate on death)</td>
</tr>
<tr class="odd">
<td>Card draw</td>
<td>Vampiric Rites; Baron Bertram Graywater; Treacherous Greed</td>
</tr>
</tbody>
</table>
</section>
<section id="lands-as-engines" class="level2">
<h2 class="anchored" data-anchor-id="lands-as-engines">Lands as engines</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Land</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rogue’s Passage</td>
<td>Part of the win condition: makes the grown Anafenza or Hei Bai unblockable for the killing swing</td>
</tr>
<tr class="even">
<td>Shadowy Backstreet</td>
<td>Tapped dual that surveils 1, smoothing draws into the engine</td>
</tr>
<tr class="odd">
<td>Godless Shrine / Concealed Courtyard / Bleachbone Verge</td>
<td>Untapped fixing to keep the curve fast</td>
</tr>
</tbody>
</table>
<p>The manabase is 24 lands in exactly White and Black (plus the colorless <code>Rogue's Passage</code>). Fast duals keep the early endure creatures on schedule, while <code>Shadowy Backstreet</code> trades a tempo for a surveil toward the engine pieces.</p>
</section>
<section id="curve-and-mana" class="level2">
<h2 class="anchored" data-anchor-id="curve-and-mana">Curve and mana</h2>
<p>Nineteen of the nonland cards cost two or less and only two cost more than three (the <code>Vein Ripper</code> pair), so the deck curves out aggressively and floods the board with bodies before the engine turns on. <code>Bleachbone Verge</code> needs a Plains or Swamp to tap for either color, so the eight basics guarantee it is live from turn one.</p>
</section>
</section>
<section id="gameplay-strategy" class="level1">
<h1>Gameplay strategy</h1>
<section id="early-game-turns-1-3" class="level2">
<h2 class="anchored" data-anchor-id="early-game-turns-1-3">Early game (turns 1-3)</h2>
<p>Lead with <code>Descendant of Storms</code> or <code>Fortress Kin-Guard</code>. Always take the Spirit token from endure triggers in the first turns — the board presence threatens damage while quietly banking sacrifice fodder. <code>Krumar Initiate</code> is the best turn-two play when you expect a long game: every spare mana becomes an X/X Spirit at sorcery speed, paying life you will win back from <code>Vein Ripper</code>, <code>Baron Bertram Graywater</code>, and <code>Treacherous Greed</code>.</p>
</section>
<section id="mid-game-turns-4-6" class="level2">
<h2 class="anchored" data-anchor-id="mid-game-turns-4-6">Mid game (turns 4-6)</h2>
<p>Land <code>Anafenza, Unyielding Lineage</code> and start the engine. The key sequencing rule: sacrifice <strong>nontoken</strong> creatures while Anafenza is out (each one makes her +2/+2 or a 2/2 Spirit), and sacrifice <strong>tokens</strong> when you only need cards or life. <code>Ruthless Lawbringer</code> is removal and an engine in one: it enters, eats a creature, and destroys any nonland permanent — with Anafenza on board the eaten creature grows her at the same time. <code>Social Snub</code> clears a blocker or a hexproof threat from every opponent and gains a life per copy.</p>
</section>
<section id="the-combo-turn" class="level2">
<h2 class="anchored" data-anchor-id="the-combo-turn">The combo turn</h2>
<p>With <code>Anafenza, Unyielding Lineage</code> and <code>Bartolomé del Presidio</code> on the battlefield, plus any nontoken creature and a token generator:</p>
<ul>
<li>Sacrifice the nontoken creature to Bartolomé: Bartolomé grows +1/+1, Anafenza endures 2.</li>
<li>Repeat with each body: <code>Krumar Initiate</code> can be tapped to make an X/X Spirit first, then sacrificed as a nontoken creature on a later activation, or kept alive to keep generating.</li>
<li>Each death also triggers <code>Vein Ripper</code> for 2 damage if he is out.</li>
<li>When Anafenza (or Bartolomé, or Hei Bai) has enough counters, activate <code>Rogue's Passage</code> and attack for lethal through any board.</li>
</ul>
<p><code>Hei Bai, Spirit of Balance</code> is the second engine that attacks: enter or attack, sacrifice a Spirit token, put two counters on it. A single Hei Bai attacking every turn while churning tokens through the outlet grows by +2/+2 per turn and beats as a 7/7 or larger fly-over blocker-free threat. When it finally leaves, its counters move onto your next attacker, so the growth is never wasted.</p>
</section>
<section id="win-condition-2-vein-ripper-drain" class="level2">
<h2 class="anchored" data-anchor-id="win-condition-2-vein-ripper-drain">Win condition 2: Vein Ripper drain</h2>
<p><code>Vein Ripper</code> turns the whole engine into a life-drain combo. Every creature death — tokens included — makes the opponent lose 2 life and you gain 2. A single engine turn with four or five sacrifices (Spirits from Krumar, an enduring creature, a lawbringer snack) is 8 to 10 damage. The 6/5 flying body with ward-sacrifice also ends games on its own, and <code>Treacherous Greed</code> closes: sacrifice a creature that already dealt combat damage this turn to draw three, drain 3, and gain 3 in one instant.</p>
</section>
<section id="mulligan-guide" class="level2">
<h2 class="anchored" data-anchor-id="mulligan-guide">Mulligan guide</h2>
<p>Keep any hand with two or three lands and a two-drop. <code>Fortress Kin-Guard</code> or <code>Bartolomé del Presidio</code> on turn two is the ideal start; <code>Anafenza</code> in the opening seven is excellent but not required. Throw back hands full of three-drops with no early creature, hands with five or more lands, or hands with <code>Vein Ripper</code> and no black sources. <code>Rogue's Passage</code> alone does not count as a colored source in the opener.</p>
</section>
<section id="key-interactions-and-edge-cases" class="level2">
<h2 class="anchored" data-anchor-id="key-interactions-and-edge-cases">Key interactions and edge cases</h2>
<ul>
<li><strong>Anafenza only sees nontoken deaths.</strong> Tokens are fuel for outlets and draw; nontoken creatures are the ones that grow her. Sequence accordingly: make a Spirit, sacrifice the Spirit to <code>Vampiric Rites</code> for a card, then sacrifice a nontoken body to Bartolomé for the endure trigger.</li>
<li><strong>Endure is a choice.</strong> “Put counters on it or create a Spirit.” You may split decisions per trigger — counters when building a voltron kill, Spirits when you need fodder or blockers.</li>
<li><strong>Krumar Initiate’s activation is sorcery-speed</strong> and costs life; the X/X Spirit it makes can be sacrificed the same turn, but only after the activation resolves.</li>
<li><strong>Sandbender Scavengers reanimates on its own death</strong> for a creature with mana value equal to or less than its power. Feed it counters by sacrificing other permanents, then when it dies it returns your <code>Anafenza</code> or <code>Vein Ripper</code> from the graveyard.</li>
<li><strong>Ruthless Lawbringer’s destroy is optional</strong> but the sacrifice is not: when it enters you may sacrifice a creature, and only if you do does the destroy trigger go on the stack.</li>
<li><strong>Vein Ripper’s ward asks for a sacrifice</strong> — your opponent pays it by losing a creature, which triggers the drain anyway. Ward here is often a free 2 damage.</li>
<li><strong>Social Snub copies</strong> if you control a creature when you cast it, so it usually hits each opponent once (or twice in a mirror of two players) for an edict plus a drain.</li>
</ul>
</section>
<section id="matchups" class="level2">
<h2 class="anchored" data-anchor-id="matchups">Matchups</h2>
<ul>
<li><strong>Aggro:</strong> You are the control deck. Trade endure creatures, use the life gain from Rites and Ripper, and stabilize behind Vein Ripper’s 6/5 flying body. <code>Shadowy Backstreet</code>’s surveil finds answers.</li>
<li><strong>Midrange:</strong> The engine out-values most fair decks — every removal spell they spend on your creatures is another Anafenza trigger and another drain from Ripper. Press the sacrifice loop every turn.</li>
<li><strong>Control:</strong> Play around sweepers by keeping the voltron plan in hand until the turn you kill: grow Anafenza with activations, hold <code>Rogue's Passage</code>, and go over the top. <code>Social Snub</code> and Lawbringer answer their planeswalkers; ward on Vein Ripper taxes their spot removal.</li>
</ul>
</section>
</section>
<section id="iterations" class="level1">
<h1>Iterations</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>Change</th>
<th>Metric delta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v1</td>
<td>Initial 60-card build (Mortify x2 as removal)</td>
<td>synergy 69.96 (gate 70.0), sim 63.7%, T4 0.683, P4L 0.676</td>
</tr>
<tr class="even">
<td>v1 to v2</td>
<td>-2 Mortify, +2 Sandbender Scavengers (on-theme sacrifice payoff over generic removal)</td>
<td>synergy 69.81, sim 62.0%</td>
</tr>
<tr class="odd">
<td>v2 to v3</td>
<td>-3 Sinkhole Surveyor, -1 Descendant of Storms, +3 Hei Bai, Spirit of Balance, +1 Social Snub (higher-cohesion fusion pieces)</td>
<td>synergy 69.64, sim 63.7%, T4 0.706, P4L 0.716</td>
</tr>
</tbody>
</table>
<p>Final battery: sim 63.7% (gate 52), goldfish T4 0.706 (gate 0.55), P(4 lands by T4) 0.716 (gate 0.55), rotation 0. Synergy scored 69.6, a rounding short of the 70 gate after three iterations.</p>
</section>
<section id="deck-list-arena-import" class="level1">
<h1>Deck list (Arena import)</h1>
<pre><code>3 Descendant of Storms
4 Fortress Kin-Guard
4 Anafenza, Unyielding Lineage
4 Bartolomé del Presidio
3 Ruthless Lawbringer
3 Krumar Initiate
3 Hei Bai, Spirit of Balance
2 Baron Bertram Graywater
2 Vein Ripper
3 Vampiric Rites
2 Sandbender Scavengers
2 Treacherous Greed
1 Social Snub
4 Godless Shrine
4 Concealed Courtyard
4 Bleachbone Verge
3 Shadowy Backstreet
1 Rogue's Passage
4 Plains
4 Swamp</code></pre>


</section>

</main> <!-- /main -->
<script data-goatcounter="https://th3pajay.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>From th3pajay — a new Standard deck guide every morning</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/th3pajay/mtga-decks">Source on GitHub</a></p>
</div>
  </div>
</footer>




</body></html>