<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-07">

<title>Wyrmgold – MTG Decks — Daily Standard Guides</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a8dd2cfac03084eab458e3b1c626e1f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MTG Decks — Daily Standard Guides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a>
  <ul class="collapse">
  <li><a href="#game-plan-phases" id="toc-game-plan-phases" class="nav-link" data-scroll-target="#game-plan-phases">Game plan phases</a></li>
  <li><a href="#card-roles" id="toc-card-roles" class="nav-link" data-scroll-target="#card-roles">Card roles</a></li>
  <li><a href="#lands-as-engines" id="toc-lands-as-engines" class="nav-link" data-scroll-target="#lands-as-engines">Lands as engines</a></li>
  <li><a href="#curve-and-mana" id="toc-curve-and-mana" class="nav-link" data-scroll-target="#curve-and-mana">Curve and mana</a></li>
  </ul></li>
  <li><a href="#gameplay-strategy" id="toc-gameplay-strategy" class="nav-link" data-scroll-target="#gameplay-strategy">Gameplay strategy</a>
  <ul class="collapse">
  <li><a href="#early-game" id="toc-early-game" class="nav-link" data-scroll-target="#early-game">Early game</a></li>
  <li><a href="#mid-game" id="toc-mid-game" class="nav-link" data-scroll-target="#mid-game">Mid game</a></li>
  <li><a href="#the-combo-turn" id="toc-the-combo-turn" class="nav-link" data-scroll-target="#the-combo-turn">The combo turn</a></li>
  <li><a href="#win-condition-2" id="toc-win-condition-2" class="nav-link" data-scroll-target="#win-condition-2">Win condition 2</a></li>
  <li><a href="#mulligan-guide" id="toc-mulligan-guide" class="nav-link" data-scroll-target="#mulligan-guide">Mulligan guide</a></li>
  <li><a href="#key-interactions-and-edge-cases" id="toc-key-interactions-and-edge-cases" class="nav-link" data-scroll-target="#key-interactions-and-edge-cases">Key interactions and edge cases</a></li>
  <li><a href="#matchups" id="toc-matchups" class="nav-link" data-scroll-target="#matchups">Matchups</a></li>
  </ul></li>
  <li><a href="#iterations" id="toc-iterations" class="nav-link" data-scroll-target="#iterations">Iterations</a></li>
  <li><a href="#deck-list-arena-import" id="toc-deck-list-arena-import" class="nav-link" data-scroll-target="#deck-list-arena-import">Deck list (Arena import)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Wyrmgold</h1>
<p class="subtitle lead">Jund (Black / Red / Green) — Smaug hoard-burn with doubled dragon damage, from The Hobbit set</p>
  <div class="quarto-categories">
    <div class="quarto-category">hobbit</div>
    <div class="quarto-category">smaug</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 7, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="at-a-glance" class="level1">
<h1>At a glance</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 61%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Format</td>
<td>Standard (MTGA)</td>
</tr>
<tr class="even">
<td>Colors</td>
<td>Black / Red / Green (Jund)</td>
</tr>
<tr class="odd">
<td>Archetype</td>
<td>Smaug treasure-hoard burn (avg nonland CMC ~3.7)</td>
</tr>
<tr class="even">
<td>Core mechanic</td>
<td>Treasure tokens × Dragon damage doubling</td>
</tr>
<tr class="odd">
<td>Primary win</td>
<td>Smaug the Magnificent attacks, dealing damage equal to your Treasure count to any target; Twinflame Tyrant doubles it, Rogue’s Passage makes him unblockable</td>
</tr>
<tr class="even">
<td>Secondary win</td>
<td>Desolation of Smaug sweeps non-Dragons and refunds four Dragon-only mana; Dracosaur, Dragonhawk and a Misty Mountains Cold 6/6 Dragon close through the air</td>
</tr>
<tr class="odd">
<td>Land win con</td>
<td>The Lonely Mountain makes Dwarf tokens (cheaper per Equipment); Restless Ridgeline attacks as a 3/4 Dinosaur; Fomori Vault digs for finishers</td>
</tr>
</tbody>
</table>
</section>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>Wyrmgold makes everything produce gold, and Smaug the Magnificent converts every Treasure into damage. He has haste, so the turn he lands he swings for your Treasure count — and Twinflame Tyrant doubles all your damage, turning a six-Treasure attack into twelve.</p>
<p>The Misty Mountains Cold is a one-card engine: four chapters of Treasure that becomes a 6/6 flying Dragon at four or more Treasures. Dori, Jolene, Charming Scoundrel, Goldvein Pick and Hell to Pay’s excess damage all bank tokens, while Smaug, Wicked Worm turns your opponents’ artifacts into a burst of Treasures and Treasure mana into cards. The set identity is the Smaug half of The Hobbit — the Magnificent, Wicked Worm, the saga, Desolation of Smaug, Last Light of Durin’s Day and The Lonely Mountain — braced by Standard’s biggest Dragons. The Hobbit set lands on Arena 2026-08-14; the import list works from that date.</p>
</section>
<section id="approach" class="level1">
<h1>Approach</h1>
<section id="game-plan-phases" class="level2">
<h2 class="anchored" data-anchor-id="game-plan-phases">Game plan phases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>What happens</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Turns 1-3</td>
<td>Develop: Scoundrel, Dori or the saga bank Treasures; removal keeps the board clear</td>
</tr>
<tr class="even">
<td>Turns 4-5</td>
<td>Engine: hasted Smaug swings for Treasure-count damage; Dracosaur exiles into extra plays</td>
</tr>
<tr class="odd">
<td>Turns 6+</td>
<td>Multiply: Twinflame doubles all burn; Desolation wipes into a Dragon; Dragonhawk and Last Light close</td>
</tr>
</tbody>
</table>
</section>
<section id="card-roles" class="level2">
<h2 class="anchored" data-anchor-id="card-roles">Card roles</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Card</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Smaug the Magnificent</td>
<td>Engine and payoff: Treasure each upkeep; on attack, damage equal to your Treasure count to any target</td>
</tr>
<tr class="even">
<td>Smaug, Wicked Worm</td>
<td>Burst ramp and draw: enters with a Treasure per artifact opponents control; Treasure-paid spells draw a card</td>
</tr>
<tr class="odd">
<td>The Misty Mountains Cold</td>
<td>Four chapters of Treasure that become a 6/6 flying Dragon token</td>
</tr>
<tr class="even">
<td>Twinflame Tyrant</td>
<td>Doubles Smaug’s burn, Terror’s pings, Whelp’s pings and Hell to Pay’s excess damage</td>
</tr>
<tr class="odd">
<td>Terror of the Peaks</td>
<td>Every Dragon that enters deals damage equal to its power to any target</td>
</tr>
<tr class="even">
<td>Bonehoard Dracosaur</td>
<td>Upkeep: play the top two exiled cards; Treasure per nonland, 3/1 Dinosaur per land</td>
</tr>
<tr class="odd">
<td>Dragonhawk, Fate’s Tempest</td>
<td>Exiles cards equal to your power-4+ count; unplayed exiles deal 2 each at end step</td>
</tr>
<tr class="even">
<td>Firespitter Whelp</td>
<td>Cheap Dragon that pings each opponent on every noncreature or Dragon spell</td>
</tr>
<tr class="odd">
<td>Jolene, Plundering Pugilist</td>
<td>Attacks with power 4+ make a Treasure; sacrifices a Treasure to ping any target</td>
</tr>
<tr class="even">
<td>Charming Scoundrel</td>
<td>Two-drop that loots, banks a Treasure, or grants a Wicked Role (+1/+1, menace)</td>
</tr>
<tr class="odd">
<td>Dori, Bearer of Friends</td>
<td>Cheap Treasure on entry with a trampling 3/2</td>
</tr>
<tr class="even">
<td>Savage Ventmaw</td>
<td>Attack-ramp: adds {R}{R}{R}{G}{G}{G} that lasts the whole turn</td>
</tr>
<tr class="odd">
<td>Desolation of Smaug</td>
<td>One-sided sweep: 3 damage to every non-Dragon creature, then four Dragon-only mana</td>
</tr>
<tr class="even">
<td>Last Light of Durin’s Day</td>
<td>Six Mountain enters put any Dragon from hand or library onto the battlefield; Mountaincycling</td>
</tr>
<tr class="odd">
<td>Hell to Pay</td>
<td>Removal that banks a Treasure per excess damage (doubled by Twinflame Tyrant)</td>
</tr>
<tr class="even">
<td>Scorching Shot</td>
<td>Five damage to a creature for {R}{R}</td>
</tr>
<tr class="odd">
<td>Goldvein Pick</td>
<td>Equipment that makes a Treasure on combat damage and discounts The Lonely Mountain</td>
</tr>
</tbody>
</table>
</section>
<section id="lands-as-engines" class="level2">
<h2 class="anchored" data-anchor-id="lands-as-engines">Lands as engines</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Land</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>The Lonely Mountain</td>
<td>Land win condition: {4}{R} (one less per Equipment) makes a 2/2 Dwarf; a Mountain for Last Light quest counters</td>
</tr>
<tr class="even">
<td>Restless Ridgeline</td>
<td>Land win condition: becomes a 3/4 Dinosaur that pumps and untaps another attacker</td>
</tr>
<tr class="odd">
<td>Goblin-town</td>
<td>Black-red fixing; late game, two +1/+1 counters on a Goblin or Orc</td>
</tr>
<tr class="even">
<td>Blazemire Verge / Thornspire Verge</td>
<td>Untapped black-red and red-green fixing off basic Mountains, Swamps and Forests</td>
</tr>
<tr class="odd">
<td>Fomori Vault</td>
<td>Dig engine: discard a card to look at the top X cards, where X is your artifact count</td>
</tr>
<tr class="even">
<td>Rogue’s Passage</td>
<td>Finisher: makes Smaug unblockable for the Treasure-count burn</td>
</tr>
<tr class="odd">
<td>Mountain / Swamp / Forest</td>
<td>The Jund core; Mountains double as Last Light fuel</td>
</tr>
</tbody>
</table>
</section>
<section id="curve-and-mana" class="level2">
<h2 class="anchored" data-anchor-id="curve-and-mana">Curve and mana</h2>
<p>Twenty-five lands: thirteen basics (5 Mountain, 4 Swamp, 4 Forest) plus twelve fixing and engine lands. Red is the engine color — Smaug, the saga and the big Dragons want double-red by turn four — so red sources are deepest. Black feeds Smaug, Wicked Worm and removal; green is a light splash for Jolene, Savage Ventmaw and the verges. The curve runs heavy on fours and fives; a two- or three-drop Treasure maker bridges to turn-four Smaug or Dracosaur, and Fomori Vault keeps the top of the deck honest.</p>
</section>
</section>
<section id="gameplay-strategy" class="level1">
<h1>Gameplay strategy</h1>
<section id="early-game" class="level2">
<h2 class="anchored" data-anchor-id="early-game">Early game</h2>
<p>Play a Treasure maker and hold the ground: Charming Scoundrel on two (loot a redundant Dragon away or bank a Treasure), Dori or the saga on three. Do not overcommit into sweepers — one engine plus removal is enough until Smaug arrives. Against aggro, Hell to Pay and Scorching Shot trade one-for-one while the saga banks gold.</p>
</section>
<section id="mid-game" class="level2">
<h2 class="anchored" data-anchor-id="mid-game">Mid game</h2>
<p>Resolve Smaug: he has haste, so he attacks the turn he lands for your Treasure count — a saga at three chapters plus an upkeep Treasure is already four to six damage before the body. Follow with a second Dragon: Bonehoard Dracosaur restocks the hand every upkeep and Terror of the Peaks punishes every further Dragon cast.</p>
</section>
<section id="the-combo-turn" class="level2">
<h2 class="anchored" data-anchor-id="the-combo-turn">The combo turn</h2>
<p>Hold six or more Treasures, cast Twinflame Tyrant, and attack with Smaug through Rogue’s Passage: he deals Treasure-count damage, doubled to twelve or more, plus 4 from the body. Every Dragon cast the same turn triggers Terror for doubled damage, every spell pings through Firespitter Whelp, and Jolene converts spare Treasures into doubled 2-point pings. A developed board routinely deals twenty-plus in one turn.</p>
</section>
<section id="win-condition-2" class="level2">
<h2 class="anchored" data-anchor-id="win-condition-2">Win condition 2</h2>
<p>Desolation of Smaug clears every non-Dragon creature — the opponent’s board and your own Dori, Jolene and Scoundrels — then adds four mana that only feeds Dragon spells. That mana plus Treasures casts Bonehoard Dracosaur, a second Smaug, or Dragonhawk, whose power-4+ count (Smaug, Worm, Terror and Dracosaur all qualify) exiles free cards and burns for each left unplayed. The Misty Mountains Cold finishes independently too: a 6/6 Dragon plus Dwarf tokens from The Lonely Mountain is a wide, evasive clock.</p>
</section>
<section id="mulligan-guide" class="level2">
<h2 class="anchored" data-anchor-id="mulligan-guide">Mulligan guide</h2>
<p>Keep two or three lands with a two- or three-drop Treasure maker or a turn-four Smaug; the saga plus removal is excellent. Ship one-lander openers, hands with three or more five-drops, and hands without turn-two red. Against aggro favor early removal; against control keep Dracosaur or Dragonhawk draws.</p>
</section>
<section id="key-interactions-and-edge-cases" class="level2">
<h2 class="anchored" data-anchor-id="key-interactions-and-edge-cases">Key interactions and edge cases</h2>
<ul>
<li>Smaug’s trigger counts Treasures as it resolves — Jolene’s attack Treasure and Goldvein Pick’s combat Treasure arrive in time for the next swing, not the current one.</li>
<li>Twinflame Tyrant doubles damage from your sources to opponents and their permanents: Smaug’s burn, Terror triggers, Whelp pings, and Hell to Pay’s damage — more excess damage means more Treasures.</li>
<li>Desolation of Smaug damages your own non-Dragons: Dori, Jolene and Charming Scoundrel are casualties; every other creature is a Dragon or Dinosaur Dragon and survives.</li>
<li>Smaug, Wicked Worm counts artifacts opponents control on entry — Equipment, Treasures and artifact creatures feed the burst; Treasure-paid spells draw at 1 life.</li>
<li>Bonehoard Dracosaur’s exiles can be played as lands, but a land still uses your land drop.</li>
<li>The Lonely Mountain enters tapped unless you control an Equipment; with two Goldvein Picks its token costs {2}{R} instead of {4}{R}. Last Light of Durin’s Day counts every Mountain that enters and at six counters puts a Dragon onto the battlefield; Fomori Vault digs X cards where X is your artifact count.</li>
</ul>
</section>
<section id="matchups" class="level2">
<h2 class="anchored" data-anchor-id="matchups">Matchups</h2>
<ul>
<li><strong>Aggro (fliers, lifegain, cats)</strong>: removal-heavy draws hold the ground while the saga banks gold; Desolation resets the board and refunds a Dragon.</li>
<li><strong>Midrange (counters, landfall)</strong>: Smaug’s haste burn races their board; Dracosaur and Dragonhawk out-value their topdecks.</li>
<li><strong>Control</strong>: grind with Dracosaur and Dragonhawk, hold Treasures until Twinflame resolves, and end through Rogue’s Passage.</li>
<li><strong>Combo and big mana</strong>: the deck is the aggressor; speed up the Smaug clock and point removal at their pieces.</li>
</ul>
</section>
</section>
<section id="iterations" class="level1">
<h1>Iterations</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 26%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>Change</th>
<th>Metric deltas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v1 → v2</td>
<td>−2 Gold Rush, +2 Firespitter Whelp (dragon-tribe cohesion swap)</td>
<td>synergy 69.5 → 69.9; sim 55.7 → 62.7%; T4 0.677 → 0.683</td>
</tr>
<tr class="even">
<td>v2 → v3</td>
<td>−1 Scorching Shot, +1 Magmatic Hellkite (on-tribe removal body)</td>
<td>sim 62.7 → 55.3% (worse — reverted)</td>
</tr>
<tr class="odd">
<td>v3 → v4</td>
<td>−2 Goldvein Pick, +1 Terror of the Peaks, +1 Firespitter Whelp</td>
<td>sim 55.3 → 53.7% (worse — reverted)</td>
</tr>
</tbody>
</table>
<p>The final list is the v2 iteration — its battery run was best (sim 62.7%, T4 0.683, P(≥4 lands) 0.688, 0 rotating). Synergy scored 69.9 against the 70.0 gate, the only failing metric; the v3 and v4 cohesion experiments simmed lower and were reverted.</p>
</section>
<section id="deck-list-arena-import" class="level1">
<h1>Deck list (Arena import)</h1>
<pre class="text"><code>Wyrmgold
Deck
4 Smaug the Magnificent
3 Smaug, Wicked Worm
2 Dori, Bearer of Friends
2 Jolene, Plundering Pugilist
2 Charming Scoundrel
2 Terror of the Peaks
2 Twinflame Tyrant
3 Bonehoard Dracosaur
1 Dragonhawk, Fate's Tempest
1 Savage Ventmaw
2 Firespitter Whelp
3 The Misty Mountains Cold
2 Desolation of Smaug
1 Last Light of Durin's Day
2 Hell to Pay
1 Scorching Shot
2 Goldvein Pick
2 The Lonely Mountain
2 Restless Ridgeline
2 Thornspire Verge
2 Blazemire Verge
2 Goblin-town
1 Rogue's Passage
1 Fomori Vault
5 Mountain
4 Swamp
4 Forest</code></pre>


</section>

</main> <!-- /main -->
<script data-goatcounter="https://th3pajay.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>From th3pajay — a new Standard deck guide every morning</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/th3pajay/mtga-decks">Source on GitHub</a></p>
</div>
  </div>
</footer>




</body></html>