<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-16">

<title>Anvil Chorus – MTG Decks — Daily Standard Guides</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a8dd2cfac03084eab458e3b1c626e1f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">MTG Decks — Daily Standard Guides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a>
  <ul class="collapse">
  <li><a href="#game-plan-phases" id="toc-game-plan-phases" class="nav-link" data-scroll-target="#game-plan-phases">Game plan phases</a></li>
  <li><a href="#card-roles" id="toc-card-roles" class="nav-link" data-scroll-target="#card-roles">Card roles</a></li>
  <li><a href="#lands-as-engines" id="toc-lands-as-engines" class="nav-link" data-scroll-target="#lands-as-engines">Lands as engines</a></li>
  <li><a href="#curve-and-mana" id="toc-curve-and-mana" class="nav-link" data-scroll-target="#curve-and-mana">Curve and mana</a></li>
  </ul></li>
  <li><a href="#gameplay-strategy" id="toc-gameplay-strategy" class="nav-link" data-scroll-target="#gameplay-strategy">Gameplay strategy</a>
  <ul class="collapse">
  <li><a href="#early-game" id="toc-early-game" class="nav-link" data-scroll-target="#early-game">Early game</a></li>
  <li><a href="#mid-game" id="toc-mid-game" class="nav-link" data-scroll-target="#mid-game">Mid game</a></li>
  <li><a href="#the-combo-turn" id="toc-the-combo-turn" class="nav-link" data-scroll-target="#the-combo-turn">The combo turn</a></li>
  <li><a href="#win-condition-2" id="toc-win-condition-2" class="nav-link" data-scroll-target="#win-condition-2">Win condition 2</a></li>
  <li><a href="#mulligan-guide" id="toc-mulligan-guide" class="nav-link" data-scroll-target="#mulligan-guide">Mulligan guide</a></li>
  <li><a href="#key-interactions-and-edge-cases" id="toc-key-interactions-and-edge-cases" class="nav-link" data-scroll-target="#key-interactions-and-edge-cases">Key interactions and edge cases</a></li>
  <li><a href="#matchups" id="toc-matchups" class="nav-link" data-scroll-target="#matchups">Matchups</a></li>
  </ul></li>
  <li><a href="#iterations" id="toc-iterations" class="nav-link" data-scroll-target="#iterations">Iterations</a></li>
  <li><a href="#deck-list-arena-import" id="toc-deck-list-arena-import" class="nav-link" data-scroll-target="#deck-list-arena-import">Deck list (Arena import)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Anvil Chorus</h1>
<p class="subtitle lead">Red / White / Blue (three colors) — Storied Dwarf equipment swarm with a token-into-counters payoff, built on The Hobbit set</p>
  <div class="quarto-categories">
    <div class="quarto-category">hobbit</div>
    <div class="quarto-category">dwarves</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 16, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="at-a-glance" class="level1">
<h1>At a glance</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 61%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Format</td>
<td>Standard (MTGA)</td>
</tr>
<tr class="even">
<td>Colors</td>
<td>Red / White / Blue (three colors; blue is the Glamdring adventure and two dual lands)</td>
</tr>
<tr class="odd">
<td>Archetype</td>
<td>Aggro-combo — Storied Dwarves, Equipment, and Dwarf tokens</td>
</tr>
<tr class="even">
<td>Size</td>
<td>60 cards (37 spells and permanents, 23 lands, average mana value 2.08 across nonlands)</td>
</tr>
<tr class="odd">
<td>Signature mechanic</td>
<td>Equipment count feeding two payoffs at once: double strike from Dáin Ironfoot and 2/2 Dwarf tokens from Fíli the Pathfinder and The Lonely Mountain</td>
</tr>
<tr class="even">
<td>Primary win</td>
<td>Equip-wide alpha strike: Dáin Ironfoot gives every equipped attacker double strike while Axe tokens from Iron Hills Blacksmith and Dáin Ironfoot, Dwarven Shortsword and Glamdring stack on the team, and Óin the Brave attacks the turn he arrives</td>
</tr>
<tr class="odd">
<td>Secondary win</td>
<td>Token swarm: Fíli the Pathfinder and Dwarven Shortsword make 2/2 Dwarf tokens, The Lonely Mountain makes them out of spare mana, and Belladonna Took converts each token into life, cards and +1/+1 counters on the whole board</td>
</tr>
<tr class="even">
<td>Land win condition</td>
<td>The Lonely Mountain, a red land that makes 2/2 red Dwarf tokens for {4}{R}, one mana cheaper per Equipment</td>
</tr>
<tr class="odd">
<td>Measured performance</td>
<td>Sim 55.7 percent over three 500-game runs, turn-4 consistency 0.575, four-land probability by turn 4 of 0.561, synergy 70.65</td>
</tr>
</tbody>
</table>
</section>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>Anvil Chorus is the Storied Dwarves build of The Hobbit set, and it is built on one loop: Equipment are artifacts, artifacts are also legendaries and Sagas fuel for Storied, and the same Equipment that turn on Storied are what Dáin Ironfoot, Dwarven Shortsword and The Lonely Mountain are counting.</p>
<p>The deck attacks from a base of eleven Equipment sources across its cheap bodies: Iron Hills Blacksmith and Dáin Ironfoot each create a colorless Axe equipment token on entry, Dwarven Shortsword arrives with a 2/2 red Dwarf token already attached to it, and Glamdring, Foe-hammer is a two-mana Equipment whose equip cost is payable by the same creatures that want the pump. Nothing in the deck costs more than four, and twenty-two of the thirty-seven nonlands cost two or less.</p>
<p>Storied is the engine switch. Controlling three or more artifacts, legendaries or Sagas gives an enduring story for the rest of the game, and the deck almost always gets there by turn three because two Axe tokens plus any of the six legendary Dwarves — or Belladonna Took, or Glamdring itself — already counts. Thorin Oakenshield turns that on into ward {1} for the entire board, saving the team from the first removal spell pointed at it. Óin the Brave becomes a hasty 2/3 that loots. Fíli the Pathfinder gives the whole team +1/+1 and makes a 2/2 red Dwarf token whenever a nontoken Dwarf enters. Kíli the Resourceful makes the first equip of each turn free.</p>
<p>Belladonna Took is the card that ties the two halves together. Every token the deck makes — Axe tokens, Dwarf tokens, the Shortsword’s 2/2 — triggers her, and the third trigger of a turn puts a +1/+1 counter on every creature you control. With Iron Hills Blacksmith and Fíli running, that is a real anthem on turn four, on top of the Equipment pumps.</p>
<p><strong>Note on the set:</strong> The Hobbit set releases on Arena on 2026-08-14. Arena IDs are still empty for most of the set’s printings in the card database, so the import list below takes effect from that release date.</p>
</section>
<section id="approach" class="level1">
<h1>Approach</h1>
<section id="game-plan-phases" class="level2">
<h2 class="anchored" data-anchor-id="game-plan-phases">Game plan phases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>Turns</th>
<th>What the deck is doing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Open</td>
<td>1 to 2</td>
<td>One threat a turn, all of them one or two mana: Dwarven Mauler is a 2/1 for one that makes every later equip cost {2} less, Bofur, Reliable Guardian is a lifelink blocker that can also save an Equipment with its adventure, and Iron Hills Blacksmith is a double striker that leaves an Axe behind</td>
</tr>
<tr class="even">
<td>Build</td>
<td>3 to 4</td>
<td>Three artifacts or legendaries means Storied is online, so Thorin Oakenshield’s ward, Óin the Brave’s haste and Kíli the Resourceful’s free equip all switch on. Fíli the Pathfinder and Dáin Ironfoot arrive and the board doubles in size</td>
</tr>
<tr class="odd">
<td>Alpha</td>
<td>4 to 5</td>
<td>Attach everything that is not already attached with Vow to Erebor and Kíli’s free equip, then attack with Dáin Ironfoot on the board: every equipped attacker has double strike</td>
</tr>
<tr class="even">
<td>Close</td>
<td>5 plus</td>
<td>The Lonely Mountain starts converting spare mana into 2/2 Dwarf tokens while Belladonna Took turns each of them into life, cards and counters, which is the fallback when the Equipment plan is answered</td>
</tr>
</tbody>
</table>
</section>
<section id="card-roles" class="level2">
<h2 class="anchored" data-anchor-id="card-roles">Card roles</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 69%">
</colgroup>
<thead>
<tr class="header">
<th>Role</th>
<th>Cards</th>
<th>What the card actually does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Equipment generators</td>
<td>Iron Hills Blacksmith (4), Dáin Ironfoot (3), Dwarven Shortsword (2)</td>
<td>Blacksmith is a 1/1 for {1}{W} with double strike that creates a colorless Axe equipment token on entry. Dáin Ironfoot is a 1/4 for {2}{R} that creates an Axe and attaches it, then gives each equipped attacking creature double strike. Dwarven Shortsword costs {3}{W}, creates a 2/2 red Dwarf token and attaches itself to it</td>
</tr>
<tr class="even">
<td>Storied payoffs</td>
<td>Thorin Oakenshield (2), Óin the Brave (2), Fíli the Pathfinder (2), Kíli the Resourceful (3)</td>
<td>Thorin Oakenshield is a 3/2 trampler for {R}{W} who, with an enduring story, gives artifacts and creatures ward {1}. Óin the Brave gets +1/+0 and haste. Fíli the Pathfinder gives creatures +1/+1 and makes a 2/2 red Dwarf token on each nontoken Dwarf entry. Kíli the Resourceful makes the first equip of each turn free and draws a card when another Dwarf or Equipment enters</td>
</tr>
<tr class="odd">
<td>Cheapest bodies and enablers</td>
<td>Dwarven Mauler (4), Bofur, Reliable Guardian (4)</td>
<td>Mauler is a 2/1 for {R} that reduces the equip cost of abilities targeting it by {2}, which is how a one-drop carries a three-mana equip. Bofur is a 1/1 lifelink for {W} whose adventure, Concerted Care, gives an artifact or creature hexproof and indestructible for {1}{W} before the creature is cast later from exile</td>
</tr>
<tr class="even">
<td>Token payoff</td>
<td>Belladonna Took (4)</td>
<td>A 2/2 legendary for {1}{W}. Every token that enters counts as a trigger: the first gives 1 life, the second draws a card, the third puts a +1/+1 counter on each creature you control</td>
</tr>
<tr class="odd">
<td>First strike and reach</td>
<td>Nori, Teller of Tales (4)</td>
<td>A 2/2 for {1}{R/W} whose attack trigger gives another attacking creature first strike. With double strike from Dáin Ironfoot, the first-strike grant is what makes a token trade up before regular damage</td>
</tr>
<tr class="even">
<td>Equipment and tricks</td>
<td>Glamdring, Foe-hammer (2), Vow to Erebor (1)</td>
<td>Glamdring is a two-mana Equipment that reduces instant and sorcery costs by the equipped creature’s power, and its Gleam of Death adventure mills six and returns every instant and sorcery among them. Vow to Erebor untaps a creature, gives it +2/+2 and attaches an Equipment to a Dwarf</td>
</tr>
</tbody>
</table>
</section>
<section id="lands-as-engines" class="level2">
<h2 class="anchored" data-anchor-id="lands-as-engines">Lands as engines</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Land</th>
<th>Count</th>
<th>Why it is in the deck</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>The Lonely Mountain</td>
<td>3</td>
<td>The win-condition land. It is a Mountain that enters untapped if you control an Equipment, and for {4}{R} it creates a 2/2 red Dwarf token — one mana cheaper for each Equipment you control, so two Axes make it a two-mana activation</td>
</tr>
<tr class="even">
<td>Fields of Strife</td>
<td>3</td>
<td>Red-white dual that enters tapped and surveils 1 for {2}{R}{W}, which is the cheapest way to filter a spare land into the graveyard in the late game</td>
</tr>
<tr class="odd">
<td>Asgardian Citadel</td>
<td>3</td>
<td>Red-white dual, enters tapped and gains 1 life — the life gain matters because the deck’s own manabase and one-drops are its only early defence</td>
</tr>
<tr class="even">
<td>Gleaming Bastion</td>
<td>2</td>
<td>White-blue dual that taps for {C} and for {W} or {U} while you control a basic land, which is why the deck plays five Plains</td>
</tr>
<tr class="odd">
<td>Stark Industries</td>
<td>2</td>
<td>Blue-red dual that enters tapped and gains 1 life; one of the four lands that tap for blue outright</td>
</tr>
<tr class="even">
<td>Multiversal Passage</td>
<td>2</td>
<td>Fixes whichever colour the hand is missing: choose a basic land type, then pay 2 life to have it enter untapped</td>
</tr>
<tr class="odd">
<td>Plains, Mountain</td>
<td>5 / 3</td>
<td>Basics. White carries the one- and two-drop half of the deck and red carries Dáin Ironfoot, Óin the Brave, Glamdring’s colourless body and The Lonely Mountain</td>
</tr>
</tbody>
</table>
<p>Coloured sources: fifteen white, sixteen red, six blue, including the duals that produce two colours. Blue exists only for the Glamdring adventure face, which is cast for {3}{U} and never affects the deck’s curve, so it is a splash rather than a third engine.</p>
</section>
<section id="curve-and-mana" class="level2">
<h2 class="anchored" data-anchor-id="curve-and-mana">Curve and mana</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Mana value</th>
<th>Count</th>
<th>Cards</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One</td>
<td>8</td>
<td>Dwarven Mauler, Bofur, Reliable Guardian</td>
</tr>
<tr class="even">
<td>Two</td>
<td>22</td>
<td>Iron Hills Blacksmith, Kíli the Resourceful, Óin the Brave, Nori, Teller of Tales, Belladonna Took, Thorin Oakenshield, Glamdring, Foe-hammer, Vow to Erebor</td>
</tr>
<tr class="odd">
<td>Three</td>
<td>3</td>
<td>Dáin Ironfoot</td>
</tr>
<tr class="even">
<td>Four</td>
<td>4</td>
<td>Fíli the Pathfinder, Dwarven Shortsword</td>
</tr>
</tbody>
</table>
<p>Two mana is where the deck lives, and Dáin Ironfoot at three is the only card that demands a specific colour pair. Four-land probability by turn four is 0.561 and turn-four consistency is 0.575, both above the 0.55 threshold the build is held to. Twenty-three lands is deliberate: the deck wants to hit four lands on time for Fíli the Pathfinder and Dwarven Shortsword, and then it stops wanting lands, because extra mana goes into The Lonely Mountain’s token ability.</p>
</section>
</section>
<section id="gameplay-strategy" class="level1">
<h1>Gameplay strategy</h1>
<section id="early-game" class="level2">
<h2 class="anchored" data-anchor-id="early-game">Early game</h2>
<p>Turns one and two are for bodies, not for tricks. Dwarven Mauler is the best one-drop because its {2} equip discount applies to every Equipment you attach to it later, which is what makes Dwarven Shortsword’s {2} equip and Glamdring’s {2} equip effectively free. Iron Hills Blacksmith on turn two is the strongest play in the deck: it is a double striker, and its Axe token is an artifact that counts for Storied, an Equipment that counts for The Lonely Mountain, and a Belladonna Took trigger.</p>
<p>Do not hold Vow to Erebor waiting for a perfect turn. It is a two-mana way to untap a creature, give it +2/+2 and attach an Equipment, and attaching at instant speed after attackers are declared is often two extra damage on a first-strike or double-strike blocker.</p>
</section>
<section id="mid-game" class="level2">
<h2 class="anchored" data-anchor-id="mid-game">Mid game</h2>
<p>Turn three is when the deck decides the game. Dáin Ironfoot on an empty board is an Axe, an attacker, and the double-strike clause waiting to be used. Fíli the Pathfinder on turn four usually makes a token immediately, because it triggers on its own entry, and then again for every other nontoken Dwarf after that.</p>
<p>Storied should be checked every turn. The count is artifacts, legendaries and Sagas: two Axe tokens plus any legendary Dwarf is three, which means Thorin Oakenshield’s ward {1} for the team, Óin the Brave’s haste and Kíli the Resourceful’s free equip are all live from turn three onwards. Ward {1} on everything is what keeps a four-creature Equipment board alive through a single-target removal spell.</p>
</section>
<section id="the-combo-turn" class="level2">
<h2 class="anchored" data-anchor-id="the-combo-turn">The combo turn</h2>
<p>The kill turn needs Dáin Ironfoot, two or more Equipment, and at least three attackers.</p>
<ol type="1">
<li>Play Dáin Ironfoot if he is not already on the board. Each Axe he makes attaches immediately.</li>
<li>Attach the spare Equipment with Kíli the Resourceful’s free equip, then with Vow to Erebor on the creature that is not yet equipped. Every attached Equipment is a point of power, and Dwarven Mauler makes that attach cost {2} less.</li>
<li>Attack with everything. Dáin Ironfoot’s attack trigger gives each equipped attacking creature double strike.</li>
<li>Order Nori, Teller of Tales’ first-strike grant on the largest unequipped attacker, or on the Axe-carrying token, so the first-strike damage happens before the regular damage step.</li>
<li>After combat, activate The Lonely Mountain for {4}{R} reduced by one per Equipment to make another 2/2 Dwarf token, which triggers Belladonna Took.</li>
</ol>
<p>Two Axes, one Dwarven Shortsword and a Glamdring on a board of four creatures is twelve or more points of double-strike damage from a curve that topped out at four mana. If the attack does not kill, the deck is still wide, and the tokens left behind trigger Belladonna Took again on the following turn.</p>
</section>
<section id="win-condition-2" class="level2">
<h2 class="anchored" data-anchor-id="win-condition-2">Win condition 2</h2>
<p>The token plan does not need Dáin Ironfoot at all. Fíli the Pathfinder makes a 2/2 red Dwarf token for each nontoken Dwarf that enters after it, Dwarven Shortsword makes another, and The Lonely Mountain turns a heavily discounted {4}{R} activation — one mana less for each Equipment you control — into one more per turn. Belladonna Took turns each of those tokens into 1 life, then a card, then a +1/+1 counter on every creature you control — so the third token of a turn is effectively an anthem plus a free card.</p>
<p>Against a deck that answers Equipment, the correct line is to stop attaching and start making tokens: keep Fíli the Pathfinder and one Equipment in play for Storied, and let The Lonely Mountain plus Belladonna Took win through counters. Against a deck with many cheap blockers, the opposite is true: attach everything to two creatures and use Dáin Ironfoot’s double strike on a board that is only two attackers wide, because doublestrike damage does not care how many defenders there are.</p>
</section>
<section id="mulligan-guide" class="level2">
<h2 class="anchored" data-anchor-id="mulligan-guide">Mulligan guide</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 57%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Hand shape</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Two lands, Dwarven Mauler and Iron Hills Blacksmith</td>
<td>Keep. This is the deck’s ideal opening: a double striker on turn two and a discount on every later equip</td>
</tr>
<tr class="even">
<td>Two lands, Belladonna Took and any two Equipment sources</td>
<td>Keep. Tokens arrive from turn two onward and she converts the third one into counters</td>
</tr>
<tr class="odd">
<td>One land, no one-drop</td>
<td>Mulligan. The deck needs three mana before Dáin Ironfoot or Fíli the Pathfinder matter</td>
</tr>
<tr class="even">
<td>Three lands, Dáin Ironfoot and one Equipment</td>
<td>Keep. Dáin plus any Axe is the double-strike turn</td>
</tr>
<tr class="odd">
<td>Five lands, Glamdring and one two-drop</td>
<td>Mulligan. Too much mana for a deck that stops at four, and blue is a splash</td>
</tr>
<tr class="even">
<td>Any hand with two Plains and a Mountain</td>
<td>Keep. That is the deck’s red-white core, and Multiversal Passage or Fields of Strife fixes the rest</td>
</tr>
</tbody>
</table>
</section>
<section id="key-interactions-and-edge-cases" class="level2">
<h2 class="anchored" data-anchor-id="key-interactions-and-edge-cases">Key interactions and edge cases</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 53%">
</colgroup>
<thead>
<tr class="header">
<th>Interaction</th>
<th>Ruling detail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Storied is permanent once online</td>
<td>The condition is checked when it becomes true; an enduring story lasts the rest of the game even if you later control fewer than three artifacts, legendaries or Sagas. Axe tokens dying to a board wipe does not switch Thorin Oakenshield’s ward off</td>
</tr>
<tr class="even">
<td>Axe tokens are Equipment, not creatures</td>
<td>Iron Hills Blacksmith and Dáin Ironfoot create colorless Axe equipment tokens with “equipped creature gets +1/+0” and equip {2}. They count for Storied, for The Lonely Mountain’s discount and for Belladonna Took’s token triggers, but they cannot attack on their own</td>
</tr>
<tr class="odd">
<td>Belladonna Took’s three triggers</td>
<td>The life, card and counter clauses trigger once each per turn, in that order. The counters clause is the one worth planning around: hold the third token of the turn, ideally The Lonely Mountain’s or Dwarven Shortsword’s, until after combat so the counters are not wasted</td>
</tr>
<tr class="even">
<td>Dáin Ironfoot’s double strike is a trigger, not a static ability</td>
<td>It happens when he attacks and it applies to attacking creatures that are equipped at that moment. Attach with Kíli the Resourceful’s free equip and with Vow to Erebor in the declare-attackers step, not after</td>
</tr>
<tr class="odd">
<td>Kíli the Resourceful’s free equip</td>
<td>The discount applies only with an enduring story, only to the first equip ability you activate each turn, and only to the equip cost — not to other activated abilities of the Equipment. His draw trigger is once per turn as well, so play him before the Equipment, not after</td>
</tr>
<tr class="even">
<td>Dwarven Mauler’s discount</td>
<td>Equip abilities you activate that target the Mauler cost {2} less. It applies to any Equipment, including Axe tokens, and it is what makes a three-mana equip playable on a two-drop</td>
</tr>
<tr class="odd">
<td>Thorin Oakenshield and ward {1}</td>
<td>The ward applies to artifacts and creatures you control, Axe tokens included, and it is applied to each permanent separately: an opponent answering a single Creature has to pay {1} or lose the spell</td>
</tr>
<tr class="even">
<td>Vow to Erebor’s attach clause</td>
<td>The +2/+2 and untap always happen; the free attach only happens if the target is a Dwarf. Casting it on a token Dwarf from Dwarven Shortsword is the best mode because the token is already the Equipment’s natural carrier</td>
</tr>
<tr class="odd">
<td>Glamdring’s cost reduction</td>
<td>X is the equipped creature’s power, so the reduction applies to instants and sorceries only, not to the creature side of the deck, and it does nothing while Glamdring is unattached</td>
</tr>
<tr class="even">
<td>The Lonely Mountain’s activation</td>
<td>It is sorcery-speed, {4}{R} minus {1} per Equipment you control, and it makes a token, not a land — it is the deck’s only repeatable way to trigger Belladonna Took without spending a card</td>
</tr>
</tbody>
</table>
</section>
<section id="matchups" class="level2">
<h2 class="anchored" data-anchor-id="matchups">Matchups</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 62%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Opponent</th>
<th>Plan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aggro, including fliers and lifegain counters</td>
<td>Race with double strike and do not over-commit Equipment. Bofur, Reliable Guardian blocks with lifelink, Asgardian Citadel and Stark Industries gain 1 life each, and Thorin Oakenshield’s ward {1} makes their single-target removal awkward. Block with the Axe-carrying token rather than a real Dwarf</td>
</tr>
<tr class="even">
<td>Midrange</td>
<td>The strong matchup. Dáin Ironfoot’s double strike beats one big blocker because first-strike damage lands first, and Nori, Teller of Tales gives first strike to whichever attacker is blocked. Belladonna Took’s counters make the token plan bigger than their blockers turn by turn</td>
</tr>
<tr class="odd">
<td>Control</td>
<td>The weak matchup. Board wipes take the Equipment and the tokens with them, so keep Fíli the Pathfinder plus one token source in hand, and remember that Storied survives the wipe even when the artifacts do not. Glamdring’s Gleam of Death refills the hand after a wipe by milling six and returning every instant and sorcery</td>
</tr>
<tr class="even">
<td>Combo</td>
<td>The deck’s clock is turn four or five, which is faster than most combo decks in the format, so the plan is to attack every turn and force them to spend their turn interacting. Equip one creature rather than four so a single removal spell does not turn off the double strike</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="iterations" class="level1">
<h1>Iterations</h1>
<p>The final list is the second version run through the viability battery; the first version failed the simulation gate.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 40%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>What changed</th>
<th>Gate results</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v1</td>
<td>Baseline list: Dwarf legends plus the full Equipment package — Dwalin, Weaponmaster, Thorin, Mountain-king, Bilbo, Luckwearer, Dwarven Mattock, Well-Worn Spatula, Old Fat Spider Can’t See Me and Long-Bodied Grey Dog, on a red-white-blue manabase with Avengers Hangar and two Islands</td>
<td>synergy 70.84 percent (pass), turn-4 0.589 (pass), four lands 0.579 (pass), sim 44.7 percent (FAIL vs 52)</td>
</tr>
<tr class="even">
<td>v2</td>
<td>-2 Dwalin, Weaponmaster, -2 Bilbo, Luckwearer, -2 Dwarven Mattock, -2 Well-Worn Spatula, -2 Old Fat Spider Can’t See Me, -1 Thorin, Mountain-king, -1 Long-Bodied Grey Dog, -1 Vow to Erebor; +4 Nori, Teller of Tales, +4 Belladonna Took, +2 Dwarven Mauler, +1 Iron Hills Blacksmith, +1 Kíli the Resourceful, +1 Dáin Ironfoot; manabase -2 Avengers Hangar, -2 Island, +1 Fields of Strife, +1 Asgardian Citadel, +1 Plains, +1 Mountain (why: the simulator never plays Equipment attachments, so the utility Equipment and the four- and five-mana top end were dead weight in the race; they became one- and two-mana attackers with token payoffs, and the manabase moved to red-white duals that support the same curve)</td>
<td>synergy 70.65 (pass), turn-4 0.575 (pass), four lands 0.561 (pass), sim 55.7 percent (pass)</td>
</tr>
</tbody>
</table>
<p>All gates pass on the final list: size 60 with no missing cards, Standard legal, zero rotating cards, sim 55.7 percent, synergy 70.65, turn-4 consistency 0.575, four-land probability 0.561.</p>
</section>
<section id="deck-list-arena-import" class="level1">
<h1>Deck list (Arena import)</h1>
<pre class="text"><code>Anvil Chorus
Deck
4 Dwarven Mauler
4 Bofur, Reliable Guardian
4 Iron Hills Blacksmith
4 Nori, Teller of Tales
4 Belladonna Took
3 Kíli the Resourceful
3 Dáin Ironfoot
2 Óin the Brave
2 Fíli the Pathfinder
2 Thorin Oakenshield
2 Dwarven Shortsword
2 Glamdring, Foe-hammer
1 Vow to Erebor
3 The Lonely Mountain
3 Fields of Strife
3 Asgardian Citadel
2 Gleaming Bastion
2 Stark Industries
2 Multiversal Passage
5 Plains
3 Mountain</code></pre>


</section>

</main> <!-- /main -->
<script data-goatcounter="https://th3pajay.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>From th3pajay — a new Standard deck guide every morning</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/th3pajay/mtga-decks">Source on GitHub</a></p>
</div>
  </div>
</footer>




</body></html>